### ISSUE TITLE
Suggestion: Server URL, APP ID, Master Key display?

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-dashboard#103]
It would be nice to maybe see these in the main dashboard or well eventually the full config.. but here is the area im talking about.

![image](https://cloud.githubusercontent.com/assets/519563/13585783/a7a8c9c0-e472-11e5-89aa-64548cb01952.png)

**Comment by drew-gross** [comment]
Good idea! This would be quite simple to implement, want to take a crack at it?

**Comment by peterdotjs** [comment]
we should probably leave out master key or at least make it only visible when clicked.

**Comment by drew-gross** [comment]
Yep, kinda like the settings/keys page from dashboard.parse.com. That could potentially be revived in Parse Dashboard, but that would need quite a bit more work.

**Comment by gateway** [comment]
Yea, I was just suggesting an easy way to see a *few* things.. esp the url's to my server's etc.. just a thought

**Comment by drew-gross** [comment]
Server URL does seem like the most useful, yeah

**Comment by drew-gross** [comment]
#121 adds serverURL. Adding more stuff I think will make the index too crowded, maybe. We could potentially bring back the settings pages if we want to display more stuff. @gateway if you still want more info, open a new issue and we can take a look at some different designs for this page.
