### ISSUE TITLE
How to put on Heroku

### ISSUE THREAD

**Issue by devJoshLopez** [ParsePlatform/parse-dashboard#112]
I just used the heroku install button and installed the parse server and connected to my app. I also tested to make sure I am writing and reading data and I am. Now I want to get the parse dashboard. I have no clue where to start. I am new to all of this. Do I create a new app? Do I find it in the add-ons section. I am lost. Please help. :)

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X ] You're running version >=2.1.4 of Parse Server.

- [ X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

**Comment by drew-gross** [comment]
We are working on some installation methods that will make it easier for you to install on Heroku. Some people have already done it by pushing the dashboard repo to a heroku app, but you have to be careful to make sure to keep your master keys secure. If you aren't comfortable doing that, then I recommend installing and running the dashboard locally until we have a better deployment story for Heroku.

**Comment by devJoshLopez** [comment]
Ok thank you Drew. I appreciate the feedback. I have no clue how to push a repo to heroku so I will try and do a local dashboard. Thanks again.

**Comment by meoz** [comment]
@drew-gross Can you elaborate on what you mean by 'make sure to keep your master keys secure' ?
I suppose the parse dashboard runs in an app on the heroku servers, just like the parse-server application is running on the same heroku servers. So how would the master keys possible be leaking out ?

**Comment by drew-gross** [comment]
The master keys are stored in a config file on the dashboard app, and that config file is transmitted to your browser when you access the dashboard. A Man In The Middle, listening to your HTTP connection, could capture your master keys.

**Comment by meoz** [comment]
I see. I'll use it locally until some sort of automatic deployment is put in place like you have suggested.
