### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < dashboard.bundle.js (when trying to access from Heroku)

### ISSUE THREAD

**Issue by astanton** [ParsePlatform/parse-dashboard#114]
I saw another post about this in #91 however I have just pulled the latest version of the code so I would think that fix should be in there.

It runs fine when I run it locally with `npm run dashboard` however when I try to run it on the Heroku server with `npm start` like it says to do, this is the error I'm getting.

Any ideas?  Is it something simple I'm missing?

**Comment by drew-gross** [comment]
Try `npm install` first, or try `npm run dashboard` on Heroku instead of `npm start`.

**Comment by astanton** [comment]
@drew-gross Tried both of those and didn't have any luck with either.

**Comment by drew-gross** [comment]
That is not what I would expect from `npm install`. Can you post the contents of `package.json` please?

**Comment by DazChong** [comment]
I found out that the error occurred on incomplete `npm install` mainly due to process killed by insufficient memory.

**Comment by drew-gross** [comment]
no response in days, closing
