### ISSUE TITLE
unable to connect to server

### ISSUE THREAD

**Issue by kenglou** [ParsePlatform/parse-dashboard#118]
My Parse Dashboard keep showing unable to connect.

- [yes] You're running version >=2.1.4 of Parse Server.

- [yes] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Ubuntu Server 14.04 with LAMP
Parse Server 2.1.4
Parse Dashboard 2.0.0(i seen this at the cofig file)
Apache2 with self-signed reverse proxy address https://localhost:1338 pointing to http://localhost:1337(Parse Server)
Apache2 with self-signed reverse proxy address https://localhost:4141 pointing to http://localhost:4040(Parse Dashboard)

#### Steps to reproduce
just visit https://[local server adress]:4141

#### Logs/Trace
![screen shot 2016-03-10 at 6 22 55 pm](https://cloud.githubusercontent.com/assets/4876665/13666783/523cddcc-e6ee-11e5-8e8f-72d66722a5b1.png)

**Comment by kenglou** [comment]
by the way, I'm able to setup the server and use the https://[local server address]:1338/parse and create an object at the mongodb that i had setup.

**Comment by batkov** [comment]
+1

**Comment by drew-gross** [comment]
Is your parse app running on the same machine your browser is running on? Using a localhost URL in the dashboard means the browser will attempt to communicate with a Parse App on the same machine as it, not the same machine as the the one the dashboard is running on.

**Comment by batkov** [comment]
Yes, parse running on same machine and it is available on same public api with dashboard.
Like:
the-ip:8080 - dashboard
the-ip:1337/parse - parse server

**Comment by kenglou** [comment]
yes running in the same machine

**Comment by drew-gross** [comment]
Have you been able to connect one of the Parse SDKs to the app?

**Comment by kenglou** [comment]
yes, and the fun thing is i'm able to create a ParseObject and save to Parse Server.
I'm using Unity3d Plugin aka DotNet Parse SDK.

**Comment by drew-gross** [comment]
Interesting. The Dashboard just uses the JS SDK so if any SDK can connect on a particular URL, then all should be able to. I'd suggest taking a closer look at your network setup and your URLs.

**Comment by kenglou** [comment]
What i can think of is I never import any data from Parse Hosted backend into parse test server that i created. will that affect the server? 

Currently i try to point the Parse Dashboard server to https://192.168.0.4:1338 and it seems like the following log appear. Anyone has any idea on this?
![screen shot 2016-03-11 at 11 32 43 am](https://cloud.githubusercontent.com/assets/4876665/13692528/20b3963a-e77d-11e5-869a-1a8b14024c6e.png)

**Comment by drew-gross** [comment]
That shouldn't affect the server. Your new screenshot show a different error: ERR_SSL_PROTOCOL_ERROR which could mean many things but most likely is a problem with your SSL certificates. As that is unrelated to Parse Dashboard, I don't think I can help you.

**Comment by kenglou** [comment]
previously i try to configure the server to run 192.168.0.4:1338 in http mode, that's why there are SSL erros. 

right now i try to take away all the SSL stuff, and run the parse-dashboard with configuration of http and run the npm start with insecure http and i still have the error message as the first one.

I'm thinking that i had configure my Parse-Server with all the Master Key and Javascript Key and DotNet CLient Key, is that matters with this?

![screen shot 2016-03-11 at 12 16 44 pm](https://cloud.githubusercontent.com/assets/4876665/13693207/9bdbccc8-e783-11e5-90eb-00a8c23d8c96.png)

**Comment by batkov** [comment]
I have different type of error
![screen shot 2016-03-11 at 9 00 54 am](https://cloud.githubusercontent.com/assets/582671/13695498/fe8e2134-e767-11e5-830b-63a705e98e34.png)

**Comment by DazChong** [comment]
@kenglou have you tried using parse-server external IP? mine localhost same issue as well but works after I edit the config of serverURL to external IP/domain. It works with HTTPS either

**Comment by kenglou** [comment]
@batkov  it seems like your sever url in parse-dashboard.config is not set.

**Comment by batkov** [comment]
Inappropriate screenshot.
So I've set external IP and it worked. 
But don't that mean seme kind of issue?

**Comment by DazChong** [comment]
I believe it was designed to use as an optional web-ui framework that run in local machine and connect to live server. But I build the parse-server and parse-dashboard environment in a VPN for development purpose.

**Comment by kenglou** [comment]
Problem Solved! 

It's the problem that happens when i try to set my server url to a local address url, then i set my apache2 configuration file, then it works @.@lll 

Thank DazChong for pointing it out. 

@batkov  your problem is solved? if yes then i will close this issue.

**Comment by batkov** [comment]
@kenglou So you typed some IP instead of "localhost"?
I've made so and it worked

**Comment by drew-gross** [comment]
Cool, sounds like we are all good here. I guess the confusion is about `localhost` and how the dashboard accesses the server. We'll try to make that more clear.
