### ISSUE TITLE
Cannot GET /1/serverInfo

### ISSUE THREAD

**Issue by felipemobile** [ParsePlatform/parse-dashboard#122]
Hi, I am setting up parse dashboard on localhost but it's not working properly since the dashboard shows the message: "_Server not reachable: server version too low_"

- [x] You're running version >=2.1.4 of Parse Server.

$ npm info parse-server version
$ 2.1.5

#### Environment Setup
OSX El Capitan 10.11.3

#### Steps to reproduce
git clone https://github.com/ParsePlatform/parse-dashboard.git
cd parse-dashboard
npm install
npm run dashboard

curl -X GET -H "X-Parse-Application-Id: XXX" -H "X-Parse-Master-Key: XXX" http://54.94.213.179:1338/1/serverInfo
_Response: Cannot GET /1/serverInfo_

As you can see my parse-dashboard-config.json points to a remote URL, does both Parse Server and Parse Dashboard need to be running on the same machine?

**Comment by drew-gross** [comment]
They do not need to be running on the same machine. Can you check that your mount point is correct? (eg. http://54.94.213.179:1338/1 is the URL you use with your Parse apps and not http://54.94.213.179:1338/parse or http://54.94.213.179:1338/?)

**Comment by felipemobile** [comment]
The mount point is correct:

var api = new ParseServer({
    serverURL: 'http://' + IP + ':' + port + '/1',
    ...
}

**Comment by drew-gross** [comment]
You also need to mount the Parse API at the correct place (the `app.use` line). Does this URL work with your parse apps?

**Comment by felipemobile** [comment]
Just to help resolving the issue, I'm starting the server using forever to ensure the Parse Serve keep running continuously.

**forever start index.js**

This mount path seems to be working to all API's calls except for the Parse Dashboard.
I've an Android and iOS app executing all essential operations.
....

`var mountPath = '/1';`
`app.use(mountPath, api);`

`// Parse Server plays nicely with the rest of your web routes`
`app.get('/', function(req, res) {`
`  res.status(200).send('I dream of being a monster.');`
`});`

`app.listen(port, function() {`
`    console.log('parse-server-example running on port ' + port + '.');`
`});`

**Comment by felipemobile** [comment]
Hmm... it seems like a Parse Server issue.

**Comment by drew-gross** [comment]
OK, good to know. I'll close this issue then.
