### ISSUE TITLE
Parse Dashboard can only be remotely accessed via HTTPS

### ISSUE THREAD

**Issue by RafaRuiz** [ParsePlatform/parse-dashboard#128]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ X] You're running version >=2.1.4 of Parse Server.

- [X ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

http://rafael-ruiz.es:4040
I get the famous sentence "Parse Dashboard can only be remotely accessed via HTTPS" but I have two alternatives:

1.- Setting the environment variable PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1 and start again.

2.- My server already has HTTPS, so if I use https://rafael-ruiz.es:4040 there's an error. Why?

**Comment by drew-gross** [comment]
Your https url doesn't seem to be connecting properly. I'd suggest either digging deeper into your network setup, or running the dashboard locally.

**Comment by DazChong** [comment]
Your web server (Apache/NGINX) need to listen to HTTPS port requests and `Proxy Pass` to Parse-Server / Parse-Dashboard port.
