### ISSUE TITLE
http://localhost:1337/parse/serverInfo 403 (Forbidden)

### ISSUE THREAD

**Issue by arnorhaux** [ParsePlatform/parse-dashboard#129]
- [ x] You're running version >=2.1.4 of Parse Server.
- [ x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

OSX with node js -> 4.3

#### Steps to reproduce

parse-server-example:
git clone
npm install
export values for process.env.DATABASE_URI and process.env.MONGOLAB_URI
npm start

parse-dashboard:
git clone
npm install
put the settings for parse-server running on localhost:1337 in parse-dashboard-config.json
npm run dashboard

I get "Server not reachable - unknow error" and the developer console in Chrome it says:

**http://localhost:1337/parse/serverInfo 403 (Forbidden)**

When I hit the server directly in the terminal with curl post, it is working fine.

**Comment by drew-gross** [comment]
Can you show what specific curl command you are using? Is it pointed at the /serverInfo endpoint?

**Comment by arnorhaux** [comment]
Hi

This would be directly from the parse-server-example:

curl -X POST \
>   -H "X-Parse-Application-Id: myAppId" \
>   -H "Content-Type: application/json" \
>   -d '{"score":1337,"playerName":"Sean Plott","cheatMode":false}' \
>   http://localhost:1337/parse/classes/GameScore

{"objectId":"PV69meU2HD","createdAt":"2016-03-12T09:02:59.439Z"}

If I curl the serverInfo endpoint from the terminal:

workbook:~ arnorhaux$   curl -X GET \
>   -H "X-Parse-Application-Id: myAppId" \
>   -H "X-Parse-Master-Key: myMasterKey" \
>   -H "Content-Type: application/json" \
>   http://localhost:1337/parse/serverInfo
{"error":"unauthorized: master key is required"}

**Comment by drew-gross** [comment]
Can you double check the master key? It looks like you are using the wrong one.

**Comment by peterdotjs** [comment]
@arnorhaux did you make sure to modify the master key in your parse-server-example? https://github.com/ParsePlatform/parse-server-example/blob/master/index.js#L17

**Comment by arnorhaux** [comment]
I purposely did not alter anything and using the default values in app.json file. I am working my way back to just freshly installed parse-server-example and parse-dashboard on my osx.

For now the values are

APP_ID = "myAppId"
MASTER_KEY = "myMasterKey"

{
  "name": "Parse Server Example",
  "description": "An example Parse API server using the parse-server module",
  "repository": "https://github.com/ParsePlatform/parse-server-example",
  "logo": "https://avatars0.githubusercontent.com/u/1294580?v=3&s=200",
  "keywords": ["node", "express", "parse"],
  "env": {
    "PARSE_MOUNT": {
      "description": "Configure Parse API route.",
      "value": "/parse"
    },
    "APP_ID": {
      "description": "A unique identifier for your app.",
      "value": "myAppId"
    },
    "MASTER_KEY": {
      "description": "A key that overrides all permissions. Keep this secret.",
      "value": "myMasterKey"
    },
    "SERVER_URL": {
      "description": "URL to connect to your Heroku instance (update with your app's name + PARSE_MOUNT)",
      "value": "http://localhost:1337/parse"
    }
  },
  "image": "heroku/nodejs",
  "addons": ["mongolab"]
}

**Comment by arnorhaux** [comment]
@drew-gross Can you point to where I am using different values in MASTER_KEY ?

**Comment by peterdotjs** [comment]
@arnorhaux the app.json values I don't believe are being loaded locally by default. Your `masterKey` value is empty when parse-server is created. Can you try putting `myMasterKey` in the location I specified above? Should be working after you do this.

**Comment by arnorhaux** [comment]
Hi

There was a whitespace in the master_key which I exported to enviromental variable on my osx. Maybe it would be good idea that all they keys are read from json config file instead of putting it directly into index.js? Then you will be able to fetch the latest commits from github without any merge conflicts on index.js ?

Anyway thank's for directing me toward the solution and keep up the good work, this is awesome ;)

**Comment by 28389** [comment]
f
