### ISSUE TITLE
"Server not reachable: server version too low"

### ISSUE THREAD

**Issue by r2DoesInc** [ParsePlatform/parse-dashboard#130]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ x] You're running version >=2.1.4 of Parse Server.

- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

I had this working earlier today, but was unable to get my cloud code to show. I started playing with the parser-server-example, and since then, I have been getting this error.

**"Server not reachable: server version too low"**

#### Environment Setup
parse-server@2.1.6
parse-dashboard@2.0.0 
node v4.3.2

#### Steps to reproduce
fresh clone of server and dashboard
configure to point to my instances
load web ui

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

Nothing in dashboard or server logs.

In the dashboard web ui it shows, 
"Server not reachable: server version too low"

**Comment by r2DoesInc** [comment]
Found the issue. It was actually just due to a misconf on my end on the parse server url. The " server version too low" came from its inability to read from /serverInfo. I would suggest some better error messages there.

**Comment by drew-gross** [comment]
Thanks for the note. I'm not sure if it will be possible to update the error message, since we can only tell if the server version is too low if the app doesn't respond to /serverInfo. But if you use e.g the wrong mount point, it will just look like the app is not responding to /serverInfo, so it will think the version is too low. If you come up with a better idea for how to tell the difference between server version 2.1.3 and incorrect URL, I would love to hear it or see a PR. The relevant code is in `src/dashboard/Dashboard.js`.

**Comment by nickjf89** [comment]
I think my serverURL is also the problem. Any suggestions? I am using heroku.

**Comment by shakked** [comment]
I'm very inexperiened with node, what exactly do you mean when you say "inability to read from /serverInfo". I'm having the same issue

**Comment by peterdotjs** [comment]
@shakked did you make sure to have your master key specified in your parse-server to match that of the `parse-dashboard-config.json` ?

**Comment by nickjf89** [comment]
Yes, they match. The odd thing is that when I revert back to a parse server version previous to 2.1.4, the Dashboard says server version too low, BUT my user and installation count are showing. Anything from 2.1.4 upwards and nothing works, and it even screws up my Heroku instance, and my iOS app stops getting data. Very odd.

**Comment by shakked** [comment]
@peterdotjs yes they match

**Comment by peterdotjs** [comment]
@nickjf89 @shakked can you guys provide some more info? Screen shots of console/Network that you guys are seeing in the dashboard. It'll help point to what is going wrong.

**Comment by nickjf89** [comment]
I think it's because I'm using parse-server-example on Heroku. I've just realised. And there is no current process for using parse-server on Heroku, only locally.

**Comment by jphewlin** [comment]
![parsedashboardscreenshot](https://cloud.githubusercontent.com/assets/4521862/14327100/e99bcbc2-fbfe-11e5-9716-6977eb01d2ad.png)

**Comment by NoviceCoder19** [comment]
Hey guys,

Can you let me know how I can update my Parse Server environment or find out which version I'm running?

**Comment by sobinsunny** [comment]
Hey guys,
  I also faced this issue.make sure that  both `parser serve`r and` parse- dashbord` is running. 
run both in different console.

**Comment by alexander-alzate** [comment]
So, you telling me that a malformed URL means the server version is to low? We don't speak about reaching the file but reaching the server! and of course, malformed URLs is an error you can detect, so is the no internet connection problem, and an inexistent service (no http or ACK respond).

**Comment by flovilmart** [comment]
@alexander-alzate I'm not sure what you're refering to, the issue has been closed.

**Comment by alexander-alzate** [comment]
@flovilmart I'm meaning that close doesn't mean fixed and it took me too much time to realize the problem I was having until I land in this post.

The issue is still reproducible because the error message is meaningless.

**Comment by flovilmart** [comment]
@alexander-alzate the resolution has already been given, at the time the issue was closed:


> Thanks for the note. I'm not sure if it will be possible to update the error message, since we can only tell if the server version is too low if the app doesn't respond to /serverInfo. But if you use e.g the wrong mount point, it will just look like the app is not responding to /serverInfo, so it will think the version is too low. If you come up with a better idea for how to tell the difference between server version 2.1.3 and incorrect URL, I would love to hear it or see a PR. The relevant code is in src/dashboard/Dashboard.js.

**Comment by skpaik** [comment]
Please properly add the remote server URL. Then it will work properly.

I faced and solved this way.
Thanks
