### ISSUE TITLE
Create new project from dashboard

### ISSUE THREAD

**Issue by r2DoesInc** [ParsePlatform/parse-dashboard#131]
Would love to be able to create a project from the dashboard. Currently requires creating it on parse.com, then exporting to parse-server.

**Comment by drew-gross** [comment]
We won't be adding the ability to create apps on Parse.com using the dashboard, but it would be pretty neat if some of the infrastructure providers who make it easy to deploy Parse Server added their deploy buttons to the dashboard. In the meantime, [nodechef.com]() has an awesome, tightly integrated setup that gives you a Parse Server and Dashboard together.

**Comment by r2DoesInc** [comment]
I think I may not have been clear enough there. I mean it would be nice to have a way to create a new app on our parse server instance without having to migrate one from parse.com

**Comment by drew-gross** [comment]
Ah. You can absolutely create new instances of Parse Server without migrating from Parse.com. What you can't do is run multiple apps on the same server. There are currently many issues in the Parse Server code base that prevent that from being possible.

**Comment by r2DoesInc** [comment]
Oh I see. Is that something that may be changed in the future?

**Comment by drew-gross** [comment]
There is some effort going into doing that, but it's not really a priority.
