### ISSUE TITLE
How to show DB logs on Dashboard

### ISSUE THREAD

**Issue by davidguardiola** [ParsePlatform/parse-dashboard#132]
I want to see info and error logs on dashboard. 

Thanks in advance.

**Comment by peterdotjs** [comment]
@davidguardiola this requires some changes to the parse-server /logs endpoint to support this. The schema is slightly different right now and only local file logging is supported. If you're interested in contributing let me know and I can point you in the right direction.

**Comment by Kenishi** [comment]
Would one possible solution be to maybe add a server config option to the parse server, example: `logDrainURL: https://dashboard.mydomain.com/myApp/someSpecialDrainEndpoint` to drain the logs to the dashboard? I would think you could maintain file logs and also open up viewing logs on the dashboard.

(Disclaimer: I'm not exactly sure _how_ log drains work, but I've used them on Heroku with other log drain services.)

**Comment by felipemobile** [comment]
I'm not sure if I'm following the right direction but I've been working on a new Parse app that has only three classes: Apps, Users and Installation. After some tweaks and with some minor dashboard adaptations I think I will be able to include new apps as simple as adding a new row to the Apps' class.

To create a new app I've done the following steps:
- Create an empty mongo database
- Restore this database from a previous dumped app (template)
- Create keys with a random algorithm

If you are using Amazon:
- Get the next available port from your Load Balacer
- Create a listener for the new port on your Load Balancer
- Update your httpd.conf with a proxy to the port number
- Restart Apache

My parse server loops a configuration file served from the app above and start each app in a different port number. The downside of this approach is that all apps will be unavailable for a few moments while the apache is restarting, so my next goal is to separate each parse server and have only one api.myserver.com redirecting each request to the right port. In my current environment I've a proxy for each app in my httpd.conf but unfortunately I still have an issue removing rows.

Despite the deadline I've moved all my 22 apps to a self hosted MongoDB, created automation scripts to backup and restore and replicated the data on a local MongoDB server so we can test our apps in a sandbox mode.

**Comment by drew-gross** [comment]
Logs are now available in the dashboard if you use VERBOSE in your Parse Server.
