### ISSUE TITLE
Unable to delete single rows

### ISSUE THREAD

**Issue by r2DoesInc** [ParsePlatform/parse-dashboard#133]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ x] You're running version >=2.1.4 of Parse Server.

- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
https://github.com/yongjhih for parse dash and server running on docker

#### Steps to reproduce
create row via parse dash
select row via dash and attempt to delete

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

```
{code: 107, error: "cannot route batch path /msz/parse/classes/PolicyMember/0sUkWLwujp"}
code: 107
error: "cannot route batch path /msz/parse/classes/PolicyMember/0sUkWLwujp"
```
Note, the proceeding /msz/ is correct. I have the 1337 port mapped to the subdirectory to allow for cleaner usage of multiple servers.
deleting it via the api consoles DELETE method works.

**Comment by drew-gross** [comment]
I'm unable to reproduce this issue, even using a doubly nested mount point as you are. Could you post your server configuration include the serverURL and mount point, and the serverURL you use in your Parse Dashboard Config?

**Comment by r2DoesInc** [comment]
I will have to come back to this issue as I found that cloud code doesnt work over https with an external address. Am working on getting everything running again with the server located at localhost.

**Comment by r2DoesInc** [comment]
dash-

>       "serverURL": "https://pserver.futurehax.org/msz/parse",

what server config do you need? other than the server url its just my keys.

**Comment by drew-gross** [comment]
Also the mount point (from `app.use`)

**Comment by r2DoesInc** [comment]
https://github.com/yongjhih/docker-parse-server/blob/master/index.js

`// Serve the Parse API on the /parse URL prefix
var mountPath = process.env.PARSE_MOUNT || '/parse';
app.use(mountPath, api);`

I dont define a custom mount point, so its `/parse'

**Comment by drew-gross** [comment]
Thats the issue. The parse server expects the server URL passed in the batch delete endpoint (which is used regardless of the number of items being deleted) to match the mount point of the parse server. If you adjust your mount point to be `msz/parse` it should work, although you might also need to modify your subdirectory mapping setup.

**Comment by r2DoesInc** [comment]
Unfortunately that didnt do it.

If i attempt to set the mount point to `/msz/parse` the server then sets runs on `/msz/msz/parse`. The `/msz/` mapping for the port is done on the virtualhost, i dont think the server cares about it.

**Comment by drew-gross** [comment]
Thats what I mean by adjusting your mapping. When you make a request to a "regular" endpoint on parse server, your send the request to `/msz/parse` and your mapping translates that to `/parse`. When you make a request to the `/batch` endpoint, which is what deleting objects does, the URL is part of the body of the request and your mapping can't translate it, so the server received the "raw" URL and gets confused.
