### ISSUE TITLE
SyntaxError: expected expression, got '<'

### ISSUE THREAD

**Issue by jcguarinpenaranda** [ParsePlatform/parse-dashboard#136]
I am running parse-dashboard with Docker, and I have connected to the url http://172.17.0.3:4040, where the service is running.

I am not able to see anything, and the only console error in Firefox says: _SyntaxError: expected expression, got '<'_, when the navigator tries to fetch the file http://172.17.0.3:4040/bundles/dashboard.bundle.js

When I open the file dashboard.bundle.js I see:
```
<!DOCTYPE html>
<html>
  <title>Parse Dashboard</title>
  <body>
    <div id="browser_mount"></div>
    <script src="/bundles/dashboard.bundle.js"></script>
  </body>
</html>

```
I don't understand why is this, because the file should be in javascript, I guess I am doing something wrong but i don't know what is it.

Other question: is it possible to run without docker? I have not used docker until today and something like node index.js would be easier to test

**Comment by drew-gross** [comment]
The is usually because the dashboard hasn't been built yet. You can build and run dashboard without docker using the instructions in the readme. Running without docker is the recommended method, actually.
