### ISSUE TITLE
Can not add custom field to User model

### ISSUE THREAD

**Issue by aristide** [ParsePlatform/parse-dashboard#137]
Hi!! 

Is it possible to add a custom field to the built-in User model? 

I've tried but nothing happened. I've also tried to add a custom field on others built-in models (Role, Production ..)

**Comment by peterdotjs** [comment]
Which version of parse-server are you running? Please update to the latest version of parse-server if you are running `2.1.4`. See #125.

**Comment by aristide** [comment]
you are right @peterdotjs , i was running version 2.1..4. I did update to 2.1.6 and now it's working. I can now add and delete custom fields on the User and other built-in models.  You can close this issue.  Tks!!
