### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by json-park** [ParsePlatform/parse-dashboard#141]
I try "npm install" Amazon Linux AMI

However, an error occurred.

Help me~

![default](https://cloud.githubusercontent.com/assets/16973070/13739345/fbe59c0c-ea0d-11e5-8b46-60baf32aaa06.png)

**Comment by peterdotjs** [comment]
@json-park this is an issue with your machine instance. Other folks had mentioned that it is related to low  memory. #114
