### ISSUE TITLE
Auth to access the dashboard but by app.

### ISSUE THREAD

**Issue by francksb** [ParsePlatform/parse-dashboard#146]
- [x] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

Hello,

> If you want to require a username and password to access the dashboard, you can do so by adding usernames and passwords for HTTP Basic Auth to your configuration file.

It's ok for me. But if I want different user access by app ?
I tried it but without success : 

```
{
  "apps": [
    {
      "serverURL": "https://…",
      "appId": "appid1",
      "masterKey": "masterkey1",
      "appName": "App1",
      "users": [
          {
                "user":"admin",
                "pass":"pass"
          },
          {
                "user":"client1",
                "pass":"pass"
          }
        ]
    },
    {
      "serverURL": "https://…",
      "appId": "appid2",
      "masterKey": "masterkey2",
      "appName": "App2",
   "users": [
          {
                "user":"admin",
                "pass":"pass"
          },
          {
                "user":"client2",
                "pass":"pass"
          }
        ]
    }
  ]
}
```
One idea please ?

**Comment by drew-gross** [comment]
There is currently no support for that use case. You could run multiple instances of the dashboard, or submit a PR (you would need to edit `index.js`)

**Comment by francksb** [comment]
Ok thank you. I will run multiple instances of the dashboard for the moment.
I hope there will be someone to PR :-)

**Comment by khafagy** [comment]
+1

**Comment by felipemobile** [comment]
If you are in a hurry, you can check my pull request. It's a temporary solution to avoid running multiple instances of the dashboard.
https://github.com/ParsePlatform/parse-dashboard/pull/258

It should be nice to have a login screen :-)

**Comment by francksb** [comment]
Yes great job ! 
Thank you very much !

**Comment by drew-gross** [comment]
#258 has been merged.
