### ISSUE TITLE
parse‑dashboard‑config.json file is missing.

### ISSUE THREAD

**Issue by json-park** [ParsePlatform/parse-dashboard#147]
I try "npm start" in Amazon Linux AMI

[parse-dashboard-config.json]
![1](https://cloud.githubusercontent.com/assets/16973070/13774607/298e36c0-eae3-11e5-8191-b0cad9696cb5.png)

[npm start]
![2](https://cloud.githubusercontent.com/assets/16973070/13774624/44bc7934-eae3-11e5-84af-50c07cfe9878.png)

[web browser]
![3](https://cloud.githubusercontent.com/assets/16973070/13774638/62af993a-eae3-11e5-9eb5-6d5f24ac61b8.png)

How can I do?

Help me~

**Comment by darkkiss** [comment]
**path/to/config.json** is the **parse-dashboard-config.json** file ... 
it's best to move your configuration elsewhere .. to avoid losing changes when pulling.


Move you file to another location and point to that file .. like this:

**npm start -- --config /parse.com/parse-dashboard-config.json --port 8080 --allowInsecureHTTP 1**
