### ISSUE TITLE
not able to add a relation

### ISSUE THREAD

**Issue by aristide** [ParsePlatform/parse-dashboard#148]
Hi!! 
I added a Role and User models. I created an Admin role. But i'm not able to add a given user to that role through the dashboard. 

I saw that it was possible on [ parse.com ](http://blog.parse.com/announcements/new-features-in-the-data-browser/)

I'm using parse-server 2.1.6

any Help !!!

**Comment by drew-gross** [comment]
We haven't added that feature yet. If you are interested in contributing, I could give you some pointers for where to start.

**Comment by aristide** [comment]
Yes i'm interested,  I'll appreciate if you can give those pointers for me to handle that.

**Comment by drew-gross** [comment]
Take a look at `BrowserToolbar.react.js` around line 68, and 98, there is some relation specific code. Then, in `BrowserTable.react.js` you will need to make some edits around line 266, as well as maybe adding an `onAddRelation` prop. The biggest change will be in `Browser.react.js`, where you'll need to create the function that adds the relation and pass it as a prop to the `DataBrowser` near line 535. Hope this helps, let me know if you run into any issues!

**Comment by Beingbook** [comment]
Is this in progress?

**Comment by aristide** [comment]
not very fast. your are welcome to help @Beingbook . !!

**Comment by Beingbook** [comment]
This is almost done without adding row from existing one.
Adding new entity and add relation was easy.
But how can I bring existing one to push it?
<img width="832" alt="2016-07-04 6 38 11" src="https://cloud.githubusercontent.com/assets/2682865/16556712/864c5ca4-4216-11e6-877e-a0313a894f1f.png">
I really need help this. I want to reuse filter component to searh element and pick it.

**Comment by MobileVet** [comment]
@Beingbook did you see @drew-gross 's notes?

**Comment by Beingbook** [comment]
@MobileVet already done I submited PR minized

**Comment by drew-gross** [comment]
Thanks @Beingbook! This is now fixed.
