### ISSUE TITLE
Save ordering between different use

### ISSUE THREAD

**Issue by AmbroiseCollon** [ParsePlatform/parse-dashboard#149]
By default, ordering is done with createdAt column. But for some classes, it's not the most convenient. It would be nice that the dashboard remembered on which column it should order. Just like he remembers the places of the columns.

**Comment by AmbroiseCollon** [comment]
Not sure about the good-first-pr means. I guess it means, this is an easy enhancement to make. If so, I'd like some tips to try it out. Thanks !

**Comment by darkkiss** [comment]
Maybe :)  #152

**Comment by peterdotjs** [comment]
@AmbroiseCollon yes when we add the `good-first-pr` tag it's a good opportunity for the community to start getting involved in the project. 

We have several other open issues so if you're interested definitely comment on them and we'll point you in the right direction :) @darkkiss was really fast on this one.

**Comment by AmbroiseCollon** [comment]
I'll sure do ! Thanks for the explanations and thanks @darkkiss to tackle this enhancement !

**Comment by peterdotjs** [comment]
Resolved with #152.
