### ISSUE TITLE
server version too low

### ISSUE THREAD

**Issue by json-park** [ParsePlatform/parse-dashboard#150]
I connect parse-dashboard (node v4.3)

but I got a message below

![2](https://cloud.githubusercontent.com/assets/16973070/13803689/05cd7ce4-eb8a-11e5-8f00-60f03e357e40.png)

[My parse-server - AWS Beanstalk] 
This is Most recent nodejs version  in AWS Beanstalk
![1](https://cloud.githubusercontent.com/assets/16973070/13803806/063fc258-eb8b-11e5-9956-1c437fdf2362.png)

How can i do?

**Comment by drew-gross** [comment]
You need to update your parse server version. Some people have been discussion how to do that here: https://github.com/ParsePlatform/parse-server/issues/873

**Comment by DatzZDeVesh** [comment]
same error I'm getting here! Have u solved that?

**Comment by json-park** [comment]
@DatzZDeVesh I solved this problem. 
You can read below link
https://github.com/ParsePlatform/parse-dashboard/issues/176
