### ISSUE TITLE
"null is not an object error", the table is empty

### ISSUE THREAD

**Issue by thphuc** [ParsePlatform/parse-dashboard#153]
I have some Classes, but there is 1 class gets this error and nothing showing.
Below is the console log:

TypeError: null is not an object (evaluating 'val.constructor')
(anonymous function)dashboard.bundle.js:57097
forEach
(anonymous function)dashboard.bundle.js:57096
BrowserCelldashboard.bundle.js:57100
mountComponentdashboard.bundle.js:24907
ReactCompositeComponent_mountComponentdashboard.bundle.js:18956
mountComponentdashboard.bundle.js:23243
mountChildrendashboard.bundle.js:32048
_createContentMarkupdashboard.bundle.js:29160
mountComponentdashboard.bundle.js:29047
mountComponentdashboard.bundle.js:23243
_mountChildByNameAtIndexdashboard.bundle.js:32281
_updateChildrendashboard.bundle.js:32184
updateChildrendashboard.bundle.js:32133
_updateDOMChildrendashboard.bundle.js:29439
updateComponentdashboard.bundle.js:29268
...

Please help!

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by peterdotjs** [comment]
Could you run with `npm run dev` and provide a stack trace again?

**Comment by thphuc** [comment]
I just tried to run with "npm run dev" and every thing works well.
How can I stop dev mode and restart my production mode?

**Comment by peterdotjs** [comment]
I'm not sure what env you are running you can just kill the process and start again.

**Comment by thphuc** [comment]
My backend is running on Ubuntu

**Comment by drew-gross** [comment]
This issue should have been fixed in a newer version of the dashboard. Please update and let me know if you still have issues.
