### ISSUE TITLE
Dashboard won't load: 404 on /bundles/dashboard.bundle.js

### ISSUE THREAD

**Issue by joeyslack** [ParsePlatform/parse-dashboard#155]
- [x] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
npm install --production

#### Steps to reproduce
npm start

The dashboard does not work at all in production, due to the .gitignore includes of the generated stuff from webpack, etc (/bundles). The app simply will not launch without the presence of /Parse-Dashboard/public/bundles/. The dashboard works in dev after running npm install && npm start, however, when attempting to deploy to a host (ie aws elasticbeanstalk), the ignored files ensure that the app cannot function. It's important that we either send up the generated files (/bundles), or we change the package.json dependencies to also be generating bundles. Trying to understand why these items were added to gitignore ever? More than happy to send a PR if this was a mistake.

**Comment by thphuc** [comment]
I just updated to latest version and I can connect to my dashboard anymore. Please help to fix this ASAP.

**Comment by drew-gross** [comment]
We just overhauled the dashboard installation process, can you check the readme and try to new process?

**Comment by thphuc** [comment]
You mean we can not install from the source code any more?

**Comment by drew-gross** [comment]
You can absolutely install from source, but I would expect most people to not install from source unless they are planning to submit PRs to the dashboard. If you want to contribute and are having issues with the source, I can help, but if you are only planning to use the dashboard and not modify it, I suggest you install from `npm`.

**Comment by Cliffordwh** [comment]
@drew-gross  I get the same problem even if i install it globally and run `parse-dashboard --appID yourAppId --masterKey yourMasterKey --serverURL "https://example.com/parse" --appName optionalName`   I get a blank screen on https://example.com/dashboard . The title shows Parse Dashboard.   Any advise?

**Comment by thphuc** [comment]
I just tried to install by using "npm install -g parse-dashboard", but I got below error. Please help!

`react-router@2.0.0 postinstall /root/.nvm/versions/node/v5.7.0/lib/node_modules/parse-dashboard/node_modules/react-router
> node ./npm-scripts/postinstall.js

module.js:341
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v5.7.0/lib/node_modules/parse-dashboard/node_modules/react-router/npm-scripts/postinstall.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
/root/.nvm/versions/node/v5.7.0/lib
└── (empty)

npm WARN In parse-dashboard@1.0.1 replacing bundled version of history with history@1.9.1`

**Comment by Xenero** [comment]
Same issue here as well. Wish Parse staff would fix it.

**Comment by joeyslack** [comment]
@drew-gross A global npm install doesn't fix the issues with the install though. Production mode is literally missing files, I don't really think anyone tested it?

**Comment by drew-gross** [comment]
We pushed a new version (1.0.2) to `npm` which should fix the issues with `react-router` installation. I just checked http://registry.npmjs.org/parse-dashboard/-/parse-dashboard-1.0.2.tgz and the `dashboard.bundle.js` file is there. I also just tried removing `node`, `npm`, and all my node modules and reinstalling from scratch and it worked.

**Comment by kanersan** [comment]
How do you remove node, npm and all that and reinstall?

**Comment by kanersan** [comment]
So my dashboard and parse server run fine on my local machine. Then when I change configurations and upload to amazon using the elastic beanstalk tool "eb deploy" command. The server crashes and fails and doesn't deploy properly. The error is cannot find dashboard in module.js or something like that. Any help would be appreciated and as parse is shutting down soon, hopefully I figure this out soon also.

**Comment by galenwilkerson** [comment]
hi, I also cannot export a dashboard using File->Download As->Jupyter Dashboards Server Bundle
Get a 404 error (see console below).  Thanks for any help.  

Notebook attached (remove .txt from filename to run)
[dashboard_network.ipynb.txt](https://github.com/ParsePlatform/parse-dashboard/files/732194/dashboard_network.ipynb.txt)


Have installed everything (dashboard, cms, bundle, server) in correct order.

System info:

> $ uname -a
> Linux VirtualBox 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

> $ npm --version
> 4.1.1
> $ node --version
> v7.4.0
> $ jupyter-notebook --version
> 4.2.3


Console:
> $ jupyter-notebook dashboard_network.ipynb 
> [I 12:45:25.119 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
> [I 12:45:25.384 NotebookApp] The port 8888 is already in use, trying another port.
> [I 12:45:25.415 NotebookApp] Loaded server extension jupyter_nbextensions_configurator
> [I 12:45:25.418 NotebookApp] Serving notebooks from local directory: /home/galen/Desktop
> [I 12:45:25.418 NotebookApp] 0 active kernels 
> [I 12:45:25.419 NotebookApp] The Jupyter Notebook is running at: http://localhost:8889/
> [I 12:45:25.419 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> [I 12:45:27.196 NotebookApp] Kernel started: 5e48c589-d3df-4fbd-9aff-a393c57b9917
> [W 12:45:31.416 NotebookApp] 404 GET /notebooks/biblio.bib (127.0.0.1): No such file or directory: biblio.bib
> [W 12:45:31.431 NotebookApp] 404 GET /notebooks/biblio.bib (127.0.0.1) 15.58ms referer=http://localhost:8889/notebooks/dashboard_network.ipynb
> [I 12:45:46.129 NotebookApp] Saving file at /dashboard_network.ipynb
> [W 12:45:46.305 NotebookApp] 404 GET /api/bundlers/dashboards_server_download?notebook=dashboard_network.ipynb (127.0.0.1) 1.43ms referer=http://localhost:8889/notebooks/dashboard_network.ipynb?dashboard
>
