### ISSUE TITLE
You must provide either a config file or an app ID, Master Key, and server URL.

### ISSUE THREAD

**Issue by nickjf89** [ParsePlatform/parse-dashboard#157]
It seems that the path to my package.json and config file is wrong, looking at the logs.

I can't seem to get the logs at the moment, but the path was definitely incorrect when I saw them earlier.

I am getting the error: You must provide either a config file or an app ID, Master Key, and server URL.

And localhost doesn't connect. 

Any suggestions?

**Comment by blu3m4n** [comment]
Same exact error happened to me.

**Comment by drew-gross** [comment]
Sorry about that! We'll have a fix out shortly. In the meantime, you can use our new installation method via `npm` (check the readme), or provide an explicit path to the config file with `node ./Parse-Dashboard/index.js --config ./Parse-Dashboard/parse-dashboard-config.json`.

**Comment by wallydsyh** [comment]
To have the dashboard Running on localhost:4040 : you have to enter that command : 
to the directory where the file "parse - dashboard-config.json " is and run this command:

parse-dashboard --config parse-dashboard-config.json

hope its helps

**Comment by nickjf89** [comment]
I think I tried that; got "parse-dashboard command not found" I believe.

**Comment by wallydsyh** [comment]
there is 2 directory called Parse-Dashboard. and the file is  in the second directory. so in your cmd make sure you are  at in the second directory before running the command

**Comment by wallydsyh** [comment]
![image](https://cloud.githubusercontent.com/assets/17909907/13854542/470c36ae-ec6c-11e5-97f8-755975312452.png)

**Comment by wallydsyh** [comment]
![image](https://cloud.githubusercontent.com/assets/17909907/13854569/6db54c6e-ec6c-11e5-9502-d86e614d5caf.png)

**Comment by peterdotjs** [comment]
@nickjf89 we're fixing an issue where the legacy scripts broke: #158. @wallydsyh is referring to the new option to use parse-dashboard cli to configure the dashboard - instructions are in the [readme](https://github.com/ParsePlatform/parse-dashboard/blob/master/README.md).

**Comment by drew-gross** [comment]
This should be fixed now - do a `git pull` or install version 1.0.2 from `npm`.
