### ISSUE TITLE
Dashboard fails to load class/collection

### ISSUE THREAD

**Issue by TylerBrock** [ParsePlatform/parse-dashboard#160]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=2.1.4 of Parse Server. (N/A, running against api.parse.com)

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Environment is running our own mongodb but still has api served through api.parse.com

#### Steps to reproduce
Navigate to different collections in data browser. (it consistently fails for me)

#### Logs/Trace
Network requests fail with `{"code":105,"error":"[objectObject] is not a valid order key"}`, screen in dashboard shows as blank.

**Comment by TylerBrock** [comment]
Err, scratch that, it started working again. Someone must be changing code on api.parse.com

**Comment by TylerBrock** [comment]
This is happening again this morning. Switching between classes renders a blank data browser because a network request fails. The request look to have a badly formed sort:

POST to `https://api.parse.com/1/classes/MessageScript`
```js
{
  "where":{},
  "limit":200,
  "order":"[objectObject],-createdAt",
  "_method":"GET",
  ...
}
```

Refreshing the dashboard fixes the problem but as soon as i click around on different classes it happens again. Node 4.4.0, parse-dashboard 1.0.2, linux, etc...

**Comment by TylerBrock** [comment]
Just saw 1.0.3 was out and upgraded to see if that helps.

**Comment by drew-gross** [comment]
1.0.3 does have some changes to column ordering. Let me know if it helps.

**Comment by TylerBrock** [comment]
Upgrading to 1.0.3 solved it. This commit specifically ce268d5a6fd7deea89ce86f113b90c274a3bac9e

Thanks
