### ISSUE TITLE
How to keep dashboard running when I log out ssh?

### ISSUE THREAD

**Issue by thphuc** [ParsePlatform/parse-dashboard#162]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

I setup parse-dashboard and run it successfully.
But when I log out of ssh or press Ctrl + D on the terminal, the dashboard stop working.
Please tell me how to keep the dashboard running even when I log out ssh or Ctrl + D?
I tried some solutions (forever, tmux) but no luck!

**Comment by DazChong** [comment]
use `screen`(easier) / `npm run` option.

https://help.ubuntu.com/community/Screen

**Comment by thphuc** [comment]
Thanks @DazChong 
My command is: **parse-dashboard --config my-config-file.json **
How to combine it with npm run or screen?

**Comment by DazChong** [comment]
usually, whenever you exit your SSH session, your active session will be killed. Using `screen` command will create a session that will not be killed even you closed your terminal / exit SSH. And you can do exactly what you usually do.

1. enter `screen` at SSH session.
2. some instruction and info will display, dismiss it with `spacebar`.
3. here you go, a new screen that will remain running even you exit your SSH session.
4. you might run the following command:

```
cd /var/www/parse/parse-dashboard
npm start -- --config some/path/to/parse-dashboard-config.json --allowInsecureHTTP=1
```

**Comment by thphuc** [comment]
After cd to the directory where parse-dashboard-config.son, I have to run below command:
**parse-dashboard --config my-config-file.json --allowInsecureHTTP**

I can not use npm start. Any idea?

**Comment by thphuc** [comment]
OK, I got it working now.
Thanks a lot @DazChong.

**Comment by TESLAA** [comment]
Ypu solved my problem too, thank you both!

**Comment by harshitparmar** [comment]
Hello everyone. Here's a short summered steps you can follow to [Use Screen Command](http://support.bhavibiztech.com/index.php?rp=/knowledgebase/21/How-to-keep-any-process-running-in-background-after-closing-SSH-console-.html) to deploy your node application. Visit our [Support Portal](http://support.bhavibiztech.com/index.php?rp=/knowledgebase) from more helpful articles.
