### ISSUE TITLE
background error

### ISSUE THREAD

**Issue by gowridev** [ParsePlatform/parse-dashboard#165]

**Comment by gowridev** [comment]
i am getting this error node[5485] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21) in background. Could help me in this regard?

**Comment by drew-gross** [comment]
Your link is broken. Also, if you could provide a stack trace or any other info, that would be helpful.

**Comment by gowridev** [comment]
parse-dashboard-master nagaraju$ npm run dashboard

> parse-dashboard@2.0.0 dashboard /Users/nagaraju/Downloads/parse-dashboard-master
> node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch

 28% 19/62 build modulesContainer#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#removeSelf is deprecated. Use Node#remove.
 30% 82/240 build modulesNode#before is deprecated. Use Node#raws.before
Hash: c46eecdfe46ace4a197b  
Version: webpack 1.12.14
Time: 33911ms
              Asset     Size  Chunks             Chunk Names
dashboard.bundle.js  3.31 MB       0  [emitted]  dashboard
        sprites.svg  99.3 kB          [emitted]  
    + 960 hidden modules
2016-03-18 17:22 node[5485] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2016-03-18 17:22 node[5485] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2016-03-18 17:22 node[5485] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2016-03-18 17:22 node[5485] (FSEvents.framework) 2016-03-18 17:22 node[5485] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

I hope this information will be helpful. If you need any information please let me know

**Comment by drew-gross** [comment]
It seems like you are using the old `npm run dashboard` method of using the dashboard. We overhauled the installation process recently to use `npm install` instead, I recommend you try that method. You can find more details in the readme.

**Comment by mrmarcsmith** [comment]
@drew-gross The dockerfile still uses "npm run dashboard" what would be the alternative ENTRYPOINT command since "npm install" is an intermediary step? 
I'm not very familiar with npm so sorry if this is a simple question.

```
FROM node:4.4.2
WORKDIR /src
ADD . /src
RUN cd /src \
 && npm install \
 && npm run build \
 && npm cache clear \
 && rm -rf ~/.npm \
 && rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["npm", "run", "dashboard"]
```
