### ISSUE TITLE
Load fail

### ISSUE THREAD

**Issue by antonfire** [ParsePlatform/parse-dashboard#166]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [y ] You're running version >=2.1.4 of Parse Server.

- [y ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
2.1.6 parse server hosted in Elastic beanstalk with Mongo DB backend
latest dashboard installed on mac

#### Steps to reproduce
Attempt to access dashboard by cli

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

When attempting to open the dashboard using the format below in CLI I get a blank screen with the spinning coloured balls but no dashboard:

CLI command:

parse-dashboard --appId "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" --masterKey "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" --serverURL "http://parseserver-bvicm-env.us-east-1.elasticbeanstalk.com/parse"

Browser error in console:

TypeError: undefined is not a function (evaluating 'e.serverURL.startsWith("https://api.parse.com/1")') dashboard.bundle.js:24300

I have looked for similar issues but can't find one.

Any help much appreciated.

**Comment by antonfire** [comment]
I have also tried:

 parse-dashboard --appId "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" --masterKey "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" --serverURL "http://parseserver-bvicm-env.us-east-1.elasticbeanstalk.com/parse" --allowInsecureHTTP=1

As I have a load balancer on the AWS connection. Same result.

**Comment by peterdotjs** [comment]
From the error it looks like the serverURL is not seen in `parse-dashboard-config.json` but your arguments look correct. Can you try manually putting the information in the config file? https://github.com/ParsePlatform/parse-dashboard#getting-started

**Comment by antonfire** [comment]
I was under the impression that parse-dashboard-config.json was only required if calling with the format:

parse-dashboard --config parse-dashboard-config.json

**Comment by antonfire** [comment]
Where should I put the parse-dashboard-config.son file?

**Comment by antonfire** [comment]
I have installed globally and tried calling parse-dashboard --config parse-dashboard-config.json from a folder containing the json file, this gives "Your config file is missing. Exiting."

I have tried putting the config file in both the bin folder and the folder containing index.js to no avail, same error.

I have tried uninstalling global and installing local and reattempting, same error. Any idea what's wrong here? Very frustrating.

Thanks

**Comment by flovilmart** [comment]
try `parse-dashboard --config ./parse-dashboard-config.json` and make sure the `parse-dashboard-config.json` is in your current folder

**Comment by antonfire** [comment]
Thanks for your reply, I have just tried this an receive the same error... Your config file is missing. Exiting.

**Comment by antonfire** [comment]
Ok no that's working now, was an issue with the file type being saved as text even with the .json extension. It brings up the spinning balls but no dashboard, I get a console error of:

TypeError: undefined is not a function (evaluating 'e.serverURL.startsWith("https://api.parse.com/1")') dashboard.bundle.js:32:37991

**Comment by flovilmart** [comment]
Did you set the serverURL property in your `parse-dashboard-config.json` on each of your apps?

**Comment by antonfire** [comment]
Yes I have:

{
  "apps": [
    {
      "serverURL": "http://parseserver-bvicm-env.us-east-1.elasticbeanstalk.com/parse",
      "appId": "xxx",
      "masterKey": "xxx",
      "appName": "Reel"
    }
  ]
}

**Comment by flovilmart** [comment]
can you locate that line in dashboard.bundle.js:32:37991, and just before, add `console.log(e)`

**Comment by antonfire** [comment]
Yes that logs an object containing:

appId: "myIdIsHere"
appName: "Reel"
masterKey: "myKeyIsHere"
serverURL: "http://parseserver-bvicm-env.us-east-1.elasticbeanstalk.com/parse"

**Comment by flovilmart** [comment]
what browser are you using?

**Comment by antonfire** [comment]
Safari

**Comment by flovilmart** [comment]
can you try `console.log(typeof e.serverURL); console.log(typeof e.serverURL.startsWith);` (or with breakpoints at that place

**Comment by antonfire** [comment]
Just tried on chrome and it works. Those two logs give string and undefined.

**Comment by flovilmart** [comment]
What version of Safari?

**Comment by antonfire** [comment]
Ok I'm running safari 8, .startsWith requires safari v9

**Comment by flovilmart** [comment]
that's why but it should be polyfilled by babel I believe. I'll replace with indexOf === 0 in the meantime

**Comment by antonfire** [comment]
Ok great, thanks. I notice that the security tab for each class has disappeared where previously we could prevent access to that table without MasterKey. Is this correct?

**Comment by flovilmart** [comment]
I have no idea @peterdotjs ?

**Comment by peterdotjs** [comment]
@antonfire the security link is a WIP see: #175

**Comment by antonfire** [comment]
Ok great thanks

**Comment by hetalsonavane** [comment]
I am getting error like parse-dashboard not recognized as internal or external command.Please help me to solve this
