### ISSUE TITLE
Problem with Localhost (Unknown error)

### ISSUE THREAD

**Issue by RobertNNms** [ParsePlatform/parse-dashboard#167]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=2.1.4 of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
parser-server 2.2.0

-------
I have only an error on localhost: (see my screenshoot)
<img width="1081" alt="sans titre" src="https://cloud.githubusercontent.com/assets/8955379/13898257/cf83e9fe-edcb-11e5-8efc-394ecfe59377.png">

Command line serverinfo:
curl -X GET -H "X-Parse-Application-Id: xxxxx" -H "X-Parse-Master-Key: xxxxx" http://localhost:1337/parse/serverInfo
{"features":{"globalConfig":{"create":false,"read":false,"update":false,"delete":false},"hooks":{"create":false,"read":false,"update":false,"delete":false},"logs":{"level":false,"size":false,"order":false,"until":false,"from":false},"push":{"immediatePush":true},"schemas":{"addField":true,"removeField":true,"addClass":true,"removeClass":true,"clearAllDataFromClass":false,"exportClass":false}},"parseServerVersion":"2.2.0"}

Any idea ?

Thanks

**Comment by peterdotjs** [comment]
Can you provide some more information? Any failed server request and the response as well as any console errors.

**Comment by RobertNNms** [comment]
Unfortunately, I don't see any errors (parser-server side -> I enabled  logs (export VERBOSE).
I see only the correct answers to requests from the "dashboard"

**Comment by peterdotjs** [comment]
I was actually referring to client side in the browser.

**Comment by RobertNNms** [comment]
I see only one error :
<img width="1680" alt="sans titre 2" src="https://cloud.githubusercontent.com/assets/8955379/13900268/a353c9ee-ee02-11e5-80ac-d3e2ec4fde54.png">

**Comment by peterdotjs** [comment]
Which version of the dashboard are you running? I think you may have a `masterKey` mismatch between what the dashboard is sending and what the server has. This is resulting in the permission denied 403. Can you check that the masterKeys are matching?

**Comment by RobertNNms** [comment]
Aie, Aie, sorry...:))

Yes, you're right, it was my master key!

Thanks
Robert
