### ISSUE TITLE
STILL server version too low?

### ISSUE THREAD

**Issue by nickjf89** [ParsePlatform/parse-dashboard#168]
So I've just deployed a new instance of the parse-server-example to AWS, which I can see uses parse-server 2.2.0.

All deploy's fine (though I won't be able to update this in future, because it doesn't work...still figuring that out...), but my local parse-dashboard still says server too low...what's going on?

Am I missing something?

**Comment by peterdotjs** [comment]
Can you provide some more information? Any failed server request and the response as well as any console errors.

**Comment by nickjf89** [comment]
I don't get errors...server works fine...dashboard works but says "server version too low". thats literally it..

**Comment by peterdotjs** [comment]
the dashboard makes a request to `serverInfo` endpoint. The response is resulting in "server version too low". Can you paste the response here...

**Comment by nickjf89** [comment]
How do I see the response? Sorry..

**Comment by drew-gross** [comment]
Use the API console of the dashboard, with `serverInfo` as the endpoint and master key checked.

**Comment by nickjf89** [comment]
Thats not an option for me. My Dashboard doesn't work - there is no API console...?

**Comment by peterdotjs** [comment]
@nickjf89 when you open the dashboard right click -> inspect -> click the network tab

From here you can view network requests in the browser and see what the response is.

**Comment by nickjf89** [comment]
Network tab is empty. There was an error: Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by peterdotjs** [comment]
Can you refresh with the inspector open? A network request should be going through. I'm not sure which resource that error is referring to. In any case we're trying to see if `serverInfo` endpoint is returning the right information and if your parse-server is working properly. A curl command to `serverInfo` also works since your API console is not working.

**Comment by nickjf89** [comment]
Thanks, it worked after refreshing. The GET request for serverInfo failed with a 404: Cannot GET /parse/serverInfo

**Comment by drew-gross** [comment]
That usually means your parse server doesn't have the `serverInfo` endpoint, or you are using the wrong path to the endpoint. Check your server to make sure the version is correct. If you installed the server globally, that maybe be causing issues. With `npm`, often the easiest solution is to remove all installations of `parse-server` everywhere and then install again. To check your path, make sure the path you are using in your dashboard configuration is the same as the path you use in your SDKs.

**Comment by nickjf89** [comment]
The server is on AWS.

**Comment by drew-gross** [comment]
You will still need to check your path and make sure your server on AWS is up to date.

**Comment by nickjf89** [comment]
Sorry, I wasn't clear. As I mentioned in the original post, it's a fresh instance of parse-server-example running 2.2.0, so I assume this is fine. And the path used in the dashboard works on my iOS app, so guess the path is good too.

**Comment by drew-gross** [comment]
I'm not super familiar with how AWS works, but it looks like the AWS deploy button relied on a zip folder on S3 that is maintained by AWS and hasn't been kept up to date. For now I'd suggest deploying Parse Server using something other than that button.

**Comment by flovilmart** [comment]
@Raj-LPU what version of the server are you using? (you should see it in the app selector). Also did you configure push properly on parse-server?
