### ISSUE TITLE
Adding new relation creates parent object instead of relation object type

### ISSUE THREAD

**Issue by dcdspace** [ParsePlatform/parse-dashboard#169]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

Parse-Dashboard running on Heroku via npm module
Parse-Server running on Heroku and Mongolab

#### Steps to reproduce
1. Create a relation column on one class (class A) of the type of another class (class B)
2. Click on "View relation" and then click the + button to add a row. 
3. Go back to the parent class, and instead of adding a row like you thought you just did in the relation, you actually added a new object in the parent class.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

My goal is to add a new object to a relation, but instead what is happening is a new object of the parent class is being created. This does not happen on the Parse.com dashboard, but since that is being retired, it would be great to be able to add objects to a relation here. Thanks.

**Comment by drew-gross** [comment]
This is somewhat related to #148 although we should maybe disable the "add" button until we've implemented adding to relations.

**Comment by drew-gross** [comment]
Fixed
