### ISSUE TITLE
Server version stuck at 2.1.4 even upgraded to 2.2.0

### ISSUE THREAD

**Issue by DazChong** [ParsePlatform/parse-dashboard#170]
I'm very pleased by the new updates of both `parse-server` and `parse-dashboard` that install all in a few lines!

I have checked my installed `parse-server` package.json, indeed it is 2.2.0, but dashboard didnt recognize it and use the default value.

**Comment by drew-gross** [comment]
Parse Server loads the version directly from the `package.json`, then transmits it to the dashboard in the `/serverInfo` endpoint. Is it possible that you didn't restart your Parse Server or something like that? If not, please get the response to the `serverInfo` endpoint in the API console and paste the output here.

**Comment by DazChong** [comment]
Thanks for the tips! Now I found what causes the issue. 

My `npm -g install` which installed at `/usr/lib/node_modules/parse-server` (v2.2.0) didnt sync with the local copy which is at '/usr/local/lib/node_modules/parse-server' (2.1.4)

Can I just remove the local copy and edit the symbolic link to use global package instead(as like parse-dashboard)?

My `serverInfo` printed the following:

```
{
  "features": {
    "globalConfig": {
      "create": false,
      "read": false,
      "update": false,
      "delete": false
    },
    "hooks": {
      "create": false,
      "read": false,
      "update": false,
      "delete": false
    },
    "logs": {
      "level": false,
      "size": false,
      "order": false,
      "until": false,
      "from": false
    },
    "push": {
      "immediatePush": true
    },
    "schemas": {
      "addField": true,
      "removeField": true,
      "addClass": true,
      "removeClass": true,
      "clearAllDataFromClass": false,
      "exportClass": false
    }
  },
  "parseServerVersion": "2.1.4"
}
```

**Comment by drew-gross** [comment]
I would recommend you add `parse-server`as an explicit dependency to your project instead of installing globally. If you don't want to do that, then I'd just suggest the old version, yes. Messing with symlinks manually would work, but it doesn't seem like a great idea, so if you can find a solution that avoids that, you should use that solution.
