### ISSUE TITLE
Install on heroku - step by step would be great

### ISSUE THREAD

**Issue by cyboolo** [ParsePlatform/parse-dashboard#171]
Hi

I have my parse server deployed on heroku.

How to install parse dashboard and where?

I read on a close issue that it is explained on the readme file but i don't see any specific explanation.

Do i have to copy parse dashboard on my github repository connected to my heroku app and just add config vars on heroku?

Could it be possible to have a simple step by step to Handle this please?

I am usine adminca but it Will soon not be free so i would like to have a good alternative.

Thank you for your help

**Comment by drew-gross** [comment]
I'd recommend using the dashboard locally if you aren't experienced with Heroku already. Deploying the dashboard means you need to very careful to keep everything secure to prevent your master key from getting leaked.
