### ISSUE TITLE
Wrong path to uploaded file using Parse Dashboard

### ISSUE THREAD

**Issue by duytran1406** [ParsePlatform/parse-dashboard#173]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ √] You're running version >=2.1.4 of Parse Server.

- [ √] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Parse Server 2.2.0 on DigitalOcean Droplet (Ubuntu 14.04)
Database on MongoDb installed on Ubuntu 14.04
Server is running on port 1337 of my subdomain with location /db
Dashboard is running on port 4040 of my subdomain
Not yet using S3 adapter, so still on the default Gridstore for saving new files

#### Steps to reproduce
Upload a file using the Dashboard

#### Logs/Trace
The url of the file should be sub.mydomain.com/db/parse/files/file_name.png
The url is now sub.mydomain.com/parse/files/file_name.png
The file is uploaded and can be viewed by adding missing '/db' path (sub.mydomain.com/db/parse/files/file_name.png)

**Comment by duytran1406** [comment]
By using cURL to query the database, it still shows the wrong path. Im not sure is this error from parse-server or parse-dashboard. 
After uploaded, my file is existed at this link : https://parse.boredninjas.com/parse/files/mflQrWKtkLDJxHXwnF7AemEUG8P2kGuzZGZ4ezVY/68b48bb50e08e33fabadc868c2109651_cover.png
But in database, it was saved as

> "R_Img":{"__type":"File","name":"68b48bb50e08e33fabadc868c2109651_cover.png","url":"**http://parse.boredninjas.com/parse/files/mflQrWKtkLDJxHXwnF7AemEUG8P2kGuzZGZ4ezVY/68b48bb50e08e33fabadc868c2109651_cover.png**"

**Comment by peterdotjs** [comment]
When you're using curl to upload a file is the path as expected? If the path isn't as expected with curl then it would point to a parse-server issue otherwise it would be a dashboard issue.

**Comment by drew-gross** [comment]
I believe this issue is fixed by using

**Comment by drew-gross** [comment]
I believe this issue is fixed by using `publicServerURL` in your server. Check the discussion in parse server around filesadapters.
