### ISSUE TITLE
How can i update paser-server on AWS Beanstalk?

### ISSUE THREAD

**Issue by json-park** [ParsePlatform/parse-dashboard#176]
I connect parse-dashboard (node v4.3)

but I got a message below

![05cd7ce4-eb8a-11e5-8f00-60f03e357e40](https://cloud.githubusercontent.com/assets/16973070/13942154/abbfa76a-f032-11e5-8956-1c6860e5ccb0.png)

So I try updating https://github.com/ParsePlatform/parse-server/issues/873

but I faild updating.

![1](https://cloud.githubusercontent.com/assets/16973070/13942277/ef1dba1e-f033-11e5-9589-8480695a95c9.png)

![2](https://cloud.githubusercontent.com/assets/16973070/13942281/f5434c06-f033-11e5-9aae-262c43d0659b.png)

[app.json]
{ "name": "Parse Server Example", "description": "An example Parse API server using the parse-server module", "repository": "https://github.com/ParsePlatform/parse-server-example", "logo": "https://avatars0.githubusercontent.com/u/1294580?v=3&s=200", "keywords": ["node", "express", "parse"], "env": { "PARSE_MOUNT": { "description": "Configure Parse API route.", "value": "/parse" }, "APP_ID": { "description": "A unique identifier for your app.", "value": "myAppId" }, "MASTER_KEY": { "description": "A key that overrides all permissions. Keep this secret.", "value": "myMasterKey" }, "SERVER_URL": { "description": "URL to connect to your Heroku instance (update with your app's name + PARSE_MOUNT)", "value": "myURL" }, "FILE_KEY": { "description": "The Parse file key", "value": "myFileKey" }, "CLIENT_KEY": { "description": "The Parse client key", "value": "myClientKey" }, "REST_KEY": { "description": "The Parse REST key", "value": "myRestKey" } }, "image": "heroku/nodejs", "addons": ["mongolab"] }

[index.js]
// Example express application adding the parse-server module to expose Parse
// compatible API routes.

var express = require('express');
var ParseServer = require('parse-server').ParseServer;

var databaseUri = process.env.DATABASE_URI;

if (!databaseUri) {
console.log('DATABASE_URI not specified, falling back to localhost.');
}

var api = new ParseServer({
databaseURI: process.env.DATABASE_URI,
cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/main.js',
appId: process.env.APP_ID || '',
fileKey: process.env.FILE_KEY || '',
masterKey: process.env.MASTER_KEY || '',
clientKey: process.env.CLIENT_KEY || '',
restAPIKey: process.env.REST_KEY || '',
serverURL: process.env.SERVER_URL || ''
});
// Client-keys like the javascript key or the .NET key are not necessary with parse-server
// If you wish you require them, you can set them as options in the initialization above:
// javascriptKey, restAPIKey, dotNetKey, clientKey

var app = express();

// Serve the Parse API on the /parse URL prefix
var mountPath = process.env.PARSE_MOUNT || '/parse';
app.use(mountPath, api);

// Parse Server plays nicely with the rest of your web routes
app.get('/', function(req, res) {
res.status(200).send('I dream of being a web site!');
});

var port = process.env.PORT || 1337;

app.listen(port, function() {
console.log('parse-server-example running on port ' + port + '.');
});

[packpage.json]
{ "name": "parse-server-example", "version": "2.1.4", "description": "An example Parse API server using the parse-server module", "main": "index.js", "repository": { "type": "git", "url": "https://github.com/ParsePlatform/parse-server-example" }, "license": "MIT", "dependencies": { "express": "~4.2.x", "kerberos": "~0.0.x", "parse": "~1.6.12", "parse-server": "~2.1.4" }, "scripts": { "start":"node index.js" }, "engines": { "node": ">=4.1" } }

**Comment by drew-gross** [comment]
Unfortunately we can't help with AWS specific issues. Try checking out the docs for AWS. If you discover an issue that is specific to Parse Server, please report the bug on the Parse Server repo.

**Comment by jdzorz** [comment]
@json-park i found the best way to do this is creating a new application version, upload zip package with updated package.json file. then deploy

**Comment by json-park** [comment]
@jdzorz  Hi~ I don't understand your description.
I want more detail description.

**Comment by jdzorz** [comment]
@json-park  Before trying these steps i recommend backing up your instances. or trying in a dev environment.

1. Download newest parse-server-example as zip https://github.com/ParsePlatform/parse-server-example/
2. the zip folder should have contents in the root of the folder. If the zip file structure looks like this:
![image](https://cloud.githubusercontent.com/assets/8130336/14018962/5c36fe6a-f19e-11e5-86df-4398a675dde9.png)
3. You'll need to extract then rezip only the contents.Should look like this:
![image](https://cloud.githubusercontent.com/assets/8130336/14019053/e36c9d04-f19e-11e5-8238-576d3e9e302a.png)
4. Then you can go to EB and in your environment. Select application versions

![image](https://cloud.githubusercontent.com/assets/8130336/14019307/1f7c0e00-f1a0-11e5-816d-063c7a15cacc.png)

5. Upload the new version 
6. Once its uploaded you can then deploy to your EB environment. This will then update your server. Also it leaves you an option to revert changes to your old version.

**Comment by json-park** [comment]
@jdzorz  Thank you very much your kindly answer~
I've solved this problem.

but I got a another problem 

I add code a S3Adapter like below
but deploy is faild.

[index.js]
![default](https://cloud.githubusercontent.com/assets/16973070/14047716/dc6208ec-f2ec-11e5-877d-74122142b937.png)
<br><br>
![3](https://cloud.githubusercontent.com/assets/16973070/14048086/61e27aa4-f2ef-11e5-8a99-df071f96b7bc.png)
<br><br>
![2](https://cloud.githubusercontent.com/assets/16973070/14048097/695191a8-f2ef-11e5-94e5-8788045f9843.png)
<br>

Do you  know this problem?
