### ISSUE TITLE
Is it possible to add new page to dashboard?

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/parse-dashboard#177]
Is it possible to add new page to dashboard without change dashboard source code? I mean something like a plugin. Thanks.

**Comment by peterdotjs** [comment]
No it's not possible. Are you referring to something like a CMS? What would be your use case?

**Comment by zhouhao27** [comment]
I'd like to add a page to send push notification.

**Comment by drew-gross** [comment]
There has been some discussion in #71 about the push console. We are working on it, but would definitely appreciate help if you are interested in helping!

**Comment by drew-gross** [comment]
Sending push notifications will be available after #192 lands
