### ISSUE TITLE
Comment utilisé sa base de donnée sur parse?

### ISSUE THREAD

**Issue by paquem** [ParsePlatform/parse-dashboard#178]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=2.1.4 of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by paquem** [comment]
Je suis un nouveau utilisateur de parse, maintenant je veux que vous puissiez m'aider à savoir comment prendre ma base de données qui est sur mon ordinateur vers parse de grâce...

**Comment by flovilmart** [comment]
You may migrate your local mongo database to mlab following their documentation.

**Comment by iOSassou** [comment]
Tu peux utiliser les procédures de MongoDB pour faire une sauvegarde et ensuite restaurer ta base sur n'importe quel service: https://docs.mongodb.org/manual/tutorial/backup-and-restore-tools/
