### ISSUE TITLE
Not able to run Dashboard

### ISSUE THREAD

**Issue by himanshu1491** [ParsePlatform/parse-dashboard#183]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
mac node version 4.4.1
parse-server version on aws 2.1.6

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

I have install all the dependencies.When I am running  npm run dashboard it gives the following error

npm ERR! Darwin 14.0.0
npm ERR! argv "/usr/local/nodejs/bin/node" "/usr/local/nodejs/bin/npm" "run" "dashboard"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! parse-dashboard@1.0.5 dashboard: `node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the parse-dashboard@1.0.5 dashboard script 'node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch'.
npm ERR! This is most likely a problem with the parse-dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch
npm ERR! You can get their info via:
npm ERR!     npm owner ls parse-dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/himanshu/Documents/parseDashboard/parse-dashboard/npm-debug.log

My congif file is {
	"apps": [{
		"serverURL": "******/parse",
		"appId": "***",
		"masterKey": "***",
		"appName": "asdsa"
	}]
}

**Comment by drew-gross** [comment]
It looks like you are using node version 0.12.0. The minimum version for developing the dashboard is 4.3. Upgrade your node version, or, if you can't do that, try installing via `npm` (check the README for how to do that)

**Comment by himanshu1491** [comment]
It worked Thanks @drew-gross there was some problem with webpack not being getting installed

Anyways Thanks
