### ISSUE TITLE
Parse-Dashboard as middleware?

### ISSUE THREAD

**Issue by robertherber** [ParsePlatform/parse-dashboard#184]
It would be great if this was possible to run this as middleware. It would make sense to run it together with the Parse Server itself.

**Comment by drew-gross** [comment]
Thats a neat idea. I'd happily accept a PR that helps make that happen!

**Comment by khafagy** [comment]
+1

**Comment by thiagoaos** [comment]
+1

**Comment by Gameleon12** [comment]
I'm currently working on such a enhancement in [this PR](https://github.com/ParsePlatform/parse-dashboard/pull/209)

**Comment by mamaso** [comment]
+1

**Comment by flovilmart** [comment]
This has been merged by #217
