### ISSUE TITLE
Enable Config page

### ISSUE THREAD

**Issue by framp** [ParsePlatform/parse-dashboard#185]
Seems like `/config` on parse-server is working with the `PARSE_EXPERIMENTAL_CONFIG_ENABLED=1`, and it seems quite reliable.
What would be the best way to enable it on the dashboard?

Cheers

**Comment by drew-gross** [comment]
Hey, retrieving config on `parse-server` works fine, but changing config doesn't quite work yet. If you want to help with implementing it, just go into `FeaturesRouter.js` on the server, and set all of the options under `globalConfig` to true. This will enable config on the dashboard, but it won't work for setting config. You can still view config though, and if you want to help with setting config it will make it very easy to test your changes!

**Comment by framp** [comment]
That's awesome, I'll just need to work on parse-server then.
Thanks!
