### ISSUE TITLE
how to instal with excite running parse server 

### ISSUE THREAD

**Issue by WahdanZ** [ParsePlatform/parse-dashboard#187]
i instal parse server with azure website , now i want to instal parse dashboard on same website 
i use this command
npm install -g parse-dashboard 
on visual studio online console 
and there are logs 

> npm install -g parse-dashboard
> npm http GET https://registry.npmjs.org/parse-dashboard
> npm http 304 https://registry.npmjs.org/parse-dashboard
> npm WARN engine parse-dashboard@1.0.5: wanted: {"node":">=4.3"} (current: {"node":"v0.10.29","npm":"1.4.10"})
> npm http GET https://registry.npmjs.org/basic-auth
> npm http GET https://registry.npmjs.org/commander
> npm http GET https://registry.npmjs.org/express
> npm http GET https://registry.npmjs.org/json-file-plus
> npm http GET https://registry.npmjs.org/package-json
> npm http 304 https://registry.npmjs.org/commander
> npm http 304 https://registry.npmjs.org/express
> npm http 304 https://registry.npmjs.org/basic-auth
> npm http 304 https://registry.npmjs.org/json-file-plus
> npm http 304 https://registry.npmjs.org/package-json
> npm http GET https://registry.npmjs.org/got
> npm http GET https://registry.npmjs.org/rc
> npm http GET https://registry.npmjs.org/registry-url
> npm http GET https://registry.npmjs.org/semver
> npm http 304 https://registry.npmjs.org/got
> npm http 304 https://registry.npmjs.org/rc
> npm http 304 https://registry.npmjs.org/semver
> npm http 304 https://registry.npmjs.org/registry-url
> npm http GET https://registry.npmjs.org/graceful-readlink
> npm http 304 https://registry.npmjs.org/graceful-readlink
> npm http GET https://registry.npmjs.org/timed-out
> npm http GET https://registry.npmjs.org/unzip-response
> npm http GET https://registry.npmjs.org/url-parse-lax
> npm http GET https://registry.npmjs.org/create-error-class
> npm http GET https://registry.npmjs.org/duplexer2
> npm http GET https://registry.npmjs.org/is-plain-obj
> npm http GET https://registry.npmjs.org/is-redirect
> npm http GET https://registry.npmjs.org/is-retry-allowed
> npm http GET https://registry.npmjs.org/is-stream
> npm http GET https://registry.npmjs.org/lowercase-keys
> npm http GET https://registry.npmjs.org/node-status-codes
> npm http GET https://registry.npmjs.org/object-assign
> npm http GET https://registry.npmjs.org/parse-json
> npm http GET https://registry.npmjs.org/pinkie-promise
> npm http GET https://registry.npmjs.org/read-all-stream
> npm http GET https://registry.npmjs.org/readable-stream
> npm http 304 https://registry.npmjs.org/timed-out
> npm http 304 https://registry.npmjs.org/url-parse-lax
> npm http 304 https://registry.npmjs.org/unzip-response
> npm http 304 https://registry.npmjs.org/is-plain-obj
> npm http 304 https://registry.npmjs.org/is-redirect
> npm http 304 https://registry.npmjs.org/is-retry-allowed
> npm http 304 https://registry.npmjs.org/is-stream
> npm http 304 https://registry.npmjs.org/lowercase-keys
> npm http 304 https://registry.npmjs.org/node-status-codes
> npm http 304 https://registry.npmjs.org/object-assign
> npm http 304 https://registry.npmjs.org/parse-json
> npm http 304 https://registry.npmjs.org/pinkie-promise
> npm http 304 https://registry.npmjs.org/create-error-class
> npm http 304 https://registry.npmjs.org/duplexer2
> npm http 304 https://registry.npmjs.org/read-all-stream
> npm http 304 https://registry.npmjs.org/readable-stream
> npm http GET https://registry.npmjs.org/is
> npm http GET https://registry.npmjs.org/node.extend
> npm http GET https://registry.npmjs.org/promiseback
> npm http 304 https://registry.npmjs.org/is
> npm http 304 https://registry.npmjs.org/promiseback
> npm http 304 https://registry.npmjs.org/node.extend
> npm http GET https://registry.npmjs.org/deep-extend
> npm http GET https://registry.npmjs.org/ini
> npm http GET https://registry.npmjs.org/minimist
> npm http GET https://registry.npmjs.org/strip-json-comments
> npm http 304 https://registry.npmjs.org/deep-extend
> npm http 304 https://registry.npmjs.org/ini
> npm http 304 https://registry.npmjs.org/minimist
> npm http 304 https://registry.npmjs.org/strip-json-comments
> npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"v0.10.29","npm":"1.4.10"})
> npm http GET https://registry.npmjs.org/capture-stack-trace
> npm http GET https://registry.npmjs.org/inherits
> npm http 304 https://registry.npmjs.org/capture-stack-trace
> npm http 304 https://registry.npmjs.org/inherits
> npm http GET https://registry.npmjs.org/pinkie
> npm http GET https://registry.npmjs.org/prepend-http
> npm http 304 https://registry.npmjs.org/pinkie
> npm http 304 https://registry.npmjs.org/prepend-http
> npm http GET https://registry.npmjs.org/error-ex
> npm http 304 https://registry.npmjs.org/error-ex
> npm http GET https://registry.npmjs.org/promise-deferred
> npm http GET https://registry.npmjs.org/is-callable
> npm http 304 https://registry.npmjs.org/promise-deferred
> npm http 304 https://registry.npmjs.org/is-callable
> npm http GET https://registry.npmjs.org/is-arrayish
> npm http 304 https://registry.npmjs.org/is-arrayish
> npm http GET https://registry.npmjs.org/accepts
> npm http GET https://registry.npmjs.org/array-flatten
> npm http GET https://registry.npmjs.org/content-disposition
> npm http GET https://registry.npmjs.org/content-type
> npm http GET https://registry.npmjs.org/cookie
> npm http GET https://registry.npmjs.org/cookie-signature
> npm http GET https://registry.npmjs.org/debug
> npm http GET https://registry.npmjs.org/depd
> npm http GET https://registry.npmjs.org/escape-html
> npm http GET https://registry.npmjs.org/etag
> npm http GET https://registry.npmjs.org/finalhandler
> npm http GET https://registry.npmjs.org/fresh
> npm http GET https://registry.npmjs.org/merge-descriptors
> npm http GET https://registry.npmjs.org/methods
> npm http GET https://registry.npmjs.org/on-finished
> npm http GET https://registry.npmjs.org/parseurl
> npm http GET https://registry.npmjs.org/path-to-regexp
> npm http GET https://registry.npmjs.org/proxy-addr
> npm http GET https://registry.npmjs.org/qs
> npm http GET https://registry.npmjs.org/range-parser
> npm http GET https://registry.npmjs.org/send
> npm http GET https://registry.npmjs.org/serve-static
> npm http GET https://registry.npmjs.org/type-is
> npm http GET https://registry.npmjs.org/utils-merge
> npm http GET https://registry.npmjs.org/vary
> npm http 304 https://registry.npmjs.org/content-type
> npm http 304 https://registry.npmjs.org/cookie
> npm http 304 https://registry.npmjs.org/accepts
> npm http 304 https://registry.npmjs.org/array-flatten
> npm http 304 https://registry.npmjs.org/content-disposition
> npm http 304 https://registry.npmjs.org/cookie-signature
> npm http 304 https://registry.npmjs.org/debug
> npm http 304 https://registry.npmjs.org/depd
> npm http 304 https://registry.npmjs.org/escape-html
> npm http 304 https://registry.npmjs.org/etag
> npm http 304 https://registry.npmjs.org/finalhandler
> npm http 304 https://registry.npmjs.org/fresh
> npm http 304 https://registry.npmjs.org/merge-descriptors
> npm http 304 https://registry.npmjs.org/on-finished
> npm http 304 https://registry.npmjs.org/methods
> npm http 304 https://registry.npmjs.org/parseurl
> npm http 304 https://registry.npmjs.org/proxy-addr
> npm http 304 https://registry.npmjs.org/path-to-regexp
> npm http 304 https://registry.npmjs.org/qs
> npm http 304 https://registry.npmjs.org/range-parser
> npm http 304 https://registry.npmjs.org/send
> npm http 304 https://registry.npmjs.org/serve-static
> npm http 304 https://registry.npmjs.org/utils-merge
> npm http 304 https://registry.npmjs.org/type-is
> npm http 304 https://registry.npmjs.org/vary
> npm http GET https://registry.npmjs.org/promise
> npm http 304 https://registry.npmjs.org/promise
> npm http GET https://registry.npmjs.org/unpipe
> npm http GET https://registry.npmjs.org/core-util-is
> npm http GET https://registry.npmjs.org/isarray
> npm http GET https://registry.npmjs.org/process-nextick-args
> npm http GET https://registry.npmjs.org/string_decoder
> npm http GET https://registry.npmjs.org/util-deprecate
> npm http 304 https://registry.npmjs.org/unpipe
> npm http 304 https://registry.npmjs.org/util-deprecate
> npm http 304 https://registry.npmjs.org/core-util-is
> npm http 304 https://registry.npmjs.org/isarray
> npm http 304 https://registry.npmjs.org/process-nextick-args
> npm http 304 https://registry.npmjs.org/string_decoder
> npm http GET https://registry.npmjs.org/ee-first
> npm http GET https://registry.npmjs.org/mime-types
> npm http GET https://registry.npmjs.org/negotiator
> npm http 304 https://registry.npmjs.org/ee-first
> npm http GET https://registry.npmjs.org/forwarded
> npm http GET https://registry.npmjs.org/ipaddr.js
> npm http 304 https://registry.npmjs.org/mime-types
> npm http 304 https://registry.npmjs.org/negotiator
> npm http GET https://registry.npmjs.org/media-typer
> npm http 304 https://registry.npmjs.org/ipaddr.js
> npm http 304 https://registry.npmjs.org/forwarded
> npm http 304 https://registry.npmjs.org/media-typer
> npm http GET https://registry.npmjs.org/mime-types
> npm http 304 https://registry.npmjs.org/mime-types
> npm http GET https://registry.npmjs.org/destroy
> npm http GET https://registry.npmjs.org/http-errors
> npm http GET https://registry.npmjs.org/mime
> npm http GET https://registry.npmjs.org/ms
> npm http GET https://registry.npmjs.org/statuses
> npm http 304 https://registry.npmjs.org/destroy
> npm http 304 https://registry.npmjs.org/statuses
> npm http 304 https://registry.npmjs.org/mime
> npm http 304 https://registry.npmjs.org/ms
> npm http 304 https://registry.npmjs.org/http-errors
> npm http GET https://registry.npmjs.org/asap
> npm http 304 https://registry.npmjs.org/asap
> npm http GET https://registry.npmjs.org/mime-db
> npm http 304 https://registry.npmjs.org/mime-db
> npm http GET https://registry.npmjs.org/inherits
> npm http 304 https://registry.npmjs.org/inherits
> D:\home\data\monaco\home\npm\parse-dashboard -> D:\home\data\monaco\home\npm\node_modules\parse-dashboard\bin\parse-dashboard
> parse-dashboard@1.0.5 D:\home\data\monaco\home\npm\node_modules\parse-dashboard
> ├── basic-auth@1.0.3
> ├── commander@2.9.0 (graceful-readlink@1.0.1)
> ├── package-json@2.3.1 (registry-url@3.0.3, semver@5.1.0, rc@1.1.6, got@5.5.0)
> ├── json-file-plus@3.3.0 (node.extend@1.1.5, is@3.1.0, promiseback@2.0.2)
> └── express@4.13.4 (escape-html@1.0.3, array-flatten@1.1.1, utils-merge@1.0.0, methods@1.1.2, cookie-signature@1.0.6, range-parser@1.0.3, fresh@0.3.0, merge-descriptors@1.0.1, path-to-regexp@0.1.7, vary@1.0.1, parseurl@1.3.1, cookie@0.1.5, etag@1.7.0, content-type@1.0.1, content-disposition@0.5.1, serve-static@1.10.2, depd@1.1.0, on-finished@2.3.0, finalhandler@0.4.1, qs@4.0.0, proxy-addr@1.0.10, debug@2.2.0, send@0.13.1, accepts@1.2.13, type-is@1.6.12) 

how can i access dashboard now ?

**Comment by drew-gross** [comment]
The README contains the next steps for how to run the dashboard.
