### ISSUE TITLE
Unable to see the parse dashboard on ibm bluemix

### ISSUE THREAD

**Issue by gowridev** [ParsePlatform/parse-dashboard#189]
If i try to open http://parse-dashboard.mybluemix.net/apps (localhost:4040/apps) URL . I am getting an error.

Uncaught SyntaxError: Unexpected token < dashboard.bundle.js:1 
`<!DOCTYPE html>
<html>
  <title>Parse Dashboard</title>
  <body>
    <div id="browser_mount"></div>
    <script src="/bundles/dashboard.bundle.js"></script>
  </body>
</html>`

How to modify URL path (replace "localhost" with other URL, say "http://parse-dashboard.mybluemix.net")?

**Comment by drew-gross** [comment]
That error typically means you didn't build the dashboard before deploying. We now recommend installing the dashboard from `npm` to get the built version.

**Comment by maqen** [comment]
How do you run/install the dashboard on remote server? Installing npm dosen't include `Dockerfile` and npm is now the recommended option.

Cloning and running as docker results in above error. `public/bundles` seem to be ignored in `.gitignore`?

**Comment by drew-gross** [comment]
`public/bundles` is ignored because it contains built files that shouldn't be checked in. Installing the dashboard via `npm` is recommended because `npm` has the built files. If you want to use a different installation method you will need to build the files yourself using `npm run prepublish`.
