### ISSUE TITLE
Unable to see the mongodb items in parse dashboard but all the items are there in mongodb 

### ISSUE THREAD

**Issue by Heman6886** [ParsePlatform/parse-dashboard#197]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=2.1.4 of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

![untitled7879879](https://cloud.githubusercontent.com/assets/12099245/14116707/c29ee104-f5fe-11e5-9200-023e73daa384.png)

**Comment by drew-gross** [comment]
Can you provide some more details? What classes are you looking for and not seeing? Can you try making requests in the API Console to check if the output is what you expect? Schemas endpoint especially.

**Comment by Heman6886** [comment]
i am looking for insatllation and user class and throug api its working

**Comment by drew-gross** [comment]
What is the output of the schemas endpoint in the API Console?

**Comment by Heman6886** [comment]
its in json and exactly what i want

**Comment by drew-gross** [comment]
That endpoint is the exact same one used by the Data Browser to find the list of classes that exist in your app. What happens when you click on the app to try to view the data browser?

**Comment by Heman6886** [comment]
it show me nothing

**Comment by Heman6886** [comment]
and now it checked my master key both at server and dashboard it matching and now it reloads 
![ytyteuntitled](https://cloud.githubusercontent.com/assets/12099245/14117769/cf06c09c-f603-11e5-8f13-9c1444e32ba6.png)

**Comment by drew-gross** [comment]
Does it take you to an empty data browser? Or not go anywhere at all? Also, does it log anything in the console? If you get unauthorised error that means you have some incorrect info in your config.

**Comment by Heman6886** [comment]
yes empty databrowser

**Comment by Heman6886** [comment]
its here 
![jkajsdkj](https://cloud.githubusercontent.com/assets/12099245/14117877/607ab5f6-f604-11e5-9a60-63c5d297267b.png)

**Comment by drew-gross** [comment]
I think if you are getting unauthorised error you need to check the other parts of your config to make sure they match.

**Comment by Heman6886** [comment]
app id and master key are matching

**Comment by drew-gross** [comment]
And server URL?

**Comment by Heman6886** [comment]
its same 
http://ipadrress:1337/parse

**Comment by drew-gross** [comment]
Can you show the chrome debugger when you try to open the data browser? I want to check for error logs or failing network requests.

**Comment by Heman6886** [comment]
can u tell me a good chrome debugger plugin

**Comment by drew-gross** [comment]
the debugger is built in to chrome, you don't need a plugin. I think in Windows you just press ctrl+alt+j, but I use a mac so I don't know if it's the same or not.

**Comment by Heman6886** [comment]
![sadasdas](https://cloud.githubusercontent.com/assets/12099245/14118285/743f4cc6-f606-11e5-8355-858bc357b859.png)

**Comment by drew-gross** [comment]
This really looks like a problem with your configuration. Did you check your mount point as well? 403 Forbidden error means something is configured incorrectly.

**Comment by goggelj** [comment]
Are you on Heroku? I had a similar problem and I am now running with:

{
  "serverURL": "https://my-app.herokuapp.com:443/parse",
  "appId": "appId",
  "masterKey": "masterKey",
  "restKey": "restKey",
  "appName": "my-app"
}

I am running dashboard locally (on my mac) and pointing to both Parse.com
(similar to the above just different url) and Heroku. Everything works.

**Comment by Heman6886** [comment]
No i am using my own vps with centos

**Comment by Heman6886** [comment]
How can i check the mount point

**Comment by Heman6886** [comment]
i have done everything again but still getting the same error

**Comment by drew-gross** [comment]
Your mount point is the part of the URL path that come before all the parse specific stuff. But it looks like you have the right mount point. unauthorized means you have not used the correct keys. Can you make sure you are using the right keys? Do you have any client keys set up on the server? If so, try removing them, or adding them to your dashboard config.

**Comment by Heman6886** [comment]
Its Done Thanksss Man
