### ISSUE TITLE
GridStore url issue

### ISSUE THREAD

**Issue by kilabyte** [ParsePlatform/parse-dashboard#199]
After migration if i add a file via the upload on my instance of the parse dashboard it uploads successfully however the url it generates when i click on the file points to the localhost and not the api endpoint url. All my server urls configs in parse-server and in parse-dashboard DO NOT point to the localhost and point to the absolute api endpoint. The end of the url for the file location is correct. Below is the screen shot of the url and of course there is an error since safari can't resolve localhost on a remote machine.
![screen shot 2016-03-29 at 12 21 00 pm](https://cloud.githubusercontent.com/assets/487948/14120791/5202a390-f5a9-11e5-82cd-da5c4ddfab35.png)

**Comment by kilabyte** [comment]
Tried it on a heroku (parse-server) install and still the same issue. Any ideas?

**Comment by kontextbewusst** [comment]
@kilabyte did you manage to fix this issue?

**Comment by kilabyte** [comment]
@kontextbewusst it was fixed under parse server 2.2.5 i believe by adding the publicServerURL to your config.

**Comment by kontextbewusst** [comment]
@kilabyte awesome, thanks for pointing that out! Works fine now.
