### ISSUE TITLE
Pointer & Relation type column on Class

### ISSUE THREAD

**Issue by hafizapp** [ParsePlatform/parse-dashboard#200]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [y] You're running version >=2.1.4 of Parse Server.

- [y] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Parse-Dashboard running on Local host via npm module
Parse-Server running on Amazon elasticbeans and Mongolab

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

How to add Pointer type column and relation type column? I can see only String, Number, Boolean & Date. 
Please help. 

@gfosco

**Comment by drew-gross** [comment]
Scroll down in the dropdown.
