### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < 

### ISSUE THREAD

**Issue by Webde** [ParsePlatform/parse-dashboard#201]
I Install last commit #192 and then my display is white.

The version #192 no run in my project. it show in terminal `Uncaught SyntaxError: Unexpected token <     dashboard.bundle.js:1`

Help me!!!! :(

**Comment by drew-gross** [comment]
This error means you haven't built the dashboard. Building the dashboard isn't necessary if you install from `npm`. If you want to develop the dashboard or install from source, run `npm run dashboard`.

**Comment by f0ster** [comment]
@drew-gross having this same issue with `npm install` , https://github.com/ParsePlatform/parse-dashboard/issues/593

**Comment by BrotherSymeon** [comment]
I am using the parse-dashboard that I installed using npm and i ran this 
`/home/innocent/.nvm/versions/node/v10.15.3/bin/parse-dashboard --dev --appId david --masterKey david --serverURL "http://172.17.0.3:1337/parse"` 

and the dashboard.bundle.js looks like this
`<!DOCTYPE html>
        <head>
          <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
          <base href="/"/>
          <script>
            PARSE_DASHBOARD_PATH = "/";
          </script>
        </head>
        <html>
          <title>Parse Dashboard</title>
          <body>
            <div id="browser_mount"></div>
            <script src="/bundles/dashboard.bundle.js"></script>
          </body>
        </html>`

can think of anything I could do to get it to work? I am sure I am doing something wrong
