### ISSUE TITLE
Experimenting the new Push send page && separating account access

### ISSUE THREAD

**Issue by felipemobile** [ParsePlatform/parse-dashboard#203]
Hi, I've made a simple change to `Parse-Dashboard/index.js` and `Parse-Dashboard/config.json` files to separate account access to our apps instead of running multiple instances of parse-dashboard. It's a temporary solution while I'm still learning a lot from the sources.

When working on the dashboard, I use `npm run dashboard` to debug and check live updates. The only issue here is that I can't see the push option at the side bar. The push send page is only available when I run `parse-dashboard --config Parse-Dashboard/parse-dashboard-config.json `

What I can do to sync my local changes with the latest Parse-dashboard updates? 

Thanks in advance and keep up the great work guys! :+1: 
Thanks to you, I'm getting better and better in node.js, mondodb, react and so many cool technologies.

```
{
  "users": [
    {
      "user":"user1",
      "pass":"pass",
      "apps": [...]
    },
    {
      "user":"user2",
      "pass":"pass",
       "apps": [...],
    }
  ]
}
```

**Comment by drew-gross** [comment]
This looks like it will be really useful!

To answer your questions:

The push send page is visible if the server tells the dashboard that it supports push. It will do this if it is configured properly, and is on the latest version. It shouldn't be anything to do with how you run the dashboard (maybe it's possible that you have it installed both globally and locally, though, and are running different versions)

Syncing your local changes just requires a git pull and merge or rebase. To get your changes merged into this repo and released to everybody, fork the repo, push your changes to your forked repo, and then submit a pull request here on GitHub.

**Comment by goggelj** [comment]
Hi Drew,

You stated above that "The push send page is visible if the server tells
the dashboard that it supports push. It will do this if it is configured
properly, and is on the latest version."

My dashboard is connected to both Heroku (new/testsing) and Parse.com. In
both cases I do not see the Push page....

Where/how do you configure the server so that the dashboard shows a Push
section?

**Comment by drew-gross** [comment]
You won't be able to see the push page for apps on Parse.com. The guide for configuring push is in the wiki on Parse Server. You can double check by looking at the "serverInfo" endpoint in the API console.

**Comment by goggelj** [comment]
Hmmm...I've already set up ios/apns push notifications on the server. Both
Dev and Prod are working.

Server is running 2.2.2 (as in Parse server example I downloaded yesterday).

Do I need to upgrade parse-server to 2.2.4+?

**Comment by drew-gross** [comment]
Yep

**Comment by felipemobile** [comment]
Hi @drew-gross , I'm running `parse-dashboard --config Parse-Dashboard/parse-dashboard-config.json` with Parse-server 2.1.6 and the push send page is already there.

The push send page disappear when I use `npm run dashboard` . I'm stuck at this difference! 

I think most of my doubts are related to how npm works. How can I build my own version of `parse-dashboard` command and delivery it through `npm install -g parse-dashboard`.

Anyway, I will submit a pull request soon with individual accounts and multiple collaborators for the same app!

**Comment by goggelj** [comment]
hmmm...again, to be sure, is this in Parse Server
<https://github.com/ParsePlatform/parse-server> or is it available in Parse
Server Example <https://github.com/ParsePlatform/parse-server-example>? I
have the latter running on Heroku and when I connect to it with the
dashboard I see no 'push page'...

I have added Push certs (one dev and one prod - both .p12 files as
described here <https://github.com/ParsePlatform/parse-server/wiki/Push>)
to my parse server and I tested push for both prod and dev devices.

What need to be set on the server so that the dashboard opens the push
page? Where?

I tried with updating the package.js to point to parse-server 2.2.4 but no
joy...

Thanks and apologies for the hassle...

**Comment by drew-gross** [comment]
@felipemobile Only I can deliver new packages through `npm install -g parse-dashboard`, but you can create a fork and upload it to `npm` under a new name the same way you would upload any package. Check the `npm` docs for how to do that.

@goggelj It's in `parse-server`. You'll need to update the version of `parse-server` used by your `parse-server-example` to get the latest features.

**Comment by goggelj** [comment]
I've done exactly that:

I have a test version running in heroku using the example server as is. In
its package.json it has:

"dependencies": {
  "express": "~4.11.x",
  "kerberos": "~0.0.x",
  "parse": "~1.8.0",
  "parse-server": "~2.2.2"
},


I also have a prod candidate running on heroku using the following
package.json (using the latest tag in github):


"dependencies": {
  "express": "~4.11.x",
  "kerberos": "~0.0.x",
  "parse": "~1.8.0",
  "parse-server": "~2.2.4"
},

Both apps have the same structure when it comes to push set-up: I have a
certs folder under project folder with the following refs in index.js:

push: {
  // android: {
  //   senderId: '...',
  //   apiKey: '...'
  // },
  ios: [
    {
      pfx: 'certs/dev.push.bundleId: 'com.companyname.app',.p12',
      bundleId: 'com.companyname.app',
      production: false // Dev
    },
    {
      pfx: 'certs/prod.push.bundleId: 'com.companyname.app',.p12',
      bundleId: 'com.companyname.app',
      production: true // Prod
    }
  ]

push and build in heroku:
remote: -----> Build succeeded!
remote:        ├── express@4.11.2
remote:        ├── kerberos@0.0.19
remote:        ├── parse@1.8.1
remote:        └── parse-server@2.2.4

I restarted the app too.

One App is running with WEB_CONCURRENCY=2 and one is running with the
default of 1.

Parse-server-2.2.4 was released 19 hours ago.

Either way, I have no Push page in my dashboard.

Looking at serverInfo in APIConfig returns:

"push": {

            *"immediatePush": true,*

            "scheduledPush": false,

            "storedPushData": false,

            "pushAudiences": false

        },

What am I missing? Does a Push page actually mean a link to a Push page
like there is in parse.com dashboard or are we using the term Page for
something else?

goggelj

**Comment by goggelj** [comment]
As a last resort a I re-ran *npm install -g parse-dashboard*

*T*his was the output:

*/usr/local/bin/parse-dashboard ->
/usr/local/lib/node_modules/parse-dashboard/bin/parse-dashboard*
*parse-dashboard@1.0.6 /usr/local/lib/node_modules/parse-dashboard*
*├── basic-auth@1.0.3*
*├── commander@2.9.0 (graceful-readlink@1.0.1)*
*├── package-json@2.3.1 (registry-url@3.0.3, semver@5.1.0, rc@1.1.6,
got@5.5.0)*
*├── express@4.13.4 (escape-html@1.0.3, array-flatten@1.1.1,
utils-merge@1.0.0, content-type@1.0.1, merge-descriptors@1.0.1,
cookie-signature@1.0.6, vary@1.0.1, fresh@0.3.0, methods@1.1.2,
serve-static@1.10.2, range-parser@1.0.3, etag@1.7.0, parseurl@1.3.1,
content-disposition@0.5.1, path-to-regexp@0.1.7, cookie@0.1.5, depd@1.1.0,
qs@4.0.0, on-finished@2.3.0, finalhandler@0.4.1, debug@2.2.0,
proxy-addr@1.0.10, send@0.13.1, type-is@1.6.12, accepts@1.2.13)*
*└── json-file-plus@3.3.0 (node.extend@1.1.5, is@3.1.0, promiseback@2.0.2)*

Not sure what changed in from the dashboard perspective between last night
and later last night but it was the dashboard and not parse-server.

Solved.

**Comment by drew-gross** [comment]
Thanks! Maybe it was an `npm` caching issue or something.
