### ISSUE TITLE
Steps to configure Dashboard for HTTPS

### ISSUE THREAD

**Issue by Vortec4800** [ParsePlatform/parse-dashboard#204]
Sorry if this question is a bit thick... How do you configure the dashboard to use HTTPS? Don't you need to configure the Express server for your certificates and keys? I didn't see a place in index.js to do this. Perhaps I'm misunderstanding?

**Comment by drew-gross** [comment]
Most people who are deploying the dashboard are deploying behind a proxy or load balancer that terminates SSL. I'd recommend that route, or running the dashboard locally. If you want to add support for direct HTTPS connections, that would be much appreciated!

**Comment by Vortec4800** [comment]
I see, so it doesn't accept direct HTTPS at the moment? That would explain my confusion.

I'll be running the dashboard on a separate VPS from the Parse API or Mongo database servers to keep things simple and separate for the dashboard. I don't really want to set up and run a separate web server or load balancer when Express is enough for my needs. It needs to be on the public internet so my entire team can access it, so I'll want to run it using HTTPS with auth support.

It seems like maybe I just need to modify the Express setup in the index.js file to work with certificate credentials? I'll work on that and if I get it working I'll send a PR with configurable/optional cert details.

**Comment by drew-gross** [comment]
Yep, `index.js` is the right place. Thanks for helping!
