### ISSUE TITLE
New Application Create

### ISSUE THREAD

**Issue by hafizapp** [ParsePlatform/parse-dashboard#205]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

Is there any way to add New Application using Parse-Dashboard? @gfosco 

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
No, you'll need to add apps via your config file.

**Comment by hafizapp** [comment]
@drew-gross Thanks
But then how I get appid, masterkey for new app?
Also what about the new mongoDB default database?

**Comment by drew-gross** [comment]
The app id and master key are in the configuration of your server. You will probably have to set up a new mongoDB database, although you might be able to reuse an existing one if you are careful.

**Comment by gfosco** [comment]
The dashboard can be used to administer multiple apps, but parse-server is intended to run a single app.  So if you want a 'new' app, you'll need to run another instance of parse-server and then add it to the dashboard configuration as you did the first one.
