### ISSUE TITLE
Do not have analysis function

### ISSUE THREAD

**Issue by scorpion1750** [ParsePlatform/parse-dashboard#212]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
dashboard :2.0.0

#### Steps to reproduce
When will you develop the analysis function in the future?Is there other solution for this? Can you recomand  to me?

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by bohemima** [comment]
Analytics will most likely not be added to parse-server in the near future. There are multiple other good services that can handle this, including Facebook Events, Google Analytics, Flurry to name a few.
