### ISSUE TITLE
Add the ability to set apps as "dev" or "prod"

### ISSUE THREAD

**Issue by goggelj** [ParsePlatform/parse-dashboard#213]
Tried to find the parameter name that would allow me to set the operational state of the app - could not find it.

I have a couple of apps, one of which is prod. In the dashboard, even the prod app that is on Parse.com appears as 'Dev'. I assume I need an entry in parse-dashboard-config. If so, what is the parameter name? If not, where do I set it?

Parse-Dashboard:
<img width="90" alt="screen shot 2016-04-01 at 09 44 16" src="https://cloud.githubusercontent.com/assets/3116350/14202177/7622493c-f7ee-11e5-8aa0-62a46d45731e.png">

Parse.com:
<img width="103" alt="screen shot 2016-04-01 at 09 44 54" src="https://cloud.githubusercontent.com/assets/3116350/14202178/7622d460-f7ee-11e5-805b-0044529273b3.png">

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [y] You're running version >=2.1.4 of Parse Server.

- [y] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
Currently there is no way to do that. If you want to add it, that would be a pretty good first PR!

**Comment by dcdspace** [comment]
Just added this, will send a PR soon.

**Comment by drew-gross** [comment]
This is done now
