### ISSUE TITLE
Option to run dashboard on localhost only

### ISSUE THREAD

**Issue by hpello** [ParsePlatform/parse-dashboard#222]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [✔] You're running version >=2.1.4 of Parse Server.

- [✔] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Ubuntu 15.10
parse-dashboard v1.0.7 installed with `npm install -g parse-dashboard`

#### Steps to reproduce
`parse-dashboard --config myconfig.json`

#### Logs/Trace
```
The dashboard is now available at http://localhost:4040/
```
```
$ sudo netstat -plaunt | grep 4040
tcp6       0      0 :::4040                 :::*                    LISTEN      32108/node
```
------------------------

Hello,

Is it possible to have the dashboard listen on localhost only?
So far, the app listens on `::` (or IPv4 `0.0.0.0`) by default, which makes the message `available at http://localhost:4040/` confusing.

A possibility would be to have an `--host` option, and/or a `HOST` env var (similarly to the option for the port) and pass it directly to express's `listen()` function along with the port.

My goal is to run the dashboard behind a HTTPS nginx proxy, and by listening on localhost only I can better restrict the access.

**Comment by flovilmart** [comment]
That's a very very valid point! Would you feel you could make a PR for that, that should be somewhat straightforward.

**Comment by hpello** [comment]
Hello,

Any news about this? I'll be happy to modify my pull request if needed.
