### ISSUE TITLE
parse-dashboard server as a background service

### ISSUE THREAD

**Issue by json-park** [ParsePlatform/parse-dashboard#223]
Hello.

I start parse-dashboard on AWS Linux AMI 

![default](https://cloud.githubusercontent.com/assets/16973070/14246756/301af534-faa4-11e5-85e0-6bfe2373b4e4.png)

However It is stop when close a commend window

I want my parse-dashboard server to run in the background

How can i do?

**Comment by flovilmart** [comment]
you can use:
1. nohup (to prevent the script from exiting), 
2. an upstart script (in /etc/init.d so your server starts at startup),
3. a process manager (pm2, forever, nodemon, so the server restarts on crashes)

I suggest a combination of 2 and 3.

further reading:

http://stackoverflow.com/questions/13982257/upstart-script-for-node-js-app
https://gist.github.com/steveneaston/58a33e6cc280ca07f4c5
https://www.exratione.com/2013/02/nodejs-and-forever-as-a-service-simple-upstart-and-init-scripts-for-ubuntu/
