### ISSUE TITLE
sending JSON push issue, incorrect content type 

### ISSUE THREAD

**Issue by mohshaheen** [ParsePlatform/parse-dashboard#233]
Hello 

i have noticed that the dashboard desnot send the JSON push notificaiton correctly

when i try to send JSON  like  
{
 "alert": "test ",
   "url": "http://ikhair.net"   }

from the dashboard  , i am not receiving any thing , while from rest api it works with no issue 
the only deference in posted Rest request from dashboard vs the Manuel REST call is the content type 
, on dashboard its always  'text/plain' even if JSON option is selected on the text box .

while with direct RESTAPI the 'content-type': 'application/json',

Note :sending text only push from dashboard works with no issue

**Comment by drew-gross** [comment]
The Parse Dashboard uses the Parse SDK to send pushes, so I think this issue belongs in the Parse-SDK-JS repo. Could you reopen it over there?
