### ISSUE TITLE
I wam't  to run the app with proper URL

### ISSUE THREAD

**Issue by usmanarif** [ParsePlatform/parse-dashboard#234]
I have installed and configured the application successfully. Now I want to run this app with proper url i.e. "parse.mtlfreetv.com". Since there is no config file present, I am a bit confused as what and where I have to change the setting?

**Comment by r2DoesInc** [comment]
This isnt done on via the parse dashboard, you need to configure it via your web server. 

My setup uses apache virtual hosts and proxypass. Here is a basic example.

```
<VirtualHost *:80>
  ServerName parse. mtlfreetv.com
  ProxyPass               /       http://localhost:4040/
  ProxyPassReverse        /       http://localhost:4040/
  ErrorLog /var/log/apache2/parse/dash-error.log
  CustomLog /var/log/apache2/parse/dash-access.log combined
</VirtualHost>
```

**Comment by drew-gross** [comment]
Thanks for the help @r2DoesInc!

**Comment by usmanarif** [comment]
@r2DoesInc thanks for the help, I will do the required setup in my web.
