### ISSUE TITLE
Dashboard cannot use a mount path that is a prefix of '/parse-dashboard-config.json'

### ISSUE THREAD

**Issue by mamaso** [ParsePlatform/parse-dashboard#235]
https://github.com/ParsePlatform/parse-dashboard/pull/217/files#diff-8191c30dbcedec21adc7973ea995cdf5R25

This line will match the routes /parse, /parse-dashboard, /parse-dashboard-config, etc and fail to add the mount path to that request.

A bit more context:

1. run dashboard at localhost:4040/parse
2. dashboard makes GET /parse-dashboard-config.json request
3. above line matches /parse mount path to /parse in /parse-dashboard-config.json
4. request is made to localhost:4040/parse-dashboard-config.json instead of the correct localhost:4040/parse/parse-dashboard-config.json

Potential fix:

Instead of 
```js
!url.startsWith(basePath)) {
```

use

```js
!url.startsWith(basePath + '/')
```

**Comment by mamaso** [comment]
Potential fix:

Instead of 
```js
!url.startsWith(basePath)) {
```

use

```js
!url.startsWith(basePath + '/')
```

**Comment by hpello** [comment]
:+1:  I got the same problem.

In other words, the current version forbids one to set a mount path that is a prefix of '/parse-dashboard-config.json'
e.g. '/parse', or '/parse-dashboard'
