### ISSUE TITLE
Parse Dashboard Error

### ISSUE THREAD

**Issue by faizsameerahmed96** [ParsePlatform/parse-dashboard#239]
I have not found this issue anywhere. I am on the latest version of parse dashboard. This happens in the "create an audience" tab. When I click on add condition nothing happens. DId anyone else experience this?

**Comment by drew-gross** [comment]
I don't have this issue. Can you check the JS Console for errors or warnings?

**Comment by jeremyjackson89** [comment]
This happens to me as well. The console produces this error:

`dashboard.bundle.js:26 Uncaught TypeError: Cannot read property '0' of undefined`

Looking at the bundle and prettifying it, it looks to be happening here with the `e[t][0]`:

```
{
    key: "handleAddCondition",
    value: function() {
        var e = f.availableFilters(this.props.schema, this.state.filters),
            t = l(e)[0];
        this.setState(function(n) {
            var r = n.filters;
            return {
                filters: r.push(new J.Map({
                    field: t,
                    constraint: e[t][0]
                }))
            }
        }, this.fetchAudienceSize.bind(this))
    }
}
```

**Comment by quincycs** [comment]
Was this fixed?  I have this issue with latest from npm.

**Comment by nkranes** [comment]
+1

**Comment by codenpk** [comment]
even I am facing this issue :(

**Comment by hchu0701** [comment]
It seems like this error was occurred when your database don't have "Installation" class

**Comment by rootux** [comment]
For us, We were missing `SERVER_URL` as an ENV variable.
Also make sure you have `MASTER_KEY` and `APP_ID`

**Comment by paoloar77** [comment]
I have the same issue.
I've just installed parse-server.
How is possible to resolve?

Thanks

**Comment by paoloar77** [comment]
Ok, resolved !
Click on "Create a Class" button, and select "Installation" and Continue.
