### ISSUE TITLE
pm2 ecosystem.json parse-dashboard

### ISSUE THREAD

**Issue by dudunato** [ParsePlatform/parse-dashboard#245]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ x] You're running version >=2.1.4 of Parse Server.

- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Ubuntu DigitalOcean

#### Steps to reproduce
I have this configuration file that I'm running with pm2:
```
{
  "apps": [{
      "name": "parse-dash",
      "script": "/usr/bin/parse-dashboard",
      "watch": true,
      "merge_logs" : true,
      "cwd": "/home/parsedash",
      "args": "--appId appId --masterKey marterKey --serverURL 'https://myparseapi.com/parse'"
  }]
}
```

And i'm getting 'You must provide either a config file or required CLI options (app ID, Master Key, and server URL); not both.' error when I start my parse-dashboard. Am I missing something?

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by sysadminPSQ** [comment]
This worked for me. 

```json
{
  "apps" : [{
    "name"        : "parse-dash",
    "script"      : "/usr/bin/parse-dashboard",
    "watch"       : true,
    "merge_logs"  : true,
    "cwd"         : "/home/parse",
    "args"         : "--config parse-dashboard-config.json"
  }]
}
```

**Comment by drew-gross** [comment]
This is likely an issue with your environment variables. Try @sysadminPSQ's suggestion of using a config file instead of command line flags.
