### ISSUE TITLE
Parse-dashboard at Azure has no App-Settings

### ISSUE THREAD

**Issue by jamesytl** [ParsePlatform/parse-dashboard#246]
I have deployed a Parse server thought this [link](https://azure.microsoft.com/en-us/blog/announcing-the-publication-of-parse-server-with-azure-managed-services/)'s tutorial and had successfully tested the connection by adding new user. Now I want to enable email verification setting but I found that my parse dashboard has only core tab instead of all other tabs like Push, Analytics and most importantly App-Setting which is the setting for email verification and others.

An Image is included below 
![parsedashboard](https://cloud.githubusercontent.com/assets/17899653/14433408/d623310c-0040-11e6-930c-89c08b480c6a.png)

**Comment by drew-gross** [comment]
Currently you need to enable Email Verification through Parse Server. There is some discussion of enabling settings in the dashboard in https://github.com/ParsePlatform/parse-server/pull/1418 which you can follow. Also, by configuring push and updating your Parse Server you can get the Config page.
