### ISSUE TITLE
Parse Dashboard version displayed somewhere?

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-dashboard#247]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x ] You're running version >=2.1.4 of Parse Server.

- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
xxx

#### Steps to reproduce
Simple Suggestion.. Can we in the main parse dashboard or maybe on the left sidebar list the parse dashboard version.. or an about link .. ? thoughts?

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
Good idea! It could probably be displayed in the top left where "PARSE DASHBOARD" is displayed. Want to submit a PR?

**Comment by gateway** [comment]
Is the version stored somewhere by chance?

**Comment by drew-gross** [comment]
You can `require` it from `package.json`.

**Comment by gateway** [comment]
Yea, I found a few ways, however since this isnt my project I'm not sure the best course of action, and some just done work unless I parse the json etc.  Their is a package info module but I do not also want to add another package.. thoughts?

http://stackoverflow.com/questions/9153571/is-there-a-way-to-get-version-from-package-json-in-nodejs-code

**Comment by drew-gross** [comment]
Just require the json file directly, like the answer to that question suggests. We do this in Parse Server, thats how the server reports it's own version to the dashboard: https://github.com/ParsePlatform/parse-server/blob/616ac71623953b11e6fdc480b1136d8c040ccc2d/spec/index.spec.js#L
