### ISSUE TITLE
Username, password and Email is not showing on the dashboard (some exceptions)

### ISSUE THREAD

**Issue by faizsameerahmed96** [ParsePlatform/parse-dashboard#249]
I am experiencing a weird bug. On my parse dashboard when I enter the User table (generated from android app) I am not able to see the 'default' fields like username, password, email, emailVerified. The strange thing is that when I delete some random column these columns suddenly appear! The are again invisible after I reload this page.

Can someone please help. I am not experienced with parse-server / parse-dashboard development so if you need more info please tell me what steps I should follow to help you.

**Comment by drew-gross** [comment]
I think we've already fixed this issue in Parse Server, but the version with the fix isn't on `npm` yet. In the meantime, you could try upgrading your Parse Server to use the latest `master`, or you could edit your `_SCHEMA` collection in your database manually to include those columns, or you can just wait until we release the next version of Parse Server :)

**Comment by faizsameerahmed96** [comment]
Thanks!

**Comment by Jerland2** [comment]
@drew-gross I am having an issue where NONE of my "User" class is being displayed on the dashboard.  Is this a new bug, or is this related? If this is the same bug I am happy to wait for thew new version on npm, or perhaps you know the solution?

When i click on the "user" Class there is no data and no option to add data. Thanks

**Comment by drew-gross** [comment]
I suspect this is the same issue. Check the response to the `schemas` endpoint in the API Console, if the `"_Users"` class has no fields, then this is the same issue.

**Comment by Jerland2** [comment]
I have figured out the problem, similar to another issue that i posted about.  If there are arrays stored in Parse in the "_User" class this causes the errors.  I have removed the arrays and now the ""User" populates with data.
