### ISSUE TITLE
Running parse-dashboard at Heroku?

### ISSUE THREAD

**Issue by onosol** [ParsePlatform/parse-dashboard#250]
Is there an example of running parse-dashboard at Heroku like the parse-server-example GitHub project?

**Comment by grassland-curing-cfa** [comment]
A working example would be really helpful!

**Comment by mattgoldspink** [comment]
I just set this up - it's very straight forward. I'm assuming you already have a Heroku account. Run the following:

$ mkdir my-parse-dashboard
$ cd my-parse-dashboard
$ git init
$ npm init
$ npm install --save parse-dashboard

For npm init just enter anything that makes sense. Now you'll need to create 2 files:

1) parse-dashboard-config.json - this should follow the pattern listed here: https://github.com/ParsePlatform/parse-dashboard
2) Procfile - The contents of this should be one line:

web: ./node_modules/.bin/parse-dashboard --config ./parse-dashboard-config.json --allowInsecureHTTP

Now you need to commit all this to git:

$ git add package.json Procfile parse-dashboard-config.json
$ git commit -m "My First Commit"

Now install the Heroku toolbelt if you haven't already: https://toolbelt.heroku.com/
Then run:

$ heroku login
$ heroku create
$ git push heroku master
$ heroku ps:scale web=1
$ heroku open

That should be it

**Comment by onosol** [comment]
mattgoldspink, This is great, thanks! The procfile was the missing piece for me. I will try this out today.

**Comment by drew-gross** [comment]
Thanks for the help @mattgoldspink! Do you think you might be able to add some formatting and open a PR adding those instructions to the readme? They look really useful.

**Comment by onosol** [comment]
@mattgoldspink, Just tested and this worked perfectly! Thanks again.

**Comment by natanrolnik** [comment]
Thank you, @mattgoldspink . That helped me!

**Comment by gateway** [comment]
Hmm, question, is ir procfile and what folder does this go into?

**Comment by cherukumilli** [comment]
# parse-dashboard-example
If anyone is interested then please check out and give me feedback about my **parse-dashboard-example** project. It is similar to the **parse-server-example**.

Please check it out at: `https://github.com/cherukumilli/parse-dashboard-example`

**Comment by gateway** [comment]
@cherukumilli thanks for doing this, its much appreciated! Ill give it a test because most of my stuff will probably be in AWS.

**Comment by natanrolnik** [comment]
@gateway as it's not intended to run for production to users, you could easily deploy to heroku in their free dyno

**Comment by Somkid2555** [comment]
http://android-kill-the-what.blogspot.com/2016/05/heroku-deploy-parse-dashboard-step.html

**Comment by grassland-curing-cfa** [comment]
**@natanrolnik** 
Can you point a working example of deploying the Dashboard to Heroku in their free dyno please? Thanks!

**Comment by nabil-takla** [comment]
I get fatal: pathspec 'package.json' did not match any files
