### ISSUE TITLE
Server not reachable: unable to connect to server

### ISSUE THREAD

**Issue by Faisal-nfl** [ParsePlatform/parse-dashboard#252]
I manually created a mongDB and deployed this [parse server example](https://github.com/ParsePlatform/parse-server-example) to heroku
now I want use Parse dashboard for this using 
parse-dashboard --appId yourAppId --masterKey yourMasterKey --serverURL "https://example.com/parse" --appName optionalName
but I don't know where to get appId, masterKey and appName after running this with default appId, masterKey and appName but actual serverURL its runs dashboard but on dashboard page it says "Server not reachable: unable to connect to server" what is the problem

**Comment by drew-gross** [comment]
You need to use the correct app ID and master key that you initialized your Parse Server with.

**Comment by Faisal-nfl** [comment]
I 'm not sure that what was the actual issue
But I manually put appId, masterKey and ServerURL in index.json than push my parse server example again.
Now its working fine
