### ISSUE TITLE
"Server not reachable: server version too low" error

### ISSUE THREAD

**Issue by grassland-curing-cfa** [ParsePlatform/parse-dashboard#253]
I have successfully installed and run a parse-dashboard instance on my localhost. The parse-dashboard-config.json file was amended to enable multiple apps. All my Parse apps are deployed on Heroku using "Parse-server-example".

When I ran the dashboard on my localhost, it listed all my apps but some apps showed the following message:
"Server not reachable: server version too low"

But count of Users were correctly displayed. I was unable to go into those apps to see Core.

**Comment by drew-gross** [comment]
That means you need to upgrade your Parse Server version for those apps. Parse Server version 2.1.4 has the Schemas API, which is necessary for the data browser to function. It is still able to fetch the counts because those endpoints don't need the Schemas API.
