### ISSUE TITLE
Server not reachable: unauthorized

### ISSUE THREAD

**Issue by Faisal-nfl** [ParsePlatform/parse-dashboard#254]
I deployed parse server example to Heroku, now when I try to access it with parse dashborad it runs but say "Server not reachable: unauthorized"

**Comment by bohemima** [comment]
You probably misconfigured the keys when you set up the dashboard. Please double check

**Comment by Faisal-nfl** [comment]
I 'm not sure that what was the actual issue
But I manually put appId, masterKey and ServerURL in index.json than push my parse server example again.
Now its working fine
