### ISSUE TITLE
Parse-dashboard columns missing

### ISSUE THREAD

**Issue by kwstasna** [ParsePlatform/parse-dashboard#255]
- [x ] You're running version >=2.1.4 of Parse Server.

- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
**Environment Setup**

Ubuntu DigitalOcean

**Steps to reproduce**
i have created a _config.json_ file  and i run

## parse-dashboard --config config.json --allowInsecureHTTP=1

The config file is the following one

```
{
  "apps": [
    {
      "serverURL": "http://ip/parse",
      "appId": "id",
      "masterKey": "key",
      "appName": "name"
    }
  ],
 "users": [
    {
      "user":"kwstasna",
      "pass":"something"
    }
  ]
}

```

Hello i have installed parse-dashboard today and i have connected it with my iOS app that i develop now. So my app when is connected to the parse-server-example it makes the the right classes and collumns. When i sign up a user with email it signs up correctly BUT when i go to my parse-dashboard there are no columns such as "username" "email" "password" and some others.

So i logout from this user and i try to login via facebook (which was working great on the parse.com version)

and i get an error 
**Can't use nil for keys or values on PFObject. Use NSNull for values**

I guess this happens cause it cant find the above columns.
When i tried to add "username" column manually nothing happened. I refreshed and somehow all the missing columns appeared.
I tried then to login via facebook and everything worked grate.

Then i refreshed the dashboard and the columns dissappeared again.

P.S. (how can i check which parse-dashboard version i have? I 've installed it to Digital Ocean Ubuntu 14.04)

Also installation class doesn't have "badge" "devicetoken" "deviceType" "pushType" and many more.

I have the same issue even if i load the parse-dashboard from localhost.

**Comment by francesc-o** [comment]
Same issue for me: in Core -> Browser, Installation's columns don't appear all: channels, badge, devicetoken, deviceType and many more don't appear, even if they are stored correcly from app (after push notification registration process). If I try to add a column manually, then all columns appear; but when I exit and then re-open the dashboard, the situation is that the initial. 
The very important problem is that when in Browser screen columns not appear, if I try to send a push notification I can't segment the target, because missing columns parameters (for example, channels)  don't appear in Audience's conditions.

**Comment by kwstasna** [comment]
@francesc-o Yeap that's true, exactly what my problem is with Facebook Login. If there are no columns such as "email" "username" etc in dashboard i get the error. But when i try to add something manually the columns appear and then i can login with facebook without errors, until i restart the dashboard. 
I will have your problem also when i will use notifications then.
This has to be seen from the developers!

**Comment by drew-gross** [comment]
This was caused by some issues in Parse Server. Most of them have been fixed, so updating your Parse Server to the latest version might help. There are also a couple lingering issues so you might need to wait for the next version.

**Comment by kwstasna** [comment]
@drew-gross i have parse-server version 2.2.6

**Comment by drew-gross** [comment]
In that case you will need to wait for the next version, which should be out within a week.

**Comment by kwstasna** [comment]
@drew-gross  ok i will ! 
My regards to all of the team!
Greetings from Greece :)
