### ISSUE TITLE
Push Section is not showing in the dashboard

### ISSUE THREAD

**Issue by shehabix** [ParsePlatform/parse-dashboard#266]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=2.1.4 of Parse Server.
- [x] Dashboard version = 1.0.9
- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
I'm running a small Digital Ocean Droplet 
with the following config for parse server .. 
```json
{
	"databaseURI": "mongodb://{user}:{pass}@domain.com:27017/dbna,e?ssl=true",
	"cloud": "/home/parse/cloud/main.js",
	"appId": "bla-bla-bla",
	"masterKey": "bla-bla-bla",
	"javascriptKey": "bla-bla-bla",
	"restAPIKey": "bla-bla-bla",
	"clientKey": "bla-bla-bla",
	"serverURL": "http://my.domain.com:1337/parse",
	"port": "1337",
	"push": {
		"android": {
			"senderId": "123456789......",
			"apiKey": "SecretKey"
		}
	}
}
```
running it via 
```parse-server /path/to/config.json```

and running the dashboard with the following config:

```json
{
  "apps": [
    {
      "serverURL": "server/url/to/app",
      "appId": "bla-bla-bla",
      "masterKey": "bla-bla-bla",
      "javascriptKey": "bla-bla-bla",
      "clientKey" : "bla-bla-bla",
      "restKey": "bla-bla-bla",
      "appName": "Friendly App name",
      "production": true
    }
  ],
  "users": [
     {
       "user":"user@gmail.com",
       "pass":"password",
       "apps": [{"appId": "bla-bla-bla"}]
    }
  ]
}
```
running it via parse-dashboard --config dashboard.json

**Parse Push Section is not showing on the left at all, I only see "Core"**

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
Try upgrading your Parse Server version. If that doesn't work, show me the response to the `serverInfo` endpoint in your Parse Server.

**Comment by shehabix** [comment]
Here it is:
```json
{
  "features": {
    "globalConfig": {
      "create": true,
      "read": true,
      "update": true,
      "delete": true
    },
    "hooks": {
      "create": false,
      "read": false,
      "update": false,
      "delete": false
    },
    "logs": {
      "level": true,
      "size": true,
      "order": true,
      "until": true,
      "from": true
    },
    "push": {
      "immediatePush": true,
      "scheduledPush": false,
      "storedPushData": false,
      "pushAudiences": false
    },
    "schemas": {
      "addField": true,
      "removeField": true,
      "addClass": true,
      "removeClass": true,
      "clearAllDataFromClass": false,
      "exportClass": false,
      "editClassLevelPermissions": true
    }
  },
  "parseServerVersion": "2.2.7"
}```

**Comment by shehabic** [comment]
Just for the record this was the issue: 
    ``` "serverURL": "http://my.domain.com:1337/parse", ```
I was opening the dashboard via https, serverURL was wrong, and can't be http as well, so I proxied it via nginx, so have something like:  "https://d.my-domain.com/parse" proxying "http://localhost:1337/parse"

**Comment by shehabix** [comment]
Just for the record this was the issue: 
    ``` "serverURL": "http://my.domain.com:1337/parse", ```
I was opening the dashboard via https, serverURL was wrong, and can't be http as well, so I proxied it via nginx, so have something like:  "https://d.my-domain.com/parse" proxying "http://localhost:1337/parse"

**Comment by SavageGamesCo** [comment]
This is driving me insane. 

I installed bitnami Parse via AWS Marketplace

I connect to the dashboard and only see Core. 

I have been scouring the internet trying to find answers. 

I even tried installing the dashboard locally to connect to the AWS server and still only see Core. 

created a self signed cert in hopes that it would do something for my local instance of dashboard and still.. only Core. It makes no sense to be able to access core but no other features. Like Push...
