### ISSUE TITLE
Are REST/API specifications available?

### ISSUE THREAD

**Issue by kulshekhar** [ParsePlatform/parse-dashboard#267]
Is there some documentation/specification available for the calls being made from Parse dashboard to Parse server? I've been using the network monitor in the browser's dev tools but there's a chance of missing something (an endpoint or a data structure) using this method.

I'm currently working on an application that could potentially expose the data required by Parse dashboard to make the two work together. In general, the use of Parse dashboard could expand beyond Parse server if this specification existed.

**Comment by drew-gross** [comment]
The dashboard is implemented using the JS SDK. The JS SDK does use some undocumented features of Parse Server and api.parse.com to work, but in general the [Parse REST API docs](https://parse.com/docs/rest/guide) will be your best bet for figuring out the details of your project.

**Comment by kulshekhar** [comment]
The REST API docs would certainly be helpful for an app that mimics the functionality of Parse server. However, I imagine Parse dashboard would need additional 'metadata' for its functionality. It's the specification for this part that I am more interested in. 

For eg., using the network monitor, I found one of the calls was made to `/apps/app_name/collections/info` to fetch information about all the `collections` and their details. These details included fields like `count`, `display_name` and `client_permissions`.

**Comment by drew-gross** [comment]
Ah, you mean the dashboard at dashboard.parse.com. Yea, that uses some endpoints that aren't available in Parse Server. We don't have any documentation for those ones, no. If you want to try to figure it out by reading the source, `src/lib/ParseApp.js` is the file where most of those calls are made.

The collection info one though has been replaced by one that uses Parse Server endpoints.

**Comment by kulshekhar** [comment]
Thanks @drew-gross 

The `src/lib/ParseApp.js` does seem like a good starting point for what I wanted
