### ISSUE TITLE
Display app icons

### ISSUE THREAD

**Issue by natanrolnik** [ParsePlatform/parse-dashboard#269]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

Currently, the dashboard doesn't show yet the app icons. Ideally, it would be very helpful to have the icons to better visualize each app, specially if you have a lot of them.

I think that we could add a `iconImage` or `icon` parameter to each app in the dashboard-config.json file, and use a placeholder if no icon (can we use the one that is currently shown in the Parse.com dashboard?). Any special recommendations for making a PR on this?

**Comment by drew-gross** [comment]
Good idea! The code that displays the icons is still there but there is no way to set an icon in this version of the dashboard. If you look at the `AppCard` and `AppsIndex` components you can see how it's displayed. Setting up the fetching and storage of the icons would be all new code.

**Comment by natanrolnik** [comment]
@drew-gross I managed to successfully show the "blank app outline" (like the current Parse.com dashboard) when no icon is set, and showing an app icon when the `src` is a remote image.
But I didn't add support yet for local files (adding to the same repo). How do you think this should be done? Where developers should put the image files when running parse-dashboard from terminal or when deploying to remote?

**Comment by drew-gross** [comment]
Looks good so far, my suggestion would be have an `iconsFolder` line in the config, and each app can have an `iconName` line that is the name of an icon within that folder. I'm open to other suggestions though.

**Comment by natanrolnik** [comment]
@drew-gross makes sense. The `iconsFolder` should be defined in the dashboard-config.json file?

**Comment by drew-gross** [comment]
yep.
