### ISSUE TITLE
'No data to display' although data is there

### ISSUE THREAD

**Issue by merowinger92** [ParsePlatform/parse-dashboard#270]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X] You're running version 2.2.6 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

Debian Wheezy 
Started with parse-dashboard --config /path/to/config --allowInsecureHTTP=1

#### Steps to reproduce

I defined a cloud function in parse server:
`Parse.Cloud.define("First", function(request,response){
    
    var User = new Parse.Object("User");

    User.set("name","Miautzekatze");
    
    User.save().then(function(result){
        console.log("success");
        response.success("saved");
    }, function(error){
        console.log("save failed!");
        response.error(error);
    });
    
});`

I can also call that function and I see "success" in console. Verifiying the data in MongoDB it's also there.
Browsing parse dashboard. the class is there but no data in it. If I try to delete the class I also get an appropriate error message that the class is not empty.

If furthere information is needed I try to provide it.

**Comment by bohemima** [comment]
Just a side note here, probably not related. But remember that "User" is not the Parse User Class, that class should be named "_User".

**Comment by drew-gross** [comment]
Can you fetch the object from the API Console or JS SDK? Parse Dashboard uses the JS SDK to fetch objects so if the SDKs work then the dashboard should work.

**Comment by merowinger92** [comment]
@drew-gross 
via REST API all information is correctly displayed...
I X-checked the config files but I don't see an error on my side...

**Comment by drew-gross** [comment]
Do you see any errors in the Javascript console? If your configuration is correct, there isn't much that could be going wrong here.

**Comment by drew-gross** [comment]
No response in many days, closing.

**Comment by aesnyder** [comment]
I'm seeing this behavior...

1. mongodump an existing working parse database

2. mongorestore that into a new database

3. point your parse app at that database

4. load the dashboard, nothing is there. 

Note: New records show up fine but old ones do not.

**Comment by thpthang10** [comment]
My case: Tap the Eye icon => Hide all => select some fields => refresh. The data back, and remember to delete the wrong instances you just created. Hope it help.
