### ISSUE TITLE
How can I visit dashboard remotely.

### ISSUE THREAD

**Issue by GongChen1107** [ParsePlatform/parse-dashboard#271]
I have a few questions about visiting dashboard remotely.I cloned a dashboard down and got a https certifications .The questions below:
1、what 's the name I should name the certification file.
2、Which path should I put the certification file.
3、Should I  map the 443 port to 4040 port.

**Comment by drew-gross** [comment]
Currently you have to do SSL termination before the dashboard. I didn't expect so many people to want to deploy the dashboard so it wasn't really designed for that. If you want to add SSL termination within the dashboard, that would be much appreciated :)
