### ISSUE TITLE
Fail to show database data (with browser js error)

### ISSUE THREAD

**Issue by ghalexxxx** [ParsePlatform/parse-dashboard#276]
There are several tables at the database, and only one of them doesn't display any data with following js error:

> BrowserCell.react.js?124e:43 Uncaught TypeError: value.map is not a function
> 
> BrowserCell	@	BrowserCell.react.js?124e:43
> ReactCompositeComponentMixin.mountComponent	@	ReactCompositeComponent.js?47a9:148
> ReactCompositeComponent_mountComponent	@	ReactPerf.js?6da6:66
> ReactReconciler.mountComponent	@	ReactReconciler.js?9da7:37
> ReactMultiChild.Mixin.mountChildren	@	ReactMultiChild.js?87d2:241
> ReactDOMComponent.Mixin._createContentMarkup	@	ReactDOMComponent.js?f4f2:591
> ReactDOMComponent.Mixin.mountComponent	@	ReactDOMComponent.js?f4f2:479
> ReactReconciler.mountComponent	@	ReactReconciler.js?9da7:37
> ReactMultiChild.Mixin._mountChildByNameAtIndex	@	ReactMultiChild.js?87d2:474
> ReactMultiChild.Mixin._updateChildren	@	ReactMultiChild.js?87d2:378
> ReactMultiChild.Mixin.updateChildren	@	ReactMultiChild.js?87d2:326
> ReactDOMComponent.Mixin._updateDOMChildren	@	ReactDOMComponent.js?f4f2:871
> ReactDOMComponent.Mixin.updateComponent	@	ReactDOMComponent.js?f4f2:700
> ReactDOMComponent.Mixin.receiveComponent	@	ReactDOMComponent.js?f4f2:645
> ReactReconciler.receiveComponent	@	ReactReconciler.js?9da7:87
> ReactChildReconciler.updateChildren	@	ReactChildReconciler.js?660f:84
> ReactMultiChild.Mixin._reconcilerUpdateChildren	@	ReactMultiChild.js?87d2:216
> ReactMultiChild.Mixin._updateChildren	@	ReactMultiChild.js?87d2:351
> ReactMultiChild.Mixin.updateChildren	@	ReactMultiChild.js?87d2:326
> ReactDOMComponent.Mixin._updateDOMChildren	@	ReactDOMComponent.js?f4f2:871
> ReactDOMComponent.Mixin.updateComponent	@	ReactDOMComponent.js?f4f2:700
> ReactDOMComponent.Mixin.receiveComponent	@	ReactDOMComponent.js?f4f2:645
> ReactReconciler.receiveComponent	@	ReactReconciler.js?9da7:87
> ReactCompositeComponentMixin._updateRenderedComponent	@	ReactCompositeComponent.js?47a9:562
> ReactCompositeComponentMixin._performComponentUpdate	@	ReactCompositeComponent.js?47a9:544
> ReactCompositeComponentMixin.updateComponent	@	ReactCompositeComponent.js?47a9:473
> ReactCompositeComponent_updateComponent	@	ReactPerf.js?6da6:66
> ReactCompositeComponentMixin.receiveComponent	@	ReactCompositeComponent.js?47a9:405
> ReactReconciler.receiveComponent	@	ReactReconciler.js?9da7:87
> ReactChildReconciler.updateChildren	@	ReactChildReconciler.js?660f:84
> ReactMultiChild.Mixin._reconcilerUpdateChildren	@	ReactMultiChild.js?87d2:216
> ReactMultiChild.Mixin._updateChildren	@	ReactMultiChild.js?87d2:351
> ReactMultiChild.Mixin.updateChildren	@	ReactMultiChild.js?87d2:326
> ReactDOMComponent.Mixin._updateDOMChildren	@	ReactDOMComponent.js?f4f2:871
> ReactDOMComponent.Mixin.updateComponent	@	ReactDOMComponent.js?f4f2:700
> ReactDOMComponent.Mixin.receiveComponent	@	ReactDOMComponent.js?f4f2:645
> ReactReconciler.receiveComponent	@	ReactReconciler.js?9da7:87
> ReactCompositeComponentMixin._updateRenderedComponent	@	ReactCompositeComponent.js?47a9:562
> ReactCompositeComponentMixin._performComponentUpdate	@	ReactCompositeComponent.js?47a9:544
> ReactCompositeComponentMixin.updateComponent	@	ReactCompositeComponent.js?47a9:473
> ReactCompositeComponent_updateComponent	@	ReactPerf.js?6da6:66
> ReactCompositeComponentMixin.receiveComponent	@	ReactCompositeComponent.js?47a9:405
> ReactReconciler.receiveComponent	@	ReactReconciler.js?9da7:87
> ReactChildReconciler.updateChildren	@	ReactChildReconciler.js?660f:84
> ReactMultiChild.Mixin._reconcilerUpdateChildren	@	ReactMultiChild.js?87d2:216
> ReactMultiChild.Mixin._updateChildren	@	ReactMultiChild.js?87d2:351
> ReactMultiChild.Mixin.updateChildren	@	ReactMultiChild.js?87d2:326
> ReactDOMComponent.Mixin._updateDOMChildren	@	ReactDOMComponent.js?f4f2:871
> ReactDOMComponent.Mixin.updateComponent	@	ReactDOMComponent.js?f4f2:700
> ReactDOMComponent.Mixin.receiveComponent	@	ReactDOMComponent.js?f4f2:645
> ReactReconciler.receiveComponent	@	ReactReconciler.js?9da7:87
> ReactChildReconciler.updateChildren	@	ReactChildReconciler.js?660f:84
> ReactMultiChild.Mixin._reconcilerUpdateChildren	@	ReactMultiChild.js?87d2:216
> ReactMultiChild.Mixin._updateChildren	@	ReactMultiChild.js?87d2:351
> ReactMultiChild.Mixin.updateChildren	@	ReactMultiChild.js?87d2:326
> ReactDOMComponent.Mixin._updateDOMChildren	@	ReactDOMComponent.js?f4f2:871
> ReactDOMComponent.Mixin.updateComponent	@	ReactDOMComponent.js?f4f2:700
> ReactDOMComponent.Mixin.receiveComponent	@	ReactDOMComponent.js?f4f2:645
> ReactReconciler.receiveComponent	@	ReactReconciler.js?9da7:87
> ReactChildReconciler.updateChildren	@	ReactChildReconciler.js?660f:84
> ReactMultiChild.Mixin._reconcilerUpdateChildren	@	ReactMultiChild.js?87d2:216
> ReactMultiChild.Mixin._updateChildren	@	ReactMultiChild.js?87d2:351
> ReactMultiChild.Mixin.updateChildren	@	ReactMultiChild.js?87d2:326
> ReactDOMComponent.Mixin._updateDOMChildren	@	ReactDOMComponent.js?f4f2:871
> ReactDOMComponent.Mixin.updateComponent	@	ReactDOMComponent.js?f4f2:700
> ReactDOMComponent.Mixin.receiveComponent	@	ReactDOMComponent.js?f4f2:645
> ReactReconciler.receiveComponent	@	ReactReconciler.js?9da7:87
> ReactCompositeComponentMixin._updateRenderedComponent	@	ReactCompositeComponent.js?47a9:562
> ReactCompositeComponentMixin._performComponentUpdate	@	ReactCompositeComponent.js?47a9:544
> ReactCompositeComponentMixin.updateComponent	@	ReactCompositeComponent.js?47a9:473
> ReactCompositeComponent_updateComponent	@	ReactPerf.js?6da6:66
> ReactCompositeComponentMixin.performUpdateIfNecessary	@	ReactCompositeComponent.js?47a9:421
> ReactReconciler.performUpdateIfNecessary	@	ReactReconciler.js?9da7:102
> runBatchedUpdates	@	ReactUpdates.js?6ba9:129
> Mixin.perform	@	Transaction.js?d39c:136
> Mixin.perform	@	Transaction.js?d39c:136
> assign.perform	@	ReactUpdates.js?6ba9:86
> flushBatchedUpdates	@	ReactUpdates.js?6ba9:147
> ReactUpdates_flushBatchedUpdates	@	ReactPerf.js?6da6:66
> Mixin.closeAll	@	Transaction.js?d39c:202
> Mixin.perform	@	Transaction.js?d39c:149
> ReactDefaultBatchingStrategy.batchedUpdates	@	ReactDefaultBatchingStrategy.js?c98c:62
> enqueueUpdate	@	ReactUpdates.js?6ba9:176
> enqueueUpdate	@	ReactUpdateQueue.js?9ce0:24
> ReactUpdateQueue.enqueueSetState	@	ReactUpdateQueue.js?9ce0:190
> ReactComponent.setState	@	ReactComponent.js?2434:65
> (anonymous function)	@	Browser.react.js?40f3:272
> wrappedResolvedCallback	@	ParsePromise.js?42cc:135
> resolve	@	ParsePromise.js?42cc:68
> (anonymous function)	@	ParsePromise.js?42cc:140
> wrappedResolvedCallback	@	ParsePromise.js?42cc:135
> (anonymous function)	@	ParsePromise.js?42cc:196
> runLater	@	ParsePromise.js?42cc:180
> then	@	ParsePromise.js?42cc:195
> wrappedResolvedCallback	@	ParsePromise.js?42cc:139
> resolve	@	ParsePromise.js?42cc:68
> wrappedResolvedCallback	@	ParsePromise.js?42cc:145
> resolve	@	ParsePromise.js?42cc:68
> wrappedResolvedCallback	@	ParsePromise.js?42cc:145
> resolve	@	ParsePromise.js?42cc:68
> (anonymous function)	@	ParsePromise.js?42cc:140
> wrappedResolvedCallback	@	ParsePromise.js?42cc:135
> resolve	@	ParsePromise.js?42cc:68
> xhr.onreadystatechange	@	RESTController.js?9d61:106

**Comment by drew-gross** [comment]
Can you try running the development version of the browser (install from source and `npm run dev`)? That way I can see the non-compiled sources.

**Comment by ghalexxxx** [comment]
Yes, done and updated the original message

**Comment by drew-gross** [comment]
The most likely cause seems to be that you have non-array data in an array column. Can you check your database to make sure you don't have invalid data in there?

**Comment by ghalexxxx** [comment]
Right, I found out that one of the supposed-to-be array data is input as {}. After changing it to [] it is ok now.

**Comment by drew-gross** [comment]
Thanks. If you discover how that data got there and think it might be a bug in Parse Server, please let us know.
