### ISSUE TITLE
Is it possible to block creating of new tables or modifying tables?

### ISSUE THREAD

**Issue by adampietrasiak** [ParsePlatform/parse-dashboard#279]
At development stage, it's good to have tables/columns auto-created when request that have them happens, but at some point I would like to disable it for data consistency and to be spam-proof by not letting any user create hundreds of tables.

Is it possible in dashboard to toggle this?

**Comment by drew-gross** [comment]
Yep just disable `addField` permission on each table and set `allowClientClassCreation` to false in your server config.
