### ISSUE TITLE
How to deploy parse dashboard in the cloud?

### ISSUE THREAD

**Issue by Jinoooo** [ParsePlatform/parse-dashboard#280]
It would be great if we can have a template like parse-server-example to deploy parse dashboard in the cloud, i.e. AWS. with min. code + .ebextensions/app.config

**Comment by drew-gross** [comment]
What we actually discovered with the templates is that once someone deployed, they didn't know how to upgrade. I'd be open to adding something like that, but only if the upgrade path is also clear.

**Comment by cherukumilli** [comment]
@Jinoooo 
I created a `parse-dashboard-example` based on `parse-server-example`. Can you please check it out at: https://github.com/cherukumilli/parse-dashboard-example and give me some feedback?

**Comment by Jinoooo** [comment]
Wonderful.  Will try it out tomorrow and provide feedbacks!

**Comment by cleever** [comment]
You should consider using docker.

This repo have almost all features of parse (server/dashboard/db/cloud) pre-configured.

https://github.com/yongjhih/docker-parse-server

**Comment by Jinoooo** [comment]
Checked docker docs, and it seems very promising.  Guess I have to configure and test it first again!
