### ISSUE TITLE
unable to see logs after upgrading dashboard to 1.0.9

### ISSUE THREAD

**Issue by AvnerHilu** [ParsePlatform/parse-dashboard#281]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [V] You're running version >=2.1.4 of Parse Server.

- [V] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Ubuntu server 
parse server 2.2.7

#### Logs/Trace

Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

After upgrading the dashboard to the latest 1.0.9
when trying to access to the logs (from dashboard) I get the following message:

No logs in the last 30 days
When you start using Cloud Code, your logs will show up here.

thought there should be logs available . 

Thx,
Avner

**Comment by drew-gross** [comment]
Is this for parse.com or Parse Server? Also, can you check to see if anything was actually logged by your Parse Server? Logging in Parse Server is handled differently than parse.com, right now you pretty much need to enable verbose mode to see any logs.

**Comment by AvnerHilu** [comment]
Hi, 
I have enabled parse-server 2.2.7 with environment variable VERBOSE=1
and now i can see the logs from the installed dashboard.
Though is this configuration suitable for production server?
Instead of configuring the VERBOSE in an environment variable can i configure it in code? maybe in Parse.initialize?
thx,
Avner

**Comment by drew-gross** [comment]
Yes, you can use the "verbose" option in your parse server configuration. As for running in production, that will depend on your server load and exact use case. Logs will rotate daily by default so if your app isn't massive then running in production should be fine.
