### ISSUE TITLE
problem with json push

### ISSUE THREAD

**Issue by mustafauysal** [ParsePlatform/parse-dashboard#283]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
```
Ubuntu 14.04
node v5.10.1
npm 3.8.3
mongod 3.0.11
parse-server 2.2.7
parse-dashboard 1.0.9
```
#### Steps to reproduce
I can't send json messages via parse dashboard. I've checked http response and it seems `{result: true}` but can't push message anyway. (no problem with text messages)

I didn't get any error with curl and json messages delivering smoothly. 

Thanks,

**Comment by drew-gross** [comment]
The Dashboard just uses the JS SDK to send pushes, so this issue is probably a Parse Server issue. Can you open an issue on that repo that includes some logs from when you attempt to send a push?
