### ISSUE TITLE
Confusing label at home page

### ISSUE THREAD

**Issue by auching** [ParsePlatform/parse-dashboard#286]
Hi, I have migrated to parse server and in production already, my parse version is 2.2.6, however, in the 'At a glance' section on dashboard homepage, there's a "DEV" label on it, which is unchangeable and unclickable, what is it indicating and how to configure that?  Thanks.

**Comment by bohemima** [comment]
In your dashboard configuration file, add `"production": true`

```
        "apps": [{
                "serverURL": "http://localhost:1337/",
                "appId": "---",
                "masterKey": "---",
                "appName": "NameOfAwesomeApp",
                "production": true
        }]

```

**Comment by drew-gross** [comment]
Thanks @bohemima. I'll update the docs as well.
