### ISSUE TITLE
404 domain.com/parse/releases/latest

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-dashboard#295]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [x ] You're running version >=2.1.4 of Parse Server.
- [ x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Environment Setup

Heroku setup
#### Steps to reproduce

Generate some log data, go to your dashboard, open up your web console and click on logs info or error
![image](https://cloud.githubusercontent.com/assets/519563/14753505/aaffbfe8-088a-11e6-8c4b-eba77fe7a6c3.png)
#### Logs/Trace

Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
This is leftover code from when this endpoints actually existed on Parse.com. It would be moderately useful to remove them, or possibly repurpose them in Parse Server, though I'm not sure what they could be used for.

**Comment by yomybaby** [comment]
I have a same problem. Is there any news?

**Comment by NatanRolnik** [comment]
I removed those calls on #660. Hopefully it will be merged soon and released.
