### ISSUE TITLE
Suddenly all of my registered devices are missing, with no cause.

### ISSUE THREAD

**Issue by davidvanbeveren** [ParsePlatform/parse-dashboard#296]
Hi folks,

Logged into my Parse account to send a Push and find out I have no registered devices. I haven't updated my iOS app in over 6 months and have done nothing that would trigger me losing all of my registered devices. They are simply gone. Switched back using the new and old interface, no differences, I had around 445 registered devices. Could anyone offer me assistance?

Many thanks. :-)

**Comment by bohemima** [comment]
Is this really related to parse-dashboard or is this something that happened at parse.com?

You should probably try the Facebook bug tool instead.

**Comment by davidvanbeveren** [comment]
Hi Henrik!

I thought that my parse.com panel *was* the Dashboard, I didn't realize
Parse had a standalone product.

Would the Facebook bug tool be able to connect to my Parse.com account and
find the issue? The reason I ask is because I haven't touched my iOS App on
the store or the source code, so I can't possibly imagine why the issue
would occur on my end (but who knows, right?). Appreciate the help!

On Mon, Apr 25, 2016 at 7:57 AM, Henrik <notifications@github.com> wrote:

> Is this really related to parse-dashboard or is this something that
> happened at parse.com?
>
> You should probably try the Facebook bug tool instead.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ParsePlatform/parse-dashboard/issues/296#issuecomment-214147800>
>



-- 
-d.

**Comment by drew-gross** [comment]
Yes, the Facebook bug tool is the way to go. Check out [parse.com/help]()

**Comment by davidvanbeveren** [comment]
Hi Drew!

Sorry - I'm totally trying not to take up your guy's time, but I couldn't
find it.

I looked for "Facebook Bug Tool" in the /help page, and I googled it too,
with no luck.

Apologies again! Is there a direct link to this scanning tool?

On Mon, Apr 25, 2016 at 6:59 PM, Drew <notifications@github.com> wrote:

> Yes, the Facebook bug tool is the way to go. Check out parse.com/help
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ParsePlatform/parse-dashboard/issues/296#issuecomment-214441548>
>



-- 
-d.

**Comment by drew-gross** [comment]
Click the "Contact us" link

**Comment by davidvanbeveren** [comment]
Found it - thanks, you rock!

On Mon, Apr 25, 2016 at 8:58 PM, Drew <notifications@github.com> wrote:

> Click the "Contact us" link
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ParsePlatform/parse-dashboard/issues/296#issuecomment-214479645>
>



-- 
-d.
