### ISSUE TITLE
Question: Is there a way to delete a Config value through dashboard?

### ISSUE THREAD

**Issue by macdonaldj** [ParsePlatform/parse-dashboard#304]
On parse.com there was a way to delete the variable name. Is there a way to do this currently?

PARSE DASHBOARD 1.0.9

**Comment by drew-gross** [comment]
Yep just click the trash icon next to the config item.

**Comment by macdonaldj** [comment]
ok, no trash icon on the nodechef version of the parse dashboard of the config settings. I'll contact them about it
