### ISSUE TITLE
Server version too low but running latest parse

### ISSUE THREAD

**Issue by notanark** [ParsePlatform/parse-dashboard#305]
Server not reachable: server version too low ... but I'm running the latest version of parse-server.

**Comment by drew-gross** [comment]
This issue also might show up if you using the wrong mount path in your config. Can you check that?

**Comment by notanark** [comment]
sure

**Comment by notanark** [comment]
It's the same as I type into my browser. That's the correct one, right?

**Comment by drew-gross** [comment]
No, you use the mount path from your Parse Server, not your dashboard.

**Comment by notanark** [comment]
I was confusing serverurl with mount. I don't see a mount option on the github .

**Comment by notanark** [comment]
my serverurl is correct.

**Comment by notanark** [comment]
ok I tested this, and it's still there. Same error.

**Comment by notanark** [comment]
I'm mounting with express and using https, can you possibly spot an error here


`

var app = express();

// Serve the Parse API on the /parse URL prefix
var mountPath = '/Parse';
app.use(mountPath, api);
app.use(express.static('public'));
// Parse Server plays nicely with the rest of your web routes
app.get('/', function(req, res) {
  res.status(200).send('I dream of being a web site.');
});


https.createServer(ssl, app)
 .listen(port, function() {
    console.log('Server running on port ' + port + '.');
});

`

**Comment by notanark** [comment]
if you mean the mountPath : '/Parse', it is set in the app.

**Comment by notanark** [comment]
The dashboard picks upt he users and installs.. can't be mouth

**Comment by drew-gross** [comment]
Do you have the Parse SDK working? Use the same server URL in your dashboard that you use when initializing your Parse SDK.

**Comment by notanark** [comment]
The parse sdk is working.

It picks up my installs and users. However, it still says version too low.

**Comment by notanark** [comment]
Maybe it's related to the bug with the jssdki I'm having

**Comment by drew-gross** [comment]
This issue is a little old now, so I'm going to close it. We have a lot of people using the dashboard successfully, so I think this must be a configuration issue on your end.

**Comment by deada92** [comment]
I had exactly the same issue. I just forget to add my protocol (https) to my domain in the config file. Maybe you forget that, too^^

**Comment by noder199** [comment]
Faced same problem, it was due to an extra '/' in the serverURL.
