### ISSUE TITLE
Parse dashboard option ?

### ISSUE THREAD

**Issue by thamer898** [ParsePlatform/parse-dashboard#310]
Hello

how to allow this option in my dashboard https://parse.com/docs/android/guide#security
how to allow  App Permissions ?

Regards

**Comment by drew-gross** [comment]
For CLPs, make sure you are on the latest version of the dashboard. For pointer permissions, you'll need to wait, as they aren't in Parse Dashboard yet.

**Comment by jasonhoch** [comment]
Does Parse Dashboard v1.0.10 support Parse Server v2.2.8 for Pointer Permission? 
I could not find it at CLP.

**Comment by drew-gross** [comment]
No, it doesn't. 1.0.11 doesn't either. I will make an issue for that.
