### ISSUE TITLE
Unset property freezes dashboard

### ISSUE THREAD

**Issue by AmbroiseCollon** [ParsePlatform/parse-dashboard#311]
In parse dashboard, let's say you have a column named `points`. In one line, the property is set to 2. If you erase it, the property is set to `undefined`. This works fine.

The only problem is that these steps make the dashboard freezes. You cannot update any other property in any line/column of the class.

**Comment by drew-gross** [comment]
Are you seeing any errors in the JS console?

**Comment by drew-gross** [comment]
I'm unable to reproduce this issue.

**Comment by AmbroiseCollon** [comment]
Apparently the issue concerns only Number columns.

Here is the error :  
```
Invariant Violation: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `BrowserCell`.
invariantdashboard.bundle.js:17761
traverseAllChildrenImpldashboard.bundle.js:30239
traverseAllChildrendashboard.bundle.js:30267
flattenChildrendashboard.bundle.js:31263
_reconcilerUpdateChildrendashboard.bundle.js:30801
_updateChildrendashboard.bundle.js:30940
updateChildrendashboard.bundle.js:30915
_updateDOMChildrendashboard.bundle.js:28285
updateComponentdashboard.bundle.js:28114
receiveComponentdashboard.bundle.js:28059
receiveComponentdashboard.bundle.js:22314
_updateRenderedComponentdashboard.bundle.js:24296
_performComponentUpdatedashboard.bundle.js:24278
updateComponentdashboard.bundle.js:24207
ReactCompositeComponent_updateComponentdashboard.bundle.js:18072
receiveComponentdashboard.bundle.js:24139
receiveComponentdashboard.bundle.js:22314
updateChildrendashboard.bundle.js:31175
_reconcilerUpdateChildrendashboard.bundle.js:30805
_updateChildrendashboard.bundle.js:30940
updateChildrendashboard.bundle.js:30915
```

**Comment by drew-gross** [comment]
I still haven't been able to reproduce this issue, even with numbers. What browser are you using? Would you have able to set a breakpoint in the debugger and poke around to see if you see anything odd looking?

**Comment by AmbroiseCollon** [comment]
I'm using Safari

**Comment by drew-gross** [comment]
I can't reproduce in Safari 9.1. Can you make sure your browser and dashboard are up to date and see if you still get the issue in other browsers?

**Comment by drew-gross** [comment]
No response in many days, closing.

**Comment by AmbroiseCollon** [comment]
Sorry for the late response. It seems that the problem is fixed with latest Safari...
