### ISSUE TITLE
500 Error after clicking on "Send a Push" from the Parse Dashboard

### ISSUE THREAD

**Issue by sagar2305** [ParsePlatform/parse-dashboard#316]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=2.1.4 of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Steps to reproduce
Open parse.com
Click on App on the Dashboard
Click on Push
Click on Send a Push
A 500 error is shown

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
For issues with the Parse.com please use [parse.com/help](http://parse.com/help).
