### ISSUE TITLE
Impossible to send a push :  "no registered device" since few days (was working before)

### ISSUE THREAD

**Issue by aboucher00** [ParsePlatform/parse-dashboard#318]
-> running version >=1.11.0 of Parse Server.

#### Environment Setup
Hi all,

Since few days, I can't send push with PARSE and I don't know why (no modification on the app code)
Last week it was working but now, when I click on "send a push" button I have the message : "No registered device" 
![image](https://cloud.githubusercontent.com/assets/19185790/15011530/9ece32b0-11f2-11e6-87da-d394e69b6353.png)

When I enter in "CORE" section, I can  see data up to date.
Do you know what is happening ? Why I can't send a push ? 

Thanks a lot for your help.

**Comment by peterdotjs** [comment]
@aboucher00 are you still getting this issue?

**Comment by drew-gross** [comment]
For issues with the hosted Parse.com service, please use [parse.com/help](http://parse.com/help).
