### ISSUE TITLE
Issue on appName with apostrophe

### ISSUE THREAD

**Issue by kwstasna** [ParsePlatform/parse-dashboard#319]
- [ x] You're running version >=2.1.4 of Parse Server.

- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

Ubuntu
Parse-Dashboard v 1.0.10
Parse-Server v 2.2.7

#### Steps to reproduce

```
{
  "apps": [
    {
      "serverURL": "http://SOMEIP.com:1337/parse",
      "appId": "SomeAPPID",
      "masterKey": "SomeMASTERKEY",
      "appName": "Self'it"  //here is the issue
    }
  ],
"users": [
    {
      "user":"user",
      "pass":"pass"
    },
    {
      "user":"user1",
      "pass":"pass"
    }
  ]
```

So Parse-Dashboard has one problem. If i put on "appName" : "Self'it" 
i cant get inside the App and see the tables. But when i change the name to  "Selfit" i can get inside. The issue is the apostrophe! 
Just saying that maybe someone will get this issue and would like to find out what is causing the problem.

Dont know if there is anything that you can do about it!

**Comment by drew-gross** [comment]
This will be fixed in the next version.
