### ISSUE TITLE
Updated to node 6, Parse-Server works but Parse-Dashboard is broken

### ISSUE THREAD

**Issue by videre** [ParsePlatform/parse-dashboard#321]
sh: line 1: 70996 Segmentation fault: 11  webpack --config webpack/build.config.js --progress --watch

npm ERR! Darwin 12.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dashboard"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.8
npm ERR! code ELIFECYCLE
npm ERR! parse-dashboard@2.0.0 dashboard: `node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch`
npm ERR! Exit status 139
npm ERR! 
npm ERR! Failed at the parse-dashboard@2.0.0 dashboard script 'node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parse-dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parse-dashboard
npm ERR! There is likely additional logging output above.

**Comment by drew-gross** [comment]
I've just published v1.0.11 which fixes this issue.
