### ISSUE TITLE
users with read-only permissions?

### ISSUE THREAD

**Issue by drorsun** [ParsePlatform/parse-dashboard#322]
With parse-dashboard I want to be able to provide some users with read-only permissions for parse apps.

Is that possible?

**Comment by drew-gross** [comment]
No. This would require the addition of a read-only master key to Parse Server, so it's quite a big job to make this happen. It's not near the top of our priorities, but we would gladly accept help in making this happen!

**Comment by drorsun** [comment]
Sad to hear. Not that critical. Thanks

**Comment by erikbZhang** [comment]
Hi, I'm part of a group of high schooners who want to try and solve this problem. Could you give any additional pointers for us?

**Comment by flovilmart** [comment]
So many ideas could be implemented there. What would be your use case?

**Comment by erikbZhang** [comment]
We want to specifically make the database read only for some users, so they can see the data but not edit.

**Comment by flovilmart** [comment]
that's where it's tricky as we only have a masterKey not a readOnlyMasterKey, we shall implement it on parse-server to make sure the dashboard is secured properly :)
