### ISSUE TITLE
Uncaught Error: Cannot create a pointer to an unsaved ParseObject

### ISSUE THREAD

**Issue by ckarmy** [ParsePlatform/parse-dashboard#323]
Hi,
I'm running my parse-dashboard locally and work fine. But when I try to view one class I get a blank screen! I see that in the console I getting this error:
![screen shot 2016-05-05 at 12 33 41 pm](https://cloud.githubusercontent.com/assets/10090783/15048055/153cf956-12be-11e6-8921-e5caaf30839f.png)

How can I fix this?!

**Comment by drew-gross** [comment]
I haven't seen this error before. Can you try installing the dashboard locally and using `npm dev dashboard`? Then I can see a full stack trace.

**Comment by drew-gross** [comment]
No response in many days, closing.
