### ISSUE TITLE
Dashboard still not correctly parsing non-standard mount

### ISSUE THREAD

**Issue by notanark** [ParsePlatform/parse-dashboard#324]
Finally got it working correctly, now it's adding /parse to my mount when I try to delete. I can browse finally.

https://MYSITE/MYMOUNT/parse/batch Failed to load resource: the server responded with a status of 400 (Bad Request)

**Comment by drew-gross** [comment]
This issue is typically caused by using URL rewriting in nginx or something similar. Make sure that your mount URL matches your Parse Server mount.

**Comment by notanark** [comment]
I am not employing nginx. I'm using the software you gentlemen wrote.

**Comment by drew-gross** [comment]
Can you provide some logs from your Parse Server in case?

**Comment by drew-gross** [comment]
No response in many days, closing.
