### ISSUE TITLE
How to host parse dashboard on server other than local host like one on hostgator and enabling a URL for it?

### ISSUE THREAD

**Issue by saurabhkhare2004** [ParsePlatform/parse-dashboard#326]
How to host parse dashboard on server other than local host like one on hostgator and enabling a URL for it to access from anywhere? Is this possible at present? 

Regards

Saurabh Khare

**Comment by kwstasna** [comment]
Hello!
I've created 3 video tutorials of how you can install Parse-Server and Parse-Dashboard, including the migration steps, at DigitalOcean Servers.

Here is the playlist with the 3 video tutorials
https://www.youtube.com/playlist?list=PLOxfUzCCcGSDQGpSJFR4_5-s0V79XES5B

If you go at this link 
https://m.do.co/c/f59cde85cbde
you can sign up at Digital Ocean and get 10$ for free! 
If you have any question dont hesitate to ask!
Good luck!
