### ISSUE TITLE
Push notifications not being sent

### ISSUE THREAD

**Issue by jetsoleadmin** [ParsePlatform/parse-dashboard#332]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
Can you include some logs from Parse Server?

**Comment by jetsoleadmin** [comment]
I don't have logs but i noticed the issue is only happening when i send pushes from the dashboard via a campaign. Pushes are successful when sent via the api. I added a screen shot
![screen shot 2016-05-09 at 6 47 11 pm](https://cloud.githubusercontent.com/assets/8744162/15130478/9a9edb40-1616-11e6-9739-a2a598b166df.jpg)

**Comment by drew-gross** [comment]
This seems to be an issue with api.parse.com. Please use [parse.com/help](http://parse.com/help) for those issues.
