### ISSUE TITLE
Support for Pointer Permissions

### ISSUE THREAD

**Issue by drew-gross** [ParsePlatform/parse-dashboard#333]
This may also require some changes in Parse Server in the serverInfo endpoint.

**Comment by mmazzarolo** [comment]
Has this been implemented yet?  
I'm not able to add pointer permission through the dashboard on:  
`parse-server@2.2.10`
`parse-dashboard@1.0.11`

However I can see the pointer permissions by adding them manually on the SCHEMA (`readUserFields`, `writeUserFields`).

**Comment by drew-gross** [comment]
It will be in the next version, which I will push today.

**Comment by nsarafa** [comment]
@drew-gross would also like to see this feature implemented. Will go through the version history and try to find where it was introduced. Thanks for the support 👍
