### ISSUE TITLE
Parse import CSV / JSON button no longer there. 

### ISSUE THREAD

**Issue by TouchTitans** [ParsePlatform/parse-dashboard#335]
Using the still live Parse.com account. Haven't ported this client app yet. 

#### Environment Setup
Basic Parse account.

#### Steps to reproduce
Try to import a class to Parse Dashboard. The import class button is gone as of today. I don't see any mention from Parse on why they removed this feature.

**Comment by hramos** [comment]
We're using this repository to track issues related to the open source `parse-dashboard` project. For hosted Parse.com apps, you'll want to submit an issue through https://parse.com/help#report.

As a reminder, we highly encourage everyone to migrate their apps as soon as possible.
