### ISSUE TITLE
Page for sending new push notifications shows 500 error

### ISSUE THREAD

**Issue by gnegrei** [ParsePlatform/parse-dashboard#338]
Hello!

I've been having an issue for the last 2 days. I'm unable to send push notifications for one of my apps via the Parse Dashboard. 

Whenever I try opening "Send New Push", the following link "https://www.parse.com/apps/appname/push_notifications/new" opens a 500 error. (see attached image). 

Additional information:
- I'm using the old dashboard
- other apps from my account don't have this issue and are working properly. 

When I try using the new dashboard, when I create my audience, it doesn't show a specific condition that I need to filter my devices. 

Please help me with this as I'm planning a release to over 40 million users, and I need to make sure the push notifications are sent properly. 

Thanks!

**Comment by drew-gross** [comment]
For issues with Parse.com, please use [parse.com/help](http://parse.com/help).
