### ISSUE TITLE
Cannot delete field "email" in "User" class

### ISSUE THREAD

**Issue by mtrezza** [ParsePlatform/parse-dashboard#341]
#### Environment Setup
parse dashboard 1.0.11, parse server 2.2.9

#### Steps to reproduce
1. in class "user" click on field "email", given that the field contains an email address
2. hit "delete" key on keyboard
3. the email address text remains in the field instead of becoming "(undefined)"
4. click onto another field -> the previous email field changes to "(undefined)" and after 1 second changes back to the original email value

#### Logs/Trace
The email address cannot be deleted with the dashboard. However the value of the field can be changed and saved, e.g. setting another email address works. This occurs only with the "email" field, other custom fields in the User class can be deleted by keystroke.

**Comment by drew-gross** [comment]
This is a bug in Parse Server. I'll open an issue there and link it here.

**Comment by drew-gross** [comment]
Will be fixed in next version of Parse Server

**Comment by OpConTech** [comment]
Drew - sorry to go back to a closed issue but when I use a PFQuery for _User in iOS app to Parse Server (v2.3.1, heroku, mlab) I am unable to read the "email" field, for example in an iOS App:  

// (after PFQuery, log the email address of each user)
NSLog(@"Member Email: %@", [object objectForKey:@"email"]);   // email field reads null - Why?
NSLog(@"Member Name: %@", [object objectForKey:@"namel"]);   // name field reads normally...

This is only the case for the email fields. All of the other fields in the _User class read normally. 

Also, In a list of these fields all of the email fields are null except for the currently logged in user's email field which I am able to read normally.

Any feedback would be greatly appreciated.
