### ISSUE TITLE
Does not deleted row in the class

### ISSUE THREAD

**Issue by ValeriySoglaev** [ParsePlatform/parse-dashboard#350]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X] You're running version >=2.1.4 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Parse server 2.2.9
Parse dashboard 1.0.11

I have two app:
 https://api.test.net/parse/
 https://api.test.net/develop/

#### Steps to reproduce
In dashboard https://api.test.net/develop/ does not deleted row in the class. In first app https://api.test.net/parse/ deleted row is ok.

**Comment by drew-gross** [comment]
This is often cause by using path rewriting in nginx or another webserver/load balancer. Can you disable that if you are using it, and if not, post some logs containing the error you are seeing?

**Comment by ValeriySoglaev** [comment]
Hi, yes I use nginx

`server {
  listen *:80;
  server_name api.test.net www.api.test.net;
  rewrite ^(.*)$ https://api.test.net$1 permanent;
}
server {
     listen *:443;
     server_name api.test.net;

        keepalive_timeout   60;
        ssl_certificate /etc/nginx/ssl/api.test.crt;
        ssl_certificate_key /etc/nginx/ssl/api.test.key;
        ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers  "RC4:HIGH:!aNULL:!MD5:!kEDH";
        add_header Strict-Transport-Security 'max-age=604800';

     location /parse/ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:7001/parse/;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $http_host;
                proxy_redirect off;
     }
     location /develop/ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:7002/parse/;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $http_host;
                proxy_redirect off;
     }
     location / {
                try_files $uri $uri/ =404;
     }
}
`

**Comment by drew-gross** [comment]
Yes this an issue with your `nginx` config. Parse Dashboard assumes you aren't doing any URL rewriting, which you are doing.

**Comment by ValeriySoglaev** [comment]
You do not tell me how to fix it?

**Comment by ValeriySoglaev** [comment]
How can I fix it? Each application must be on a separate subdomain?

**Comment by ValeriySoglaev** [comment]
How run two app on a one domain?

**Comment by drew-gross** [comment]
You can use separate ports, separate subdomains, or separate mount points. For your `/develop/` route, just change the `app.use('/parse')` to `app.use('/develop')`.

**Comment by ValeriySoglaev** [comment]
thanks
