### ISSUE TITLE
Heroku Parse Dashboard can only be remotely accessed via HTTPS

### ISSUE THREAD

**Issue by jameslin101** [ParsePlatform/parse-dashboard#353]
I'm trying to run both Parse Server and Parse Dashboard on the same server/port as express middleware with the method
// make the Parse Dashboard available at /dashboard
app.use('/dashboard', dashboard);

Even after setting PARSE_DASHBOARD_ALLOW_INSECURE_HTTP to 1 in my Heroku env variables I'm still getting:

Parse Dashboard can only be remotely accessed via HTTPS

**Comment by drew-gross** [comment]
`PARSE_DASHBOARD_ALLOW_INSECURE_HTTP` only applies when running the dashboard command line app. If you are constructing and mounting the Dashboard on express, pass `true` as the second parameter to the `new ParseDashboard` function.

**Comment by jameslin101** [comment]
sweet! Thanks!
