### ISSUE TITLE
Problem connecting to Parse Server 2.2.10 with dashboard 1.0.11

### ISSUE THREAD

**Issue by unger** [ParsePlatform/parse-dashboard#354]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X ] You're running version >=2.1.4 of Parse Server.

- [X ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

Parse Server 2.2.10 running on Amazon AWS
Dashboard 1.0.11 running on Heroku

#### Steps to reproduce

Connecting to parse server 2.2.10 with dashboard 1.0.11 does not work for me, no data is shown in the Browser, and in the console I get a lot of these messages:

No Access-Control-Allow-Origin header is present on the requested resource. Origin is therefore not allowed access. The response had HTTP status code 504.

Probably getting these as the server and dashboard are on different domains?

When reverting back to server version 2.2.9 everything works again.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
HTTP status code 504 is thrown by your load balancer, proxy, or some other webserver and is not related to Parse Server or Parse Dashboard. Check your network setup and ask Server Fault if you can't find the issue.

Running on separate domains shouldn't be an issue, I myself run my dashboard and server on different domains.

**Comment by unger** [comment]
Thanks for the quick answer, maybe I made some wrong conclusions about this. As it works with 2.2.9 and not with 2.2.10, all other parts unchanged, it seamed like it was something introduced with that version.

**Comment by christiangenco** [comment]
For posterity, I was getting this issue because I forgot to add `/parse` to my `serverURL`.
