### ISSUE TITLE
Parse Dashboard access on LAN - Unable to connect to server

### ISSUE THREAD

**Issue by mistre83** [ParsePlatform/parse-dashboard#355]
I've just setup parse-server and parse-dashboard an there are both the latest  version.

I can use without problem on localhost, but i would like to use Parse Dashboard from another computer that is connected on LAN.

On Parse Dashboard i've used a _parse-dashboard-config.json_ to provide user and connect it to the server. If i visit http://localhost:4040 i can connect to the server and i see: Server URL: http://localhost:1337/parse.

If i open dashboard on lan (using http://192.168.0.12/:4040) i can connect to the dashboard but the message is: Server not reachable: unable to connect to server.

At the beginning, i need to setup server/dashboard on LAN because i need to understand how it works and develop some application.

I've checked a lot here and on Internet but i havent find a solution

**Comment by drew-gross** [comment]
The Parse Server URL you put in your config must be accessible to the machine you are accessing the dashboard from. It sounds like using `http://192.168.0.12:1337/parse` may work for you.

**Comment by mistre83** [comment]
Oh many Thanks! it was so simple!!

**Comment by mobilestar0223** [comment]
Woo! It worked well. I encountered same problem. I wasted a day for this issue. But it worked well and I just solve this problem. Many Thanks.
