### ISSUE TITLE
getting app_id and javascript_id from parse dashboard for ionic

### ISSUE THREAD

**Issue by Faisal-nfl** [ParsePlatform/parse-dashboard#356]
I am trying to make an ionic app with parse back-end.

I deployed open source parse server on heroku and and accessing it with parse dashboard from local machine.

I am following  [use-parse-core-in-ionic-framework-mobile-apps tutorial](https://www.thepolyglotdeveloper.com/2015/04/use-parse-core-in-ionic-framework-mobile-apps/l)
 to achieve this in which it ask to get app_id and javascript_id ,

app_id is quite clear but how to get javascript_id??

**Comment by drew-gross** [comment]
Javascript ID is no longer necessary, you can just ignore it/use an empty string..
