### ISSUE TITLE
App icons are not displayed as explained in the docs

### ISSUE THREAD

**Issue by deada92** [ParsePlatform/parse-dashboard#358]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ x] You're running version >=2.1.4 of Parse Server.

- [ x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Digitalocean Ubuntu (https://www.digitalocean.com/community/tutorials/how-to-migrate-a-parse-app-to-parse-server-on-ubuntu-14-04)

#### Steps to reproduce
So I have followed the digitalocean guide to install Parse-Server on an Ubuntu instance. Then I installed the Parse-Dashboard wich also works great now. I just have a simple problem: The App Icons are not showing up. I have created a folder `icons` at the same level of `parse-dashboard-config.json` and filled it with this:

```
{
  "apps": [
    {
      "serverURL": "xxx",
      "appId": "xxx",
      "masterKey": "xyxy",
      "appName": "PrayfortheWorld",
      "iconName": "pray.png",
      "production": true
    }
  ],
  "iconsFolder": "icons"
}
```

```
drwxrwxr-x  2 parse parse 4096 May 19 14:16 icons/
drwxrwxr-x  2 parse parse 4096 May 16 10:39 logs/
drwxrwxr-x 44 parse parse 4096 May 19 06:32 .npm/
-rw-r--r--  1 parse parse  342 May 19 14:15 parse-dashboard-config.json
```

I start the dashboard with this script:

```
var config = require('../parse-dashboard-config.json');
var express = require('express');
var ParseDashboard = require('parse-dashboard');

var dashboard = new ParseDashboard(config);
var app = express();

// make the Parse Dashboard available at /dashboard
app.use('/dashboard', dashboard);

var httpServer = require('http').createServer(app);
httpServer.listen(4040);
```

pm2 handles this job with following config:

```
{
  "apps" : [{
    ....
    },
    {
    "name"        : "parse-dash",
    "script"      : "/home/parse/dashboard/main.js",
    "watch"       : true,
    "merge_logs"  : true,
    "cwd"         : "/home/parse/dashboard",
    "log_date_format"  : "YYYY-MM-DD HH:mm Z",
    "max_memory_restart":  "100M",
    }
  ]
}
```

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

Any idea why this dont work?

**Comment by drew-gross** [comment]
Can you check your browser console to see if there is a request for the images? If so, can you check the response and the url to see what they are showing?

**Comment by deada92** [comment]
So the request is getting out but the response is empty:

```
Request URL:https://xxxxxx.com/dashboard/appicons/pray.png
Request Method:GET
Status Code:200 OK
Remote Address:45.55.173.103:443
Response Headers
view source
Connection:keep-alive
Content-Encoding:gzip
Content-Type:text/html; charset=utf-8
Date:Thu, 19 May 2016 18:42:44 GMT
Server:nginx/1.4.6 (Ubuntu)
Transfer-Encoding:chunked
X-Powered-By:Express
Request Headers
view source
Accept:image/webp,image/*,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,de;q=0.6,ar;q=0.4
Connection:keep-alive
Host:parseapi.cornea-apps.com
Referer:https://xxx.com/dashboard/apps
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
```

this looks kinda wrong: `https://xxxxxx.com/dashboard/appicons/pray.png`

**Comment by drew-gross** [comment]
No I think the url is fine. I'm not able to reproduce this issue. Could you maybe zip up a minimal system that demonstrates the issue so I can take a look?

**Comment by deada92** [comment]
I'm sorry its a dumb question but what do you mean with zip up a minimal system? I know what zip is but what should I zip??

One more thing: I use nginx to forward any requests to the applications. Here is my configs just for the locations:
```

        location /prayfortheworld/ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:1337/prayfortheworld/;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $http_host;
                proxy_redirect off;
        }


        location /dashboard/ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:4040/dashboard/;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $http_host;
                proxy_redirect off;
        }


        location / {
                try_files $uri $uri/ =404;
        }

```

I use also ssl as described in the guide of digitalocean. Also you said that the url is fine. Does the dashboard internally search for the icon at the path `/appicons/*.png` ??

**Comment by drew-gross** [comment]
Ah, I see the problem. When you do `new ParseDashboard` the information about where the `parse-dashboard-config.json` is gets lost. My recommendation is to remove your `parse-dashboard-config` file and paste the contents into your script, then adjust the `iconsFolder` to be pointing to the right place relative to where your script lives.
