### ISSUE TITLE
Parse Dashboard 404 error

### ISSUE THREAD

**Issue by septemberboy7** [ParsePlatform/parse-dashboard#366]
I've setup parse-server successfully. I can update objects from POST. But after logging in to parse dashboard. It's showing 404 error. I use a parse-dashboard-config.json file to start parse-dashboard. Am I misplacing the json file?

<img src="http://s33.postimg.org/gs7qllt3j/Screen_Shot_2016_05_23_at_10_56_14_PM.png" alt="Parse Dashboard 404 error" />

**Comment by drew-gross** [comment]
I think you must be visiting an incorrect URL in your dashboard. When the dashboard starts, it shows the URL it's available on, make sure you visit that URL.

**Comment by septemberboy7** [comment]
When it starts, it asks for username, password. I entered them as defined in the parse-dashboard-config.json and that 404 page occurs.

**Comment by drew-gross** [comment]
That would happen regardless of whether or not you visited the correct URL.

**Comment by septemberboy7** [comment]
Correct URL? I think http://localhost:4040/parse is a correct url.

**Comment by septemberboy7** [comment]
My URL was incorrect. It's just http://localhost:4040

**Comment by drew-gross** [comment]
That depends on your port and mount point.
