### ISSUE TITLE
How to keep Parse Dashboard running after I closed the terminal window on EC2?

### ISSUE THREAD

**Issue by JonathanKirknes** [ParsePlatform/parse-dashboard#368]
I just built Parse Dashboard on EC2 Ubuntu Server.

When I type this command, It's running correctly.

parse-dashboard --config parse-dashboard-config.json --allowInsecureHTTP true

But after I closed the terminal window or pressed Ctrl+C, Dashboard is terminated.

How can I keep my dashboard running forever?

Please help me.

Thank you!

**Comment by drew-gross** [comment]
There are many many ways to do this including `nohup`, `forever`, etc. If you need further help, please use Server Fault, as this isn't really a Parse Dashboard issue.
