### ISSUE TITLE
Background job has been stuck in "Running" status for over 15 minutes

### ISSUE THREAD

**Issue by JacobJT** [ParsePlatform/parse-dashboard#377]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ (still on Parse.com) ] You're running version >=2.1.4 of Parse Server.

- [ x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

Whatever you guys have on your servers. I pushed the cloud code your way.

#### Steps to reproduce

Run a background job

Wait

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

fixRecurringServiceProviderTake	05/26/16 10:17 AM UTC	01/01/01 12:00 AM UTC	running  

(It is currently 05/26/16 10:44 AM UTC)

**Comment by drew-gross** [comment]
For issues with the parse.com service, please use [parse.com/help](http://parse.com/help).
