### ISSUE TITLE
Problem with uploading files though proxy ngnix server.

### ISSUE THREAD

**Issue by Den-Ree** [ParsePlatform/parse-dashboard#381]
Hi, I use parse server with Digital Ocean and ver. 2.2.10. I have problem when uploading files to parse from dashboard. I get error - "unable to connect to parse api", when I use through proxy nginx server. But if I connect dashboard directly to node.js, everything is good.
Dashboard is located on another machine.
nginx 's config: 
location /devel/ { 

proxy_pass http://localhost:8000/; 
proxy_redirect off; 
proxy_set_header Host $host; 
proxy_set_header X-Real-IP $remote_addr; 

}
 node.js is situated by address:
http://localhost:8000/
Will be appreciated for any help)

**Comment by drew-gross** [comment]
Rewriting the URL in your nginx config isn't supported, unfortunately.
