### ISSUE TITLE
__op:Delete value populated when clearing cell

### ISSUE THREAD

**Issue by araskin** [ParsePlatform/parse-dashboard#383]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ X] You're running version >=2.1.4 of Parse Server.

- [X ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Mac OS X running local node connecting to remote databased hosted on AWS

#### Steps to reproduce
1. Create a column in a collection of type Object called 'testCol'
2. Create a new row and enter any valid JSON object in  'testCol'
3. Save the record 
4. Click on the 'testCol' column on the newly created record and hit DELETE on your keyboard. This should clear out the value in this record but instead populates the cell with the following value

![2016-05-30_0521](https://cloud.githubusercontent.com/assets/3648751/15646969/711b07ec-2626-11e6-8751-4864fba4734d.png)

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
This should be fixed by the newest version of Parse Server (2.2.11)
