### ISSUE TITLE
Date picker shows wrong day and numbers of days

### ISSUE THREAD

**Issue by iStopped** [ParsePlatform/parse-dashboard#387]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

ParseDashboard 1.0.11 

#### Steps to reproduce

May has 31 days not 30. Days are wrong!
Just open a date picker, screenshot attached.

<img width="245" alt="screen shot 2016-05-31 at 16 39 02" src="https://cloud.githubusercontent.com/assets/910971/15678418/91b1ead8-274e-11e6-8a59-bec3c4d0fd75.png">

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
Sorry, this doesn't reproduce for me, I see 31 days. Can yo utry updating to 1.0.12?

**Comment by steven-supersolid** [comment]
This should now be fixed in 1.0.19. The days were being calculated from the previous month in certain timezones.
