### ISSUE TITLE
Cannot read property 'attributes' of undefined

### ISSUE THREAD

**Issue by AlphaNerds** [ParsePlatform/parse-dashboard#389]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ x] You're running version >=2.1.4 of Parse Server.

- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Steps to reproduce
Access a user profile from main feed by clicking it.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

angular.js:13642 TypeError: Cannot read property 'attributes' of undefined
    at init (profile.modal.directive.js:38)
    at profile.modal.directive.js:115
    at processQueue (angular.js:16104)
    at angular.js:16120
    at Scope.$eval (angular.js:17378)
    at Scope.$digest (angular.js:17191)
    at Scope.$apply (angular.js:17486)
    at done (angular.js:11637)
    at completeRequest (angular.js:11843)
    at XMLHttpRequest.requestLoaded (angular.js:11776)

**Comment by drew-gross** [comment]
I don't think this is a dashboard issue, as your stack trace includes some angular, and we don't use angular.

**Comment by AlphaNerds** [comment]
Whoops. Posted in wrong place, sorry
On May 31, 2016 8:22 PM, Drew <notifications@github.com> wrote:I don't think this is a dashboard issue, as your stack trace includes some angular, and we don't use angular.
