### ISSUE TITLE
Parse-Server v2.2.11 unauthorized error

### ISSUE THREAD

**Issue by DazChong** [ParsePlatform/parse-dashboard#391]
As topic, parse-server previous version 2.2.10 are working fine.

As for version parse-server 2.2.11, iOS SDK and CURL test are working fine too. I inspect the error from the Chrome Dev Tools and discovered that parse-dashboard `POST` to `serverInfo`,`_User`, & `_Installation` are throwing error 403.

Not sure is parse-server issue or parse-dashboard.

Reverted back to parse-server 2.2.10 and parse-dashboard working again.

**Comment by drew-gross** [comment]
Can you show your server logs please? 403 unauthorized usually means incorrect master key or something like that.

**Comment by DazChong** [comment]
Ah.. I had it reverted and now testing on another app on other server within same dashboard. 

I suspect the error came from `_Installation` or `_User` class as the error do not occurred on this app.

The app that I having issue does not require `_Installation`, `_User`, or `_Session` as it serve as my personal development database.

Are both (including `_Session`) required as default?

**Comment by DazChong** [comment]
Follow up, same unauthorized issue appear again once I updated parse-server to 2.2.11.

Server side do not log anything even I turned on `VERBOSE`

iOS, PHP, CURL all working but not on parse-dashboard.

I created a new empty database instance to test but seem's like empty database doesn't affected. Will update again after more digging.

**Comment by theill** [comment]
I suspect https://github.com/ParsePlatform/parse-server/commit/03108e634776ebeda71c0c3159f8fbedff1b796c to be the issue. I'm having the same issue and in my case I'm running ParseServer behind an already basic authenticated route and thus the `appId` and `masterKey` will now be replaced with your username and password.

**Comment by DazChong** [comment]
It seems like the error no longer an issue upon 2.2.12 update, running fine for few days since. Closing issue.
