### ISSUE TITLE
The parse push dashboard on parse.com is broken

### ISSUE THREAD

**Issue by MarkMurphy** [ParsePlatform/parse-dashboard#393]
My browser console reveals the following 

```
Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
```

Occurs on https://dashboard.parse.com/apps/{YOURAPPNAMEHERE}/push/activity/all

replace `{YOURAPPNAMEHERE}` with an actual parse app name.

**Comment by drew-gross** [comment]
For issues with the parse.com service, please use [parse.com/help](http://parse.com/help).

**Comment by MarkMurphy** [comment]
@drew-gross That's where I came from. It brought me here.
