### ISSUE TITLE
Blank screen from forever

### ISSUE THREAD

**Issue by alehkudrevich** [ParsePlatform/parse-dashboard#396]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.]

Hello.
I install Parse Dashboard and all works fine when I start like this:

> parse-dashboard

But, when I try to start it from forever, I've got blank screen. How can I fix it? Thanks.

> forever-service install parse-dashboard --script ./Parse-Dashboard/index.js
> start parse-dashboard

**Comment by drew-gross** [comment]
This issue seems to be with `forever` and not with `parse-dashboard`. We can't support `forever` here.
