### ISSUE TITLE
While uploading file using parse deshboard running with my own server, its not stored in MongoDb. I want to store file in MongoDb.

### ISSUE THREAD

**Issue by ankit1234** [ParsePlatform/parse-dashboard#397]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [*] You're running version >=2.1.4 of Parse Server.

- [*] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Latest Version of Parse Server 2.2.11 and 1.0.12 Parse dashboard

#### Steps to reproduce
Like I have set up parse-server and parse-dashboard in my ubuntu server. But when I try to upload file from dash board its just show processing finish but file is not visible. But if I upload file from my android app its showing.(with mongo db storage path, I am not using S3)
So like I am thinking problem with dashboard not with parse-server. Please let me know to use FileAdapter do I need to modify any thing inside dashboard.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by ankit1234** [comment]
My self, I found solution. Like as per written in nots of Parse-dashboard, javascriptKey is required in your configuration file. But in doc it is written only required for app which is still on Parse.com.
But its required for migrated parse server apps also.
So better some where add this note in documentation.

**Comment by kevalshah09** [comment]
I did added the javascriptkey to Parse Dashboard and parse-server but it still doesn't work. I have added the key when initializing both in index.js. Can you tell me where exactly I should do this.
