### ISSUE TITLE
Can't send push notification from Parse Dashboard

### ISSUE THREAD

**Issue by iziaviyente** [ParsePlatform/parse-dashboard#398]
Getting this error when trying to send a push notification through Parse:

ERROR:
read tcp 10.252.5.204:44390->10.252.5.224:27017: i/o timeout

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ X] You're running version >=2.1.4 of Parse Server.

- [X ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
That seems like an issue with your mongo database. Can you make sure you can do other stuff with your Parse Server?

**Comment by dvanwinkle** [comment]
@drew-gross This can probably be closed.
