### ISSUE TITLE
Parse dashboard cannot see mongodb imported collection  !

### ISSUE THREAD

**Issue by modiodio** [ParsePlatform/parse-dashboard#407]
#### Environment Setup
OS => Ubuntu 14.04.4 LTS
Node JS => v6.2.1
parse version => v2.2.11
parse dashbord => The current version
Mongodb version => v3.0.12

Hello Guys,
I need your help because I'm stuck for two days with parse dashboard

I Install parse server and parse dashboard on my remote server.
I download my database mongodb from parse.com. 
And I imported the json file in my own database mongodb with the command line below : 
mongoimport --host localhost --db newdatabase --collection _User --file _User.json

But when I log on to parse dashboard I don't see the collection _User I imported ! 

#### Parse server configuration
```
var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/newdatabase',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'My App ID',
  masterKey: process.env.MASTER_KEY || 'My master Key',
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',
  liveQuery: {
    classNames: ["Posts", "Comments"]
  }
});
```

#### Parse Dashboard configuration
```
{
  "apps": [{
      "serverURL": "http://91.123.765.12:1337/parse",
      "appId": "my app id",
      "masterKey": "my master key",
      "javascriptKey": "my js key",
      "restKey": "rest key",
      "appName": "AppName",
      "production": true
  }],
  "iconsFolder": "icons",
  "users": [
      {
           "user":"test",
           "pass":"test"
      }
   ]
}
```

Thanks you in advance for your answer

**Comment by drew-gross** [comment]
You also need to import the _SCHEMA collection.

**Comment by BlackKnight7** [comment]
Hi  @drew-gross , I'm new to mongo, you said we can import the _SCHEMA collection, but how? I've viewed all docs for mongoimport, but didn't find any doc about import schema. Can you add give us one example?

**Comment by anushajp** [comment]
Hi @drew-gross, Could you please explain how we can import the _SCHEME collection?

**Comment by memsis** [comment]
Terrible necro, but : the _SCHEMA isn,t available in the Parse Export file... So we are stuck at either rebuilding it by hand, having parse dashboard rebuilding it or having an external tool.

Any idea on the fastest route available for now ?

**Comment by flovilmart** [comment]
You should you the migration too from parse.com not the exported JSON files

**Comment by memsis** [comment]
As I understand it, as soon as the migration is done from Parse, the app
will use the new MongoDB server to manage the data. But before we can get
to this point we have to run tests on our new Parse Server to make sure it
will works properly. And the only way I could find for now is to get the
JSON files from Parse... If I'm wrong at one point, please correct me :-)

---------------------------------------------------------------------------------------------------------------------------------------------
Sébastien Lemieux

2016-10-27 17:48 GMT-04:00 Florent Vilmart <notifications@github.com>:

**Comment by flovilmart** [comment]
You should not try to import the JSON files to the mongo database, that's not the recommended way. In any case, you should migrate your database to mongodb.

**Comment by memsis** [comment]
As I understand it, as soon as the migration is done from Parse, the app will use the new MongoDB server to manage the data. This is not what I want for now, since we are still testing the new MongoDB platform. I'd like not to have to blindly trust a new service provider.

**Comment by flovilmart** [comment]
ok, your call then. I can't help much. The migration to mongodb was recommended a while ago, if this is not a route you want to explore, I can't be of much help here. If you want to try to import your JSON object you will have likely problems as parse-server is designed to work flawlessly from a migrated parse or new objects. not with JSON inserted objects.

**Comment by memsis** [comment]
@flovilmart We only want to test our MongoDB server and Parse Server installation before moving it to production. So using the "migration tool" from Parse seems out of the question for us, since we don't want to move our mongo server in production right now, we want to test.

**Comment by steven-supersolid** [comment]
You could try cloning your app in parse.com which should copy _SCHEMA but not the data. Then you can migrate your cloned app to a new MongoDB provider and import the data from your production app.
Then you can test parse-server and parse-dashboard against your cloned app database.

**Comment by fanatixgithub** [comment]
@memsis I think there's one thing that's not been explained or you've not understood properly: you can *start* the migration process from Parse to your own Parse Server, have it completely copy all your data over, but not *finalise* the migration - meaning it'll leave all the data on your own Server, but still use live Parse until you click Finalise. This is how I've tested my local Parse Server/Dashboard/Mongo combo, just kicked off the migration but not finalised it. You can do this as many times as you need to.

**Comment by memsis** [comment]
@steven-supersolid  and @fanatixgithub, thanks for the cue. Stevens solution should have been a no-brainer for us, I completly overlooked that option. And Fanatix's explanation is exactly what I was looking for.

Thanks to both of you.
