### ISSUE TITLE
Class creation permission

### ISSUE THREAD

**Issue by jcano** [ParsePlatform/parse-dashboard#408]
I'm currently using parse-server 2.2.12 and parse-dashboard 1.0.13 in a dev environment. 

I'm trying to restrict the creation of classes to only admin and on one of the old guides it says that it should be done on the settings tab of the data browser. I'm assuming the organization of the UI has changed but I clicked everywhere and still can't find anything close to "App Permissions".

On "Security", inside the browser, I can set the CLP and on each row of a collection I have access to the ACL, but I don't how to disable class creation by users.

Where is this option?

**Comment by drew-gross** [comment]
This is now done using the `allowClientClassCreation` setting in Parse Server. Can you link to this guide? We should update it.

**Comment by jcano** [comment]
I think it's in all the SDK guides. To list a few:

https://parse.com/docs/ios/guide#security-restricting-class-creation
https://parse.com/docs/android/guide#security-restricting-class-creation
https://parse.com/docs/js/guide#security-restricting-class-creation

**Comment by Abderezai** [comment]
turning off the class creation permission will disable it for all, even admin. I think the question is how to allow a specific user (admin) to create classes.
I haven't tested this, but maybe you can make a parse server on a local machine, and on that instance allow class creation, and then login locally with Dashboard and create a class.

**Comment by NatanRolnik** [comment]
This is available in the latest releases.
