### ISSUE TITLE
Admin Credentials Not Working on Existing Parse App - Can't Access to Migrate.

### ISSUE THREAD

**Issue by mbreit262** [ParsePlatform/parse-dashboard#409]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=2.1.4 of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Whatever is currently on parse.com?

#### Steps to reproduce
We're trying to start our parse migration but the admin credentials for one of our projects is not working and the password reset e-mail just redirects to parse.com

Trying to log in here: https://www.parse.com/login
Using the credentials below:

user: mwoodell@spotify.com
pass: pharrell1

Yields an invalid email/password error.

Tried to reset password but e-mail contains a link:
- https://www.parse.com/password_resets/DTgOSoNgEUJdIMr1HEoY/edit

That simply redirects to parse.com whether you click it or paste it into browser.

Any help is appreciated.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
For issues with the parse.com service, please use [parse.com/help](http://parse.com/help).
