### ISSUE TITLE
I cannot select all in my own host dashboard?

### ISSUE THREAD

**Issue by kevinlee85** [ParsePlatform/parse-dashboard#412]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Parse-server is hosed by Heroku. MongoDB is hosted by mLab.
Parse-Dashboard is started on my owned local computer.

#### Steps to reproduce
Only one class by Parse-Dashboard.
Try to select all rows.
Then Dashboard do not allow me to do it.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by AmbroiseCollon** [comment]
https://github.com/ParsePlatform/parse-dashboard/issues/124
