### ISSUE TITLE
Dashboard app list sort order

### ISSUE THREAD

**Issue by 185driver** [ParsePlatform/parse-dashboard#415]
When the dashboard loads and displays the app list, the sort order of the apps seems to vary each time. It would be nice if the list had a consistent alpha default sort order.

I'm managing several apps using the same parse server and on a single dashboard, if that's a factor.

Thanks for considering.

**Comment by drew-gross** [comment]
FIxed y=by #417

**Comment by 185driver** [comment]
Thank you, sir.
