### ISSUE TITLE
Export / Import data - previously supported on parse.com

### ISSUE THREAD

**Issue by MobileVet** [ParsePlatform/parse-dashboard#419]
Dashboard 1.0.13
Server 2.2.13

It would be helpful to allow exporting and importing data.  This helps when creating development and production servers that include some 'base' data that is shared across each 'application'.

**Comment by nsarafa** [comment]
check out [this gist](https://gist.github.com/davimacedo/c7738203a2a616b48a22fdc7c00b37d2) showing an example of a background job for importing parse data via a curl request

**Comment by MobileVet** [comment]
Duplicate of #307
