### ISSUE TITLE
Parse Dashboard error when deploying to heroku

### ISSUE THREAD

**Issue by SoniaAbed** [ParsePlatform/parse-dashboard#421]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=2.1.4 of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
node version 4.4.5
npm version 2.15.5
#### Steps to reproduce
I used this tutorial to setup parse dashboard on heroku server:
https://www.andrewcbancroft.com/2016/04/17/deploying-parse-dashboard/
![heroku](https://cloud.githubusercontent.com/assets/6106954/16045254/50c37868-3250-11e6-8749-01d216c46f31.png)

#### Logs/Trace
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.15.5
3 info using node@v4.4.5
4 verbose readDependencies loading dependencies from /Users/macbook/ParseDashboard/parse-dashboard/package.json
5 verbose install where, deps [ '/Users/macbook/ParseDashboard/parse-dashboard',
5 verbose install   [ 'basic-auth',
5 verbose install     'commander',
5 verbose install     'express',
5 verbose install     'json-file-plus',
5 verbose install     'package-json',
5 verbose install     'babel-core',
5 verbose install     'babel-loader',
5 verbose install     'babel-plugin-remove-proptypes',
5 verbose install     'babel-polyfill',
5 verbose install     'babel-runtime',
5 verbose install     'css-loader',
5 verbose install     'file-loader',
5 verbose install     'history',
5 verbose install     'http-server',
5 verbose install     'immutable',
5 verbose install     'immutable-devtools',
5 verbose install     'jest-cli',
5 verbose install     'js-beautify',
5 verbose install     'marked',
5 verbose install     'node-sass',
5 verbose install     'parse',
5 verbose install     'prismjs',
5 verbose install     'react',
5 verbose install     'react-addons-test-utils',
5 verbose install     'react-dnd',
5 verbose install     'react-dnd-html5-backend',
5 verbose install     'react-dom',
5 verbose install     'react-router',
5 verbose install     'sass-loader',
5 verbose install     'style-loader',
5 verbose install     'svg-prep',
5 verbose install     'transform-jest-deps',
5 verbose install     'webpack' ] ]
6 verbose install where, peers [ '/Users/macbook/ParseDashboard/parse-dashboard', [] ]
7 verbose installManyTop reading for lifecycle /Users/macbook/ParseDashboard/parse-dashboard/package.json
8 info preinstall parse-dashboard@1.0.14
9 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/babel-core/package.json
10 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/babel-loader/package.json
11 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/babel-plugin-remove-proptypes/package.json
12 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/babel-polyfill/package.json
13 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/babel-runtime/package.json
14 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/basic-auth/package.json
15 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/commander/package.json
16 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/css-loader/package.json
17 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/express/package.json
18 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/file-loader/package.json
19 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/history/package.json
20 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/http-server/package.json
21 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/immutable/package.json
22 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/immutable-devtools/package.json
23 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/jest-cli/package.json
24 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/js-beautify/package.json
25 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/json-file-plus/package.json
26 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/marked/package.json
27 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/node-sass/package.json
28 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/package-json/package.json
29 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/parse/package.json
30 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/prismjs/package.json
31 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/react/package.json
32 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/react-addons-test-utils/package.json
33 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/react-dnd/package.json
34 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/react-dnd-html5-backend/package.json
35 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/react-dom/package.json
36 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/react-router/package.json
37 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/sass-loader/package.json
38 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/style-loader/package.json
39 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/svg-prep/package.json
40 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/transform-jest-deps/package.json
41 verbose installManyTop reading scoped package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/webpack/package.json
42 info package.json babel-plugin-remove-proptypes@1.0.3 dev-dependencies should probably be devDependencies.
43 info package.json babel-polyfill@6.9.1 No description
44 info package.json immutable-devtools@0.0.7 license should be a valid SPDX license expression
45 info package.json svg-prep@1.0.4 No description
46 info package.json svg-prep@1.0.4 No repository field.
47 info package.json svg-prep@1.0.4 No license field.
48 verbose readDependencies loading dependencies from /Users/macbook/ParseDashboard/parse-dashboard/package.json
49 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/babel-core/package.json
50 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/babel-loader/package.json
51 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/babel-plugin-remove-proptypes/package.json
52 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/babel-polyfill/package.json
53 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/babel-runtime/package.json
54 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/basic-auth/package.json
55 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/commander/package.json
56 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/css-loader/package.json
57 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/express/package.json
58 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/file-loader/package.json
59 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/history/package.json
60 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/http-server/package.json
61 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/immutable/package.json
62 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/immutable-devtools/package.json
63 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/jest-cli/package.json
64 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/js-beautify/package.json
65 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/json-file-plus/package.json
66 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/marked/package.json
67 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/node-sass/package.json
68 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/package-json/package.json
69 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/parse/package.json
70 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/prismjs/package.json
71 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/react/package.json
72 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/react-addons-test-utils/package.json
73 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/react-dnd/package.json
74 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/react-dnd-html5-backend/package.json
75 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/react-dom/package.json
76 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/react-router/package.json
77 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/sass-loader/package.json
78 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/style-loader/package.json
79 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/svg-prep/package.json
80 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/transform-jest-deps/package.json
81 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/webpack/package.json
82 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/.bin/css-beautify/package.json
83 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/.bin/hs/package.json
84 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/.bin/html-beautify/package.json
85 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/.bin/http-server/package.json
86 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/.bin/jest/package.json
87 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/.bin/js-beautify/package.json
88 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/.bin/marked/package.json
89 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/.bin/node-sass/package.json
90 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/.bin/svg-prep/package.json
91 verbose targetResolver reading package data from /Users/macbook/ParseDashboard/parse-dashboard/node_modules/.bin/webpack/package.json
92 verbose already installed skipping immutable-devtools@~0.0.4 /Users/macbook/ParseDashboard/parse-dashboard
93 verbose already installed skipping jest-cli@^12.0.2 /Users/macbook/ParseDashboard/parse-dashboard
94 verbose already installed skipping js-beautify@~1.5.0 /Users/macbook/ParseDashboard/parse-dashboard
95 verbose already installed skipping marked@^0.3.5 /Users/macbook/ParseDashboard/parse-dashboard
96 verbose already installed skipping node-sass@^3.7.0 /Users/macbook/ParseDashboard/parse-dashboard
97 verbose already installed skipping parse@1.6.14 /Users/macbook/ParseDashboard/parse-dashboard
98 verbose already installed skipping prismjs@~1.2.0 /Users/macbook/ParseDashboard/parse-dashboard
99 verbose already installed skipping react@^15.0.1 /Users/macbook/ParseDashboard/parse-dashboard
100 verbose already installed skipping react-addons-test-utils@^15.0.1 /Users/macbook/ParseDashboard/parse-dashboard
101 verbose already installed skipping react-dnd@~2.1.4 /Users/macbook/ParseDashboard/parse-dashboard
102 verbose already installed skipping react-dnd-html5-backend@~2.0.0 /Users/macbook/ParseDashboard/parse-dashboard
103 verbose already installed skipping react-dom@^15.0.1 /Users/macbook/ParseDashboard/parse-dashboard
104 verbose already installed skipping react-router@2.3.0 /Users/macbook/ParseDashboard/parse-dashboard
105 verbose already installed skipping sass-loader@~3.1.2 /Users/macbook/ParseDashboard/parse-dashboard
106 verbose already installed skipping style-loader@~0.12.3 /Users/macbook/ParseDashboard/parse-dashboard
107 verbose already installed skipping svg-prep@~1.0.0 /Users/macbook/ParseDashboard/parse-dashboard
108 verbose already installed skipping transform-jest-deps@^2.1.0 /Users/macbook/ParseDashboard/parse-dashboard
109 verbose already installed skipping webpack@~1.12.0 /Users/macbook/ParseDashboard/parse-dashboard
110 verbose already installed skipping basic-auth@^1.0.3 /Users/macbook/ParseDashboard/parse-dashboard
111 verbose already installed skipping commander@^2.9.0 /Users/macbook/ParseDashboard/parse-dashboard
112 verbose already installed skipping express@^4.13.4 /Users/macbook/ParseDashboard/parse-dashboard
113 verbose already installed skipping json-file-plus@^3.2.0 /Users/macbook/ParseDashboard/parse-dashboard
114 verbose already installed skipping package-json@^2.3.1 /Users/macbook/ParseDashboard/parse-dashboard
115 verbose already installed skipping babel-core@~5.8.12 /Users/macbook/ParseDashboard/parse-dashboard
116 verbose already installed skipping babel-loader@~5.3.0 /Users/macbook/ParseDashboard/parse-dashboard
117 verbose already installed skipping babel-plugin-remove-proptypes@~1.0.0 /Users/macbook/ParseDashboard/parse-dashboard
118 verbose already installed skipping babel-polyfill@^6.7.2 /Users/macbook/ParseDashboard/parse-dashboard
119 verbose already installed skipping babel-runtime@~5.8.25 /Users/macbook/ParseDashboard/parse-dashboard
120 verbose already installed skipping css-loader@~0.18.0 /Users/macbook/ParseDashboard/parse-dashboard
121 verbose already installed skipping file-loader@^0.8.5 /Users/macbook/ParseDashboard/parse-dashboard
122 verbose already installed skipping history@~1.9.1 /Users/macbook/ParseDashboard/parse-dashboard
123 verbose already installed skipping http-server@~0.8.5 /Users/macbook/ParseDashboard/parse-dashboard
124 verbose already installed skipping immutable@~3.7.5 /Users/macbook/ParseDashboard/parse-dashboard
125 silly install resolved []
126 info build /Users/macbook/ParseDashboard/parse-dashboard
127 info linkStuff parse-dashboard@1.0.14
128 silly linkStuff parse-dashboard@1.0.14 has /Users/macbook/ParseDashboard as its parent node_modules
129 verbose linkBins parse-dashboard@1.0.14
130 verbose linkMans parse-dashboard@1.0.14
131 verbose rebuildBundles parse-dashboard@1.0.14
132 verbose rebuildBundles [ '.bin',
132 verbose rebuildBundles   'babel-core',
132 verbose rebuildBundles   'babel-loader',
132 verbose rebuildBundles   'babel-plugin-remove-proptypes',
132 verbose rebuildBundles   'babel-polyfill',
132 verbose rebuildBundles   'babel-runtime',
132 verbose rebuildBundles   'basic-auth',
132 verbose rebuildBundles   'commander',
132 verbose rebuildBundles   'css-loader',
132 verbose rebuildBundles   'express',
132 verbose rebuildBundles   'file-loader',
132 verbose rebuildBundles   'history',
132 verbose rebuildBundles   'http-server',
132 verbose rebuildBundles   'immutable',
132 verbose rebuildBundles   'immutable-devtools',
132 verbose rebuildBundles   'jest-cli',
132 verbose rebuildBundles   'js-beautify',
132 verbose rebuildBundles   'json-file-plus',
132 verbose rebuildBundles   'marked',
132 verbose rebuildBundles   'node-sass',
132 verbose rebuildBundles   'package-json',
132 verbose rebuildBundles   'parse',
132 verbose rebuildBundles   'prismjs',
132 verbose rebuildBundles   'react',
132 verbose rebuildBundles   'react-addons-test-utils',
132 verbose rebuildBundles   'react-dnd',
132 verbose rebuildBundles   'react-dnd-html5-backend',
132 verbose rebuildBundles   'react-dom',
132 verbose rebuildBundles   'react-router',
132 verbose rebuildBundles   'sass-loader',
132 verbose rebuildBundles   'style-loader',
132 verbose rebuildBundles   'svg-prep',
132 verbose rebuildBundles   'transform-jest-deps',
132 verbose rebuildBundles   'webpack' ]
133 info install parse-dashboard@1.0.14
134 info postinstall parse-dashboard@1.0.14
135 info prepublish parse-dashboard@1.0.14
136 verbose unsafe-perm in lifecycle true
137 info parse-dashboard@1.0.14 Failed to exec prepublish script
138 verbose stack Error: parse-dashboard@1.0.14 prepublish: `webpack --config webpack/publish.config.js`
138 verbose stack Exit status 1
138 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
138 verbose stack     at emitTwo (events.js:87:13)
138 verbose stack     at EventEmitter.emit (events.js:172:7)
138 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
138 verbose stack     at emitTwo (events.js:87:13)
138 verbose stack     at ChildProcess.emit (events.js:172:7)
138 verbose stack     at maybeClose (internal/child_process.js:827:16)
138 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
139 verbose pkgid parse-dashboard@1.0.14
140 verbose cwd /Users/macbook/ParseDashboard/parse-dashboard
141 error Darwin 15.3.0
142 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
143 error node v4.4.5
144 error npm  v2.15.5
145 error code ELIFECYCLE
146 error parse-dashboard@1.0.14 prepublish: `webpack --config webpack/publish.config.js`
146 error Exit status 1
147 error Failed at the parse-dashboard@1.0.14 prepublish script 'webpack --config webpack/publish.config.js'.
147 error This is most likely a problem with the parse-dashboard package,
147 error not with npm itself.
147 error Tell the author that this fails on your system:
147 error     webpack --config webpack/publish.config.js
147 error You can get information on how to open an issue for this project with:
147 error     npm bugs parse-dashboard
147 error Or if that isn't available, you can get their info via:
147 error
147 error     npm owner ls parse-dashboard
147 error There is likely additional logging output above.
148 verbose exit [ 1, true ]
 
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
That tutorial is a bit outdated. Please use the instructions in the readme.
