### ISSUE TITLE
Billing issues - can't find a better place to report

### ISSUE THREAD

**Issue by JacobJT** [ParsePlatform/parse-dashboard#423]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ x] You're running version >=2.1.4 of Parse Server.

- [ x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

I'm on Parse.com here

#### Steps to reproduce

Looking at my biling history

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

I submitted a "bug" on Facebook, as it seemed to be the only place to contact anyone, but haven't gotten a hold of anyone.

The "An issue with your bill? Please contact us" just takes me to the faq, with a contact us link that brings me here, so you guys are stuck with me.

I keep getting notifications that my card was declined and that I may experience service interruptions. I had $500 in Parse credits. I used $287.84 in May. I used $271.52 in June. I shut off my paid tier services, while I still had the remaining $212.16 on my account. It's trying to make me pay the full $271.52.  Please reduce my bill to the proper $58.36 so I can update my billing info and get rid of this ugly red bar at the top of my dashboard and avoid service interruptions. 

Find my post on the Parse Server Developers facebook group, or the one I submitted through the Facebook help center I somehow stumbled on from Parse.com at some point.

**Comment by hramos** [comment]
This repository is for Parse Server issues. For billing inquiries regarding the hosted Parse.com service, please see the contact information at the bottom of your billing receipt that is sent via email to the account owner.

**Comment by JacobJT** [comment]
I did. It brought me here.

**Comment by JacobJT** [comment]
Please put me in direct contact with who I need to be put in contact with
to resolve this.

**Comment by hramos** [comment]
My followup on June 13 to your bug report has all the details about this case as well as instructions on how to get in touch with billing.
