### ISSUE TITLE
Downloading iOS Certificates

### ISSUE THREAD

**Issue by khallouf** [ParsePlatform/parse-dashboard#425]
Hello everyone,
we are trying to move to another service since parse is - unfortunately - shutting down

so I have been trying to retrieve our data to implement the new one
I'm trying to download our iOS certificate files but I can't find anyway to do that

the only result I found while searching was in an old Dashboard design which had a download button, but I can't find anything in the current Dashboard

is there a way to retrieve the certificates or I have to generate them again?

thanks

**Comment by peterdotjs** [comment]
@khallouf you can retrieve your cert by going to the legacy dashboard on parse.com/apps through the settings page.
