### ISSUE TITLE
Cannot unset a string column

### ISSUE THREAD

**Issue by AmbroiseCollon** [ParsePlatform/parse-dashboard#426]
#### Environment Setup
Parse Server 2.2.13
Parse Dashboard 1.0.14

#### Steps to reproduce
1. Write 'foo' in a cell of a String type column
2. Delete everything in the cell
3. Press enter

=> The cell contains an empty string and not `(undefined)` as expected

**Comment by andrewimm** [comment]
If you highlight the cell without editing it, you can press "Backspace" or "Delete" to return its contents to undefined. This should be true for every cell type.

**Comment by AmbroiseCollon** [comment]
Ok so this embarrassing...
