### ISSUE TITLE
cant load my data in dashboard

### ISSUE THREAD

**Issue by superbbirds** [ParsePlatform/parse-dashboard#434]
hi,

i have a account on parse.com 
today when i log in to my account in parse , i could not see my data with ip from iran 
why this happen? how i can fix this problem with my account 

![2](https://cloud.githubusercontent.com/assets/12657590/16357712/72a0bed4-3b13-11e6-94eb-a23eea7ecf95.png)

thanks

**Comment by flovilmart** [comment]
Problems on parse.com should be reported with https://parse.com/help#report.

Thanks
