### ISSUE TITLE
Is there a GitHub project for Heroku deployment?

### ISSUE THREAD

**Issue by grassland-curing-cfa** [ParsePlatform/parse-dashboard#443]
Just wondering if there is a GitHub project for Parse-Dashboard so that I can clone and then deploy it on my Heroku as a new app?
It'd be even better if the Dashboard can host multiple Parse apps!
Thanks!

**Comment by bohemima** [comment]
Parse Dashboard can have multiple apps, see https://github.com/ParsePlatform/parse-dashboard#managing-multiple-apps. Also, from what I can see, there is a Procfile to make it ready for Heroku deployment (https://github.com/ParsePlatform/parse-dashboard/blob/master/Procfile)

**Comment by grassland-curing-cfa** [comment]
Thanks @bohemima !
I had a look at the Procfile but still no clue as to how-to. Can you point me how to use the Procfile to deploy the Dashboard to Heroku please?
