### ISSUE TITLE
No data in the Performance section

### ISSUE THREAD

**Issue by yshahak** [ParsePlatform/parse-dashboard#444]
We have Android app that use Parse. I can see in the Analytics section in the Dashboard that we have about 700K API requests per day, and we got couple of time email that we exceeded more than 75% of the limit for 30 per/sec.
The issue is, when I trying to see data about the request, under the Performance section, nothing is shown at all.
![image](https://cloud.githubusercontent.com/assets/6691908/16555700/9d5bf360-41de-11e6-89e3-4d12531443c4.png)

**Comment by flovilmart** [comment]
Please use http://parse.com/help for problems unrelated to open source projects.

**Comment by yshahak** [comment]
Aactually I came here from the link you supplied, but I guess it is indeed not the right place.
