### ISSUE TITLE
Two redundent -createdAt were used.

### ISSUE THREAD

**Issue by 5amfung** [ParsePlatform/parse-dashboard#447]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

parse-server@2.2.14
parse-dashboard@1.0.14

#### Steps to reproduce

1. Set VERBOSE=1 for parse-server
2. Click on one of your object under Browser in your Parse Dashboard.
3. Look at the parse-server debug output, you will see `"order": "-createdAt,-createdAt"`

Here's the full GET request.  I see the double `-createdAt` being used for all Parse objects.
```
verbose: GET /parse/classes/Image { host: 'localhost:1337',
  connection: 'keep-alive',
  'content-length': '243',
  origin: 'http://localhost:1337',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.49 Safari/537.36',
  'content-type': 'text/plain',
  accept: '*/*',
  dnt: '1',
  referer: 'http://localhost:1337/dashboard/apps/Infocery/browser/Image',
  'accept-encoding': 'gzip, deflate',
  'accept-language': 'en-US' } {
  "where": {},
  "limit": 200,
  "order": "-createdAt,-createdAt"
}
```

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
Is this causing any bugs? If not we can probably just leave it as is.

**Comment by TylerBrock** [comment]
Yeah, actually it seems to me that i'm unable to sort on createdAt in ascending order.
