### ISSUE TITLE
Migrate Schema

### ISSUE THREAD

**Issue by adampietrasiak** [ParsePlatform/parse-dashboard#45]
Is there any way to save current schema of classes (with all the fields) and to import it later?

**Comment by drew-gross** [comment]
You can easily save the current schemas in the API console, just use `schemas` for the endpoint and make sure to use the master key. We don't currently have a great way to import a schema, but we would happily accept PRs!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.3](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0)
