### ISSUE TITLE
Would it be better that the <a> footer of sidebar open as new tab?

### ISSUE THREAD

**Issue by durunvo** [ParsePlatform/parse-dashboard#450]
Would it be better that the <a> footer of sidebar open as new tab? Just pure curious.

**Comment by drew-gross** [comment]
Yeah that would probably be nice! Want to help?

**Comment by durunvo** [comment]
Sure, if anyone have not done it yet.

**Comment by drew-gross** [comment]
Someone just did it :P which I why I closed this.
