### ISSUE TITLE
The 'Add row' icon is at the bottom of a table... this should be moved to the header area of the table view.

### ISSUE THREAD

**Issue by MobileVet** [ParsePlatform/parse-dashboard#451]
Having the + at the bottom of the rows is problematic if you have a lot of rows.  Ideally it should be placed in the upper header area.

![dashboard](https://cloud.githubusercontent.com/assets/1977118/16661963/66f00eb2-4443-11e6-807f-1cb835e70db4.jpg)

**Comment by MobileVet** [comment]
I realize it is in the list of 'edit' options... but it doesn't make much sense to be at the end of a long list of rows.  Maybe it should just be deleted?  Could be placed in front of the Object name as well.

Clearly a low priority item

**Comment by grassland-curing-cfa** [comment]
Agree with you @MobileVet

**Comment by drew-gross** [comment]
I also agree. This would be a good first contribution since there are already examples of how to trigger a row addition.

**Comment by Beingbook** [comment]
I think it will conflict with my PR.

**Comment by flovilmart** [comment]
It's been released part of the header! Please update to the latest version!
