### ISSUE TITLE
Dashboard shutdown?

### ISSUE THREAD

**Issue by carlosmorcerf** [ParsePlatform/parse-dashboard#455]
On 27 January 2017 the Parse Dashboard will also be turned off?

**Comment by Zertz** [comment]
The hosted Parse service is shutting down, but you can keep running the open-source `parse-server` and `parse-dashboard` on your own infrastructure.

**Comment by hramos** [comment]
@Zertz is correct. Closing this as this is not a `parse-dashboard` issue.
