### ISSUE TITLE
Parse Export Data backup is not received 

### ISSUE THREAD

**Issue by arpandesai** [ParsePlatform/parse-dashboard#462]
Hell Parse Team, 

I have tried taking backups multiple time, data backup email or Zip is not received. 

Thanks, 
Arpan 

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Steps to reproduce

Settings - > Export app data
Your app is being exported! We'll email you a link when it's ready.

I have initiated multiple export request, none of them are succeeding. We haven't received an email yet. 

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by flovilmart** [comment]
As this is a problem on parse.com, please use http://parse.com/help for support
