### ISSUE TITLE
Actual User Login in Dashboard

### ISSUE THREAD

**Issue by Abderezai** [ParsePlatform/parse-dashboard#466]
Sorry if this is duplicate, I couldn't find exact description of the issue I am having.
I want to be able to modify data via the dashboard, but the ACL permissions would not allow me, as the dashboard does not allow for login authentication.

The user setting right now does not pass the user to the api requests made by dashboard.

**Comment by bohemima** [comment]
The dashboard should use the masterkey for all requests, so it shouldn't be a problem. Are you seeing any errors?

**Comment by Abderezai** [comment]
I see. I am not seeing any errors. I was checking in a beforeSave if the request.user was set, but now looking at it I shouldn't be doing that. I didn't know master key can be set from a client. Good to know :D thanks
