### ISSUE TITLE
404, cannot POST/serverInfo

### ISSUE THREAD

**Issue by alexbruce** [ParsePlatform/parse-dashboard#469]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [ ] You're running version >=2.1.4 of Parse Server.
- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Logs/Trace

Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

As I open up my parse dashboard I am greeted with a 404 error and when I dig a bit deeper, I come across the error stating that "cannot POST/serverInfo" and the url is https://www.MY_DOMAIN.com/parse/serverInfo.
Is there a solution to this?

**Comment by bohemima** [comment]
Is parse-server reachable at that domain and path? What happens if you open that URL directly in your browser?

**Comment by alexbruce** [comment]
As I type in www.my_domain.com/parse/serverInfo the screen prints "Cannot get /serverInfo". Other than that, I can access my dashboard and it shows my app with the error of "Server not reachable: server version too low". I have tried looking it up and spent many hours searching for an answer but so far I have not been successful.

**Comment by bohemima** [comment]
So, basically you set something up incorrect, please have a look at your config for parse-server and eventual other programs (do you proxy through apache, nginx, etc?)

Without knowing _how you_ have setup things everything here is just guesses.

**Comment by alexbruce** [comment]
I run my reverse proxy through nginx.

**Comment by alexbruce** [comment]
I run it with express and just wondering if I should put in some code or something inside my app.js file.

**Comment by NatanRolnik** [comment]
`/serverInfo` should be a GET
