### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by srinivas69** [ParsePlatform/parse-dashboard#471]
Hi,

When I'm trying to run the parse-dashboard with the following command I getting the unhandled error.

> parse-dashboard --appId yourAppId --masterKey yourMasterKey --serverURL "https://example.com/parse" --appName optionalName

Here is unhandled error that I have got.

> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: listen EADDRINUSE 0.0.0.0:4040
>     at Object.exports._errnoException (util.js:873:11)
>     at exports._exceptionWithHostPort (util.js:896:20)
>     at Server._listen2 (net.js:1250:14)
>     at listen (net.js:1286:10)
>     at net.js:1395:9
>     at nextTickCallbackWith3Args (node.js:453:9)
>     at process._tickCallback (node.js:359:17)
>     at Function.Module.runMain (module.js:443:11)
>     at startup (node.js:139:18)
>     at node.js:968:3
> 

Please let me know how to resolve it.

**Comment by bohemima** [comment]
"Error: listen EADDRINUSE 0.0.0.0:4040"

Something is already running on port 4040, course another port.

**Comment by srinivas69** [comment]
I have rebooted the server. Now it is working.
Some other user has told me to use the following command

`killall -9 node`
