### ISSUE TITLE
Image going to .bin File

### ISSUE THREAD

**Issue by rahb3rt** [ParsePlatform/parse-dashboard#477]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [YES ] You're running version >=2.1.4 of Parse Server.

- [YES ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

Just the basic parse-dashboard with a parse-server background

#### Issue

When uploading an image file from Swift, when checking my dashboard I see a .bin file not an image file. Is this a known issue? If so how do I go about fixing it?

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by dcdspace** [comment]
@rahb3rt Did you fix this? I am experiencing the exact same issue.

**Comment by rahb3rt** [comment]
@dcdspace yes, it turns out that thats how parse stores the file as bins, but if you output through a UI, Parse then interprets the file that it is holding. So like I am storing images in my DB, making a bit of an app like instagram copy. When they are in the DB they are .bin files, however, when I read them out, they become image files once again. I believe this is to compress the data. I could be wrong though

**Comment by benpackard** [comment]
@dcdspace @rahb3rt  If you are creating these files from a `PFFile`, specify the content type. I.e. instead of `self.init(data: data)` use `self.init(data: data, contentType: "image/jpeg")`
