### ISSUE TITLE
Background job is stuck on pending from long time.

### ISSUE THREAD

**Issue by Code-Crash** [ParsePlatform/parse-dashboard#485]
Hi Team,

We have our background job stuck on pending for the last 4 hours, we are completely blocked and request you to look into this issue urgently.

Thanks,
Pravin

**Comment by mbt-jeremy-r** [comment]
Not from the team, but I think you will need to provide the code of your background job and any possible logs for them to help you.

**Comment by Code-Crash** [comment]
This is happening for all the background job, not for a specific job, Please see the screenshot.

<img width="1276" alt="screen shot 2016-08-03 at 8 48 38 pm" src="https://cloud.githubusercontent.com/assets/5871757/17371009/edc44952-59bb-11e6-9b45-ecd97227f0d0.png">
