### ISSUE TITLE
Proposal: Form Based Authentication

### ISSUE THREAD

**Issue by JeremyPlease** [ParsePlatform/parse-dashboard#493]
The current basic auth implementation works well, but there are a few minor downsides:
- Not all browsers can save basic auth credentials.
- Login persistence can't be controlled (ie. stay logged in for 2 weeks).
- Basic auth username/password is passed as base64 encoded string (technically ok over https).
- Cancelling from browser basic auth just shows "You don't have any apps."

---
### Proposal:
1. Create a page similar to https://www.parse.com/login (stripped down to only have username/password inputs--[screenshot](https://cldup.com/uq9go3Wrm0.PNG)).
2. Redirect to to login page if not authenticated.
3. Verify session on `/parse-dashboard-config.json` route.
4. Continue to use `users` configuration.
5. Use [passport](https://github.com/jaredhanson/passport) and [passport-local](https://github.com/jaredhanson/passport-local) for authentication.
6. Update config loading to set passport configuration options.

---

Any suggestions, concerns, or objections?

**Comment by steven-supersolid** [comment]
A logout button would be useful too
