### ISSUE TITLE
Server not reachable: server version too low

### ISSUE THREAD

**Issue by thphuc** [ParsePlatform/parse-dashboard#50]
I am setting up dash-board on localhost (my PC).
I get the error: "Server not reachable: server version too low"
My parse-server version is 2.1.4

**Comment by drew-gross** [comment]
2.1.4 should be a high enough version. Can you open up your javascript console and check if you have failing network requests? Specifically, requests to `yourparseserver.com/parse/serverInfo` as these are the ones that contain the dashboard version.

**Comment by thphuc** [comment]
yourparseserver.com/parse/serverInfo -> Error 404 (not found)
I also checked, there is no "serverInfo" folder (or file) under my app folder.
Where to get this?

**Comment by thphuc** [comment]
OK. I figured it out. My fault!
I am using Parse server example and they are still using parse-server 2.1.2
But I got another issue with User table on dashboard. I have some users but the user table is empty. I will open new issue.
Thanks @drew-gross

**Comment by coryshaw** [comment]
For what it's worth, I was having the same issue, which was caused by the parse-dashboard-config.json serverUrl NOT containing a trailing /parse. adding the trailing /parse to my serverUrl brought it to life.
