### ISSUE TITLE
Getting 404 on login

### ISSUE THREAD

**Issue by tanmays** [ParsePlatform/parse-dashboard#500]
Just updated parse-server to `2.2.18` and parse-dashboard to `1.0.16` and now I get 404 when logging on to dashboard. Used to work fine in previous release. 

**My config**:

Parse Server and Parse Dashboard on the same server/port, both as express middleware on AWS EB and mLab

**index.js file**:

```
var ParseServer = require('parse-server').ParseServer;
var api = new ParseServer({
    // Parse Server settings
});

var app = express();

// Serve the Parse API on the /parse URL prefix
var mountPath = '/parse';
app.use(mountPath, api);

// Parse Server plays nicely with the rest of your web routes
app.get('/', function(req, res) {
  res.status(200).send('API is working');
});
var port = process.env.PORT || 8081;
app.listen(port, function() {
    console.log('parse-server-example running on port ' + port + '.');
});

var ParseDashboard = require('parse-dashboard');
var config =  {
  "allowInsecureHTTP": true,
  "apps": [
    {
      "serverURL": "https://api.xxx.com/parse",
      "appId": "xxx",
      "masterKey": "xxx",
      "appName": "xxx"
    }
  ],"users": [
    {
      "user":"xxx",
      "pass":"xxx"
    }
  ]
};

var dashboard = new ParseDashboard(config, config.allowInsecureHTTP);

// make the Parse Dashboard available at /dashboard
app.use('/dashboard', dashboard);
```

**Comment by Gameleon12** [comment]
Same issue here. Whenever running parse-dashboard `1.0.16` on a express server it gives the 404 error when trying to load the login page. It doesn't matter which version of parse-server it is linked to.

For now I reversed to version `1.0.15` with parse-server `2.2.18`, which seems to work fine for now.

**Comment by ababich** [comment]
This is closely related to #486 
Looks like lack of updated documentation or test coverage for this piece allows regressions

**Comment by drew-gross** [comment]
Sorry about that. I will revert the change.

**Comment by AstonBraham** [comment]
Same here....
I even tried to revert back to the previous releases...
The 404 erro page still persists

**Comment by ababich** [comment]
@AstonBraham 1.0.15 works just fine, I can confirm that - make sure your setup was really reverted back to 1.0.15

@drew-gross will it be 1.0.17 or how it will appear in npm?

**Comment by joeyslack** [comment]
I can confirm 1.0.15 works. 

1.0.16 does not, nor does 1.0.17 (in local dev)

**Comment by tanmays** [comment]
Same what @joeyslack says. Both `1.0.16` and `1.0.17` result in 404. Only `1.0.15` works. Which means either #465 or #487 are causing it. @drew-gross

**Comment by drew-gross** [comment]
I haven't been able to reproduce this. Please move discussion to #503.

**Comment by rdiaz82** [comment]
Hi, 
I just installed the dashboard, and firstly I got the site warning about the security access, and after setting the unsecure access I'm getting **Cannot GET /login** I'm using express and the following configuration:
`var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var ParseDashboard = require('parse-dashboard');

// Configure the Parse API
var api = new ParseServer({
  databaseURI: 'xxxxxxxxx',
  cloud: __dirname + '/cloud/main.js',
  appId: 'xxxxxxxxxx',
  masterKey: 'xxxxxxxxxx',
  serverURL: 'http://localhost:9998/parse'
});

var dashboard = new ParseDashboard({
  "apps": [
    {
      "serverURL": "http://localhost:9998/parse",
      "appId": "xxxxxxxxxx",
      "masterKey": "xxxxxxxxxxxxx",
      "appName": "xxxxxxxxxx"
    }
  ],
  "users": [
    {
      "user":"user1",
      "pass":"pass"
    }
  ]
}, true);
var app = express();

// Serve the Parse API on the /parse URL prefix
app.use('/parse', api);
app.use('/static', express.static('public'));
app.use('/dashboard',dashboard)
var httpServer = require('http').createServer(app);
httpServer.listen(9998);`

Any ideas on this?
Thanks in advance!!

**Comment by flovilmart** [comment]
@rdiaz82 see #604
