### ISSUE TITLE
Dashboard v1.0.16/17 broken.

### ISSUE THREAD

**Issue by majidhassan** [ParsePlatform/parse-dashboard#503]
I'm using parse-server and parse-dashboard on a DigitalOcean machine. The dashboard doesn't work with versions 1.0.16 and 1.0.17, but works fine, when I install parse-dashboard version 1.0.15, though. 

1.0.16: does not seem to load anything, I get a blank page in my browser.
1.0.17: gives me a 404.

My setup:
parse-server: 2.2.18
host: ubuntu 14.0.4 on DigitalOcean
running with pm2

**Comment by mooshee** [comment]
+1 Reverting to parse-dashboard 1.0.15 resolves the issue.

**Comment by andrew8712** [comment]
> 1.0.17: gives me a 404.

Same thing here

**Comment by altagir** [comment]
same thing, just find out the fix by seeing i did updated the dashboard
couldn't find any logs apart from mix of 404 - 408 

seemed to block after
"GET /dashboard/bundles/img/cf0a48bbd61302f119a4576be8e01ed9.png HTTP/1.1" 304 0 ...
24.114.89.46 - - [22/Aug/2016:08:58:44 -0400] "-" 408 0 "-" "-"
24.114.89.46 - - [22/Aug/2016:08:58:44 -0400] "-" 408 0 "-" "-"

**Comment by majidhassan** [comment]
@altagir I also got multiple 304 errors in my nginx access logs.

**Comment by sebsylvester** [comment]
Also getting a 404 (awesome design btw). 
JavaScript bundle is loaded without any error messages in the console.

**Comment by drew-gross** [comment]
I haven't been able to reproduce this. The most suspicious looking change I can see is here: https://github.com/ParsePlatform/parse-dashboard/commit/5b301f300f608470feaab1407ac2c4a36df01573#diff-0e8cf7d2b8786ce6d1cc52a9bb1b5313R12 Can one of you try reverting that change and see if that fixes your issue?

**Comment by kenwen** [comment]
I'm getting the quite awesome 404 page too, latest version of parse server and dashboard, running on google app engine

**Comment by yingliangzhang** [comment]
Same here, +1 for reverting back to `1.0.15`.

**Comment by afturner** [comment]
I am also getting that, and my mount path for the Parse Server is also not working, +1 reverting to 1.0.15

**Comment by johnnydimas** [comment]
I am also having this same issue. I am running the parse-dashboard as express middleware on the same server as my parse-server on aws.

However, when I clone the repo and run the dashboard standalone, it does run fine.

@drew-gross I tried to revert the history.js change you mentioned above, rebuild the dashboard, and put it into my node server, but it did not clear up the problem. I am still getting 404 errors.

**Comment by drew-gross** [comment]
Interesting. I'm glad you mentioned that the issue doesn't occur when you clone the dashboard, as I never run it any other way.

**Comment by sjmn** [comment]
Still getting ...bundles/dashboard.bundle.js...  "Failed to load resource: the server responded with a status of 404 (Not Found)" even after reverting to 1.0.15 .

**Comment by kenwen** [comment]
From what I've experienced parse server needs to roll back as well

**Comment by sjmn** [comment]
@kenwen how far back?

**Comment by kenwen** [comment]
@sjmn I rolled back to 2.2.17, that was last version working for me

**Comment by majidhassan** [comment]
@sjmn @kenwen I have 2.2.18 running 1.0.15 without any problems.

**Comment by flovilmart** [comment]
Finally some good news!

**Comment by sjmn** [comment]
@majidhassan Can you share what you perceive to be your solution?  Seems you started this thread out with trouble and most recently are reporting success.

**Comment by drew-gross** [comment]
I was able to reproduce the issue by installing from npm. I've pushed 1.0.18 which fixes this issue for me, please let me know if 1.0.18 fixes your problem.

**Comment by majidhassan** [comment]
@drew-gross dashboard 1.0.18 works for me on server 2.0.18.

**Comment by johnnydimas** [comment]
@drew-gross worked great for me too! Running the latest dashboard and server now. Thanks!

**Comment by tanmays** [comment]
1.0.18 works! Thanks Drew!

**Comment by sjmn** [comment]
thanks @drew-gross - latest versions of server and dashboard working for me also.

**Comment by altagir** [comment]
same here .. thanks. I guess one can close the issue

**Comment by flovilmart** [comment]
Thanks everyone!
