### ISSUE TITLE
Push Notifications Not Working On Parse.com

### ISSUE THREAD

**Issue by mabarakat** [ParsePlatform/parse-dashboard#504]
Push notifications is not working on the original site. when i try to create a push notifications on the original dashboard it says no devices exists. although my installation table has over 910k objects. also when i try the Beta dashboard it these colored circles keeps floating forever and i cannot modify any audiences. as the screen is not opening.

This issue is on Parse.com not on my own installation.

**Comment by flovilmart** [comment]
please report your issues to https://parse.com/help for issues with parse.com
