### ISSUE TITLE
Cannot deploy my app to App Engine

### ISSUE THREAD

**Issue by otymartin** [ParsePlatform/parse-dashboard#51]
I followed all the steps to get the dashboard up and running, it works.

However, its created a problem for me. My app is currently hosted on Google App Engine.

I installed the dashboard files within the same folder where I have my parse server.
Parse Server Directory: `dev/appName-server/"server files, cloud code, app.yaml e.t.c`
Dashboard Directory: `dev/appname-server/parse-dashboard`

When I run my command to deploy my server code `gcloud preview app deploy` I get this problem
```terminal
Beginning deployment...

ERROR: (gcloud.preview.app.deploy) There is a Dockerfile in the current directory, and the runtime field in /Users/myUserName/Documents/dev/appName-server/app.yaml is currently set to [runtime: nodejs]. To use your Dockerfile to build a custom runtime, set the runtime field in /Users/myUserName/Documents/dev/appName-server/app.yaml to [runtime: custom]. To continue using the [nodejs] runtime, please omit the Dockerfile from this directory. 
```
Even After removing the DockerFile in my `dev/appName-server/` directory, my deployment gets stuck at 
```terminal
Verifying that Managed VMs are enabled and ready.
Provisioning remote build service.
Copying certificates for secure access. You may be prompted to create an SSH keypair.
Building and pushing image for module [default]
--- DOCKER BUILD OUTPUT ---
```

**Comment by drew-gross** [comment]
This issue seems to be pretty specific to google app engine. As a guess, I would say to remove the preinstall script from `package.json` (it's there to prevent people from accidentally pushing their master keys to GitHub, but it's pretty hacky)

If that doesn't work, I probably won't be able to help you.

**Comment by flovilmart** [comment]
If you have a Dockerfile, you should put the runtime in app.yaml to custom

Also, I would recommend you deploy 2 modules instead of 1 with a routing.yaml to run api and dashboard to the right modules.

**Comment by otymartin** [comment]
@drew-gross I kinda new to terminal. What command can i use to uninstall the dashboard along with all its files? I assume the parse-dashboard is the one creating the docker file.

@flovilmart Im not versed enough with server side/terminal to follow your instructions to be honest. for now I'd rather just uninstall.

**Comment by drew-gross** [comment]
Just delete the `parse-dashboard` folder.

**Comment by otymartin** [comment]
@drew-gross thanks drew. Do you recognize these files? Im assuming parse-dashboard created them. i want to know whether to delete them aswell
<img width="580" alt="screen shot 2016-03-05 at 1 46 37 am" src="https://cloud.githubusercontent.com/assets/2222881/13546197/2b553e08-e274-11e5-833f-455528298ce6.png">
<img width="394" alt="screen shot 2016-03-05 at 1 47 25 am" src="https://cloud.githubusercontent.com/assets/2222881/13546200/3c0502b0-e274-11e5-86b7-73c795c0d9e7.png">

**Comment by drew-gross** [comment]
Parse Dashboard does not create any files outside it's own folder.

**Comment by flovilmart** [comment]
These are the Google app engine deployment temporary folders

**Comment by otymartin** [comment]
@drew-gross @flovilmart thanks. Will try reinstalling in separate folder

**Comment by drew-gross** [comment]
You could replace the `npm run dashboard` step with a two step process:

```
webpack --config build.config.js
node Parse-Dashboard/index.js
```
