### ISSUE TITLE
User collection empty

### ISSUE THREAD

**Issue by thphuc** [ParsePlatform/parse-dashboard#52]
As title said, the User collection is empty.
In mongodb, there are around 10 users.
I guess this issue is similar to [#825](https://github.com/ParsePlatform/parse-server/issues/825).
(When I use Android to request user list, the result is empty. But if I request for ONE (1) user, it works)

**Comment by drew-gross** [comment]
This sounds like it might be a Parse Server issue. Can you open the Javascript console and show the request and the response to the request? Make sure to redact your master key.

**Comment by thphuc** [comment]
I got below error in Console:

19743Warning: AppsSelector is accessing getDOMNode or findDOMNode inside its render(). render() should be a pure function of props and state. It should never access something that requires stale data from the previous render, such as refs. Move this logic to componentDidMount and componentDidUpdate instead.
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by drew-gross** [comment]
500 (Internal Server Error) is definitely a problem with Parse Server. Can you open an issue there? Please include an example CURL request and the state of your database (you can get the cURL from Chrome debugger network tab by right clicking on a request for _User and selecting copy as cURL, again make sure to redact your Master Key) https://github.com/ParsePlatform/parse-server/issues/
