### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by kilabyte** [ParsePlatform/parse-dashboard#53]
Got everything setup now including one app. I get this error underneath the app that it can't connect to the parse-server on the localhost. If i replace the URL with the parse API url it works great! The parse-server is running on the localhost and apps can read and write from it. Any thoughts?

![screen shot 2016-03-04 at 11 16 40 pm](https://cloud.githubusercontent.com/assets/487948/13546324/2ee0e9a6-e25f-11e5-8dc3-81505a62d1af.png)

**Comment by drew-gross** [comment]
Did you include your parse mount point in the server URL?

**Comment by kilabyte** [comment]
Yup. I can even go to that url and i get the unauthorized json string

**Comment by kilabyte** [comment]
I got it working pointing to a heroku instance... hmmm let me give it a good look over

**Comment by drew-gross** [comment]
That sounds strange. Can you check in your browser debugger what the response is to the /serverInfo endpoint of your Parse Server?

**Comment by kilabyte** [comment]
So if i put in an external url i.e. not localhost it works perfect. as soon as i put in localhost with the mount point it says it can't be found. If i run /serverInfo on the parse server i get "cannot find variable serverInfo". or typed into the address bar i get "cannot GET /serverInfo"

**Comment by drew-gross** [comment]
What version is your Parse Server?

**Comment by kilabyte** [comment]
2.1.4

**Comment by drew-gross** [comment]
If you execute this cURL on your localhost, what is the response:

**Comment by kilabyte** [comment]
Same.
![screen shot 2016-03-05 at 12 48 13 am](https://cloud.githubusercontent.com/assets/487948/13546741/f5547f10-e26b-11e5-9793-00633971a80d.png)

**Comment by drew-gross** [comment]
OK, sounds like a bug in the server. Can you post the contents of your server's `package.json` file?

**Comment by kilabyte** [comment]
[package.json.zip](https://github.com/ParsePlatform/parse-dashboard/files/159752/package.json.zip)

**Comment by drew-gross** [comment]
You need to include the keys in your cURL. Please use the exact curl I sent you including the method and headers, but replace the mount, appId and masterKey with your mount, appId and masterKey (make sure not to include master key when you show me the results)

**Comment by kilabyte** [comment]
![screen shot 2016-03-05 at 1 02 15 am](https://cloud.githubusercontent.com/assets/487948/13546807/19f81050-e26e-11e5-9e80-00375c7fa4cc.png)

**Comment by drew-gross** [comment]
you still need the /serverInfo at the end of your URL for the curl. So if your mount point is `anni` use `http://localhost:1337/anni/serverInfo`

Can you also paste the contents of your `parse-dashboard-config.json` file, with the master keys removed?

**Comment by kilabyte** [comment]
AH sorry bout that its getting late haha.
![screen shot 2016-03-05 at 1 08 47 am](https://cloud.githubusercontent.com/assets/487948/13546829/e91702ec-e26e-11e5-989e-365190f79256.png)

![screen shot 2016-03-05 at 1 07 36 am](https://cloud.githubusercontent.com/assets/487948/13546821/b8d3b36e-e26e-11e5-92b4-4e4a89f3bfb6.png)

**Comment by drew-gross** [comment]
Your `parse-dashboard-config.json` file has `http://parse.kilabytecloud.com:1337/anni` as your serverURL, but you say it's your `localhost` server that the dashboard can't connect to. Are you sure your config file is correct?

That server response is correct, so the problem is not with the server.

**Comment by kilabyte** [comment]
ya sorry thats my current config and its working i'll redo it with the local host my bad... :/

**Comment by kilabyte** [comment]
![screen shot 2016-03-05 at 1 15 54 am](https://cloud.githubusercontent.com/assets/487948/13546858/e300024a-e26f-11e5-9369-36bd843e8000.png)
![screen shot 2016-03-05 at 1 15 42 am](https://cloud.githubusercontent.com/assets/487948/13546859/e3234e9e-e26f-11e5-842d-b2b158d934a8.png)

**Comment by drew-gross** [comment]
That looks like it should work. Can you try removing the users, javascript key, and rest key from your config, and see if that changes anything?

**Comment by kilabyte** [comment]
nope still unreachable with that setup
![screen shot 2016-03-05 at 1 22 33 am](https://cloud.githubusercontent.com/assets/487948/13546890/c0795f40-e270-11e5-96e4-034d8d2160ce.png)

**Comment by drew-gross** [comment]
OK, I guess it's time to dig into the code. Can you open `dashboard/Dashboard.js` and on line 145 replace `'unable to connect to server'` with `JSON.stringify(error)` and then refresh the dashboard and tell me what the new error is?

**Comment by kilabyte** [comment]
Server not reachable: {"code":100,"message":"XMLHttpRequest failed: \"Unable to connect to the Parse API\""}

**Comment by drew-gross** [comment]
That is what I would expect if your Parse Server was not running, but it must be running if your cURL succeeded. What URL are you accessing the dashboard on? `localhost:4040`? You don't have anything in your `hosts` file that lets you visit other domains but still have them be `localhost`, do you? Also, can you open the Chrome Debugger, and on the Network tab, find the failing `/serverInfo` request, and screenshot the info for that request? It should look something like this:

![image](https://cloud.githubusercontent.com/assets/558242/13546958/fd95d94c-e272-11e5-8824-6d33f0923471.png)

minus the master key of course.

**Comment by kilabyte** [comment]
Well i won't be able to make a local host request from my browser as my computer and VPS reside on different networks and i can't vpn to my vps

**Comment by drew-gross** [comment]
I think I see your issue. You have the dashboard and server running on the same VPS, and you are loading the dashboard from your VPS via some method that give your VPS a URL that you can access from your browser. But since your `serverURL` is set to `localhost` in your config file, your browser then tries to access `localhost` which goes to the `localhost` of the machine your browser is running on, not the `localhost` of the machine your Parse Server is running on.

**Comment by kilabyte** [comment]
right but the config file for the parse-server is set to localhost. and that would be correct since the file resides on the VPS its referencing itself. if parse-dash is also running on the same VPS and its config has localhost in it then it should still reference the VPS machine and not my personal local machine no diff then how parse-server is accessing localhost? or have i just lost all hope at this early morning hour haha

**Comment by drew-gross** [comment]
The `npm run dashboard` command starts a small express app that sends the config file to the browser (and validates your username, password, and https). Once the browser has the config file, it sends requests to the serverURL(s) in the config file. If that URL is `localhost`, it will send requests to `localhost` which is the `localhost` of the machine the browser is running on.

**Comment by kilabyte** [comment]
Ah gotcha. thanks for clearing that up and sticking through it haha :+1:  :+1:

**Comment by drew-gross** [comment]
No worries! I'm glad people are using the dashboard. I'm surprised at the number of people trying to deploy the dashboard to heroku or other remote services, I personally quite prefer the local experience. I'm going to open an issue to improve teh heroku experience, hopefully someone will pick it up :)

**Comment by kilabyte** [comment]
That would be great! Im basically building both one instance on heroku and one on the VPS while i evaluate which rabbit hole to go down.

**Comment by androidexceptioncom** [comment]
Im with the same problem, i have a VPS with the dashboard and parse server, i changed my config.json and my index.html removing the localhost with my server ip but the problem persist :C whats the solution of this problem?
