### ISSUE TITLE
Parse asked for password when deleting apps but keeps saying wrong. Same password used as when logging in. 

### ISSUE THREAD

**Issue by konradmurch** [ParsePlatform/parse-dashboard#530]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [ ] You're running version >=1.0.18 of Parse Dashboard.
- [ ] You're running version >=2.2.18 of Parse Server.
- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Logs/Trace

Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by steven-supersolid** [comment]
I can't see any option to do delete an app on self-hosted parse-dashboard - could you clarify the UI flow or whether you are trying to do this on parse.com? If the issue is on parse.com then please open a support ticket on that site as it is not possible to fix here.
