### ISSUE TITLE
Where do I get an App ID and a Master Key? 

### ISSUE THREAD

**Issue by msutyak** [ParsePlatform/parse-dashboard#536]
Where do I get an App ID and a Master Key for use with Parse Dashboard.  Are these required?

**Comment by ovidiubute** [comment]
@msutyak you need to choose your own App ID and Master Key. The App ID is basically the name of your application (e.g. 'MyParseApp') and the Master Key is a random string that you should not disclose with anyone (treat it as a password for your Parse backend).

**Comment by steven-supersolid** [comment]
Additionally, if you are using an existing parse application you can get these from the parse.com dashboard by going to Settings -> Keys (https://parse.com/apps/MY-APP-NAME/edit#keys)

**Comment by SerialForBreakfast** [comment]
If you can ssh into your parse server, you can find the settings in your Parse setup.js.
just "cd apps/parse/htdocs" to get into the directory and "nano server.js" to read the file
You can find you applicationID and MasterKey for Parse there.

**Comment by thongbk83** [comment]
https://parse.com/ dies any updates for app key and master key ?

**Comment by hamzabinamin** [comment]
@msutyak @ovidiubute  @SerialForBreakfast @thongbk83 @steven-supersolid 
Hey guys since parse.com died, how can I find the master key? Any help?

**Comment by steven-supersolid** [comment]
The master key is defined in your server. You must have appId and masterKey in order to start the server so you should use the values you have set up there.

**Comment by claireebilski** [comment]
I don't have a apps/parse/htdocs directory and in server.js I just see app ID and master key for parse-server, not parse-dashboard... anyone have an idea of where to get these credentials for parse-dashboard?

**Comment by TomWFox** [comment]
Hi,

The `appId` and `masterKey` in your server.js files are the only ones you need. When you launch your Parse Dashboard these are the keys you use to authenticate with your Parse Server.

Please see the [getting started section](https://github.com/parse-community/parse-dashboard#getting-started) for the Parse Dashboard for more info.

**Comment by JorisGanne** [comment]
I have the same problem...I have already an application and tried to find the app credentials by "cd apps/parse/htdocs/" but get the error: -bash: cd: apps/parse/htdocs/: No such file or directory. Can someone help me?

**Comment by claireebilski** [comment]
I had to cd into stack, then parse-dashboard, and run vi config.json to find the appId and masterkey along with the user credentials. 

If you want to edit the user credentials you have to use the command :w! sudo tee % to save your edits to the file and override the read only permissions if the file! 

Hope this helps.

**Comment by JorisGanne** [comment]
Thank you! It has helped me a lot!

**Comment by b4ssey** [comment]
OMG! I've seen what I've been looking so dearly for. Thank you

**Comment by aakash-gavle** [comment]
how can I get master key ,appid, and other ids .. I'm using windows os and I'm stuck on this problem from the last 2 days pls help me.
>

**Comment by b4ssey** [comment]
@aakash-gavle Type cd stack/parse-dashboard/ .Then vi config.json

**Comment by aakash-gavle** [comment]
Thankyou  so much b4ssey

**Comment by gagansarwara** [comment]
> @aakash-gavle Type cd stack/parse-dashboard/ .Then vi config.json

Thank you sooo much

**Comment by BFK-78** [comment]
Thank you All

**Comment by mtrezza** [comment]
It's interesting that this old thread about a basic topic is still relevant today. Does anyone have a suggestion what we could improve in the docs to address this?
