### ISSUE TITLE
Where to find Parse Dashboard 1.0.18?

### ISSUE THREAD

**Issue by funnel20** [ParsePlatform/parse-dashboard#541]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=1.0.18 of Parse Dashboard.

- [X] You're running version >=2.2.18 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
I'm using Parse at Nodechef.com, where Parse Dashboard is 1.0.15.
Your question above suggests that there is already a version 1.0.18. Where to find this?

#### Steps to reproduce

1. Visite the Releases at https://github.com/ParsePlatform/parse-dashboard/releases 
2. The most recent version is 1.0.11.
3. Where is 1.0.18? Or 1.0.15 that runs at Nodechef.com?

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by markmssd** [comment]
https://www.npmjs.com/package/parse-dashboard there you go.
You can install it with ```npm install parse-dashboard```
