### ISSUE TITLE
Support for scheduling a Push Note, even with local time zone enabled

### ISSUE THREAD

**Issue by funnel20** [ParsePlatform/parse-dashboard#542]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=1.0.18 of Parse Dashboard.

- [X] You're running version >=2.2.18 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
I'm using Parse at Nodechef.com, where Parse Dashboard is 1.0.15 and Parse Server 2.2.19.
At Parse.com it's possible to schedule a Push Note, even with local time zone enabled.
Parse Dashboard 1.0.15 doesn't allow these options.
Will these be implemented?

#### Steps to reproduce
1. Open Pash Dashboard
2. Select Push
3. Select Send New Push
4. Use Everyone as audience and type a message
5. At the preview 3 values for Delivery are shown (Time, Time Zone and Expiration), but I don't see a way to change them.

**Comment by gateway** [comment]
Currently based upon this documentation https://github.com/ParsePlatform/parse-server/wiki/Push its not currently supported.  Check out this blog for a potential way https://medium.com/@tiffany.ricks/parse-server-scheduled-push-notifications-hack-2ae873995b5b#.bmwgyikjt  ..

Also with Redis enabled with https://github.com/Automattic/kue to push jobs to and have them execute a push job based upon time value.

We have an admin server that is separate from parse where we can input ads, then on that server we run a cronjob every hour to see if any ad's need to be displayed and use the rest api to push to a channel that the users are subscribed to.

Not really all in parse but their are ways to do this.

**Comment by funnel20** [comment]
However, this issue was regarding scheduling of a push note, even to user's time zone.
By using the iOS and JS SDKs I was able to do this, so issue can be closed.

**Comment by gateway** [comment]
Check out https://clevertap.com/parse-migration/ they have the ability to push all your installation data into their system, they also have parse modules that do not use parse push, thus not having to worry about how much the parse server can send out esp if you have a lot of users.  Using their module https://github.com/CleverTap/parse-migrate you can also send stuff our with cloud code.. this is just a fyi.. I think we will be going down this route soon..

**Comment by soniurvashi11** [comment]
@gateway I m planning to use scheduled push notifications for my android and IOS apps, which are using parse APK. How about using OneSignal as my pushadapter in parse-server? Can u guide me about it?
