### ISSUE TITLE
Downloads link is broken

### ISSUE THREAD

**Issue by lewellyn** [ParsePlatform/parse-dashboard#543]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [X] You're running version >=1.0.18 of Parse Dashboard.
- [X] You're running version >=2.2.18 of Parse Server.
- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Environment Setup
- Parse Server version 2.2.21
- Parse Dashboard version 1.0.18
#### Steps to reproduce
- Log into Dashboard.
- Click "Downloads" button in lower left of browser window.
- Get a 404 rather than anything relevant to "Downloads".

**Comment by NatanRolnik** [comment]
Fixed in the current version
