### ISSUE TITLE
Any way to restore deleted Installations on parse.com?

### ISSUE THREAD

**Issue by fisch0920** [ParsePlatform/parse-dashboard#547]
- [x] You're running version >=1.0.18 of Parse Dashboard.
  Original hosted version of dashboard.parse.com
- [x] You're running version >=2.2.18 of Parse Server.
- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

NOTE: this is for the original hosted version of parse.com, not the self-hosted version.

We accidentally deleted thousands of Installations from one of our apps on dashboard.parse.com.  Is there any way to contact official Parse support at this point or any option I'm missing to restore a backup of these files (we don't have any backups locally).

I realize this question may be better suited to stackoverflow, but as this is really time-sensitive and this community is full or Parse dashboard experts, we figured it couldn't hurt to ask.

We'd appreciate any help you could give.  Thanks!

**Comment by steven-supersolid** [comment]
Hi, sorry if this is coming late but your best bet is to go to http://parse.com/help and find the 'contact us' link to open a bug report. AFAIK Parse has never kept backups so you may be out of luck.

If you have not migrated your database yet then you could try a provider like mLab or Mongo Atlas that provide a auto backup facilities.

**Comment by NatanRolnik** [comment]
Closing as not related to Parse Dashboard. Hope you figured it out.
