### ISSUE TITLE
"Export data" page not doing anything; stuck as "Waiting to begin"

### ISSUE THREAD

**Issue by amyboyd** [ParsePlatform/parse-dashboard#549]
As seen in this screenshot below, I've clicked the button that should start a data export, but the page has stuck at "Waiting to begin". I've waited and tried refreshing the page, but it's still not doing anything.

![image](https://cloud.githubusercontent.com/assets/398210/19044205/26da0552-898b-11e6-8114-97200b67ad58.png)

I've used this page successfully in the past, but it no longer works.

**Comment by jimcamut** [comment]
Same issue with our dashboard. I'm going to submit a ticket to Facebook/Parse.
