### ISSUE TITLE
Parse for people without a parse account?

### ISSUE THREAD

**Issue by TG908** [ParsePlatform/parse-dashboard#55]
Will it ever be possible for people that don't have a parse account to use parse dashboard or parse server?

**Comment by flovilmart** [comment]
This is completely possible! You don't need a parse account at all to start using either of those.

**Comment by TG908** [comment]
I just wasnt shure where i would get these from:
`{
  "apps": [
    {
      "serverURL": "http://localhost:1337/parse",
      "appId": "myAppId",
      "masterKey": "myMasterKey",
      "appName": "MyApp"
    }
  ]
}`

**Comment by flovilmart** [comment]
This is the configuration for parse-dashboard.
You can set your appId and masterKey to anything you want, and your appName too.

Once you set that on the dashboard, start a parse-server following the documentation with the according keys.

Just make sure you keep your master key private, and not shared with anyone.

**Comment by TG908** [comment]
Thank you very much that'll do it!
