### ISSUE TITLE
Browser won't render class table with field that contains an object

### ISSUE THREAD

**Issue by seangeiger** [ParsePlatform/parse-dashboard#552]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [X] You're running version >=1.0.18 of Parse Dashboard.
- [X] You're running version >=2.2.18 of Parse Server.
- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Steps to reproduce

I have multiple classes which have a field that's an object.  They look like this:

```
    {
        "objectId": "example",
        "username": "example",
        "createdAt": "2016-05-26T02:07:34.545Z",
        "updatedAt": "2016-05-26T02:07:56.154Z",
        "publicKey": {
            "__type": "Bytes",
            "base64": "examplePublicKey"
        }
    },
```

When the Dashboard Browser tries to display all the rows for this class, it returns an error of 
`"Objects are not valid as a React child (found: object with keys {__type, base64})."`
and doesn't display any rows.  If I filter to rows with undefined publicKeys, they display as they should.

This is related to [Issue 539](https://github.com/ParsePlatform/parse-dashboard/issues/539) but happens in a different context.  The stack trace and error messages are very similar.

**Comment by hedegren** [comment]
Having the same issue, where one of the column contains match data in base64 format.

**Comment by jordanhaven** [comment]
Just submitted a PR for this: https://github.com/ParsePlatform/parse-dashboard/pull/623
