### ISSUE TITLE
All the records were deleted when clicking “-Row”, not only the selected ones

### ISSUE THREAD

**Issue by yuriy-peslyak** [ParsePlatform/parse-dashboard#553]
Hi Team,

We were trying to delete some of the records in our custom section "CustomLeague" under the “User” menu ("..-Production" app -> Core -> User -> CustomLeague). When selected the needed rows and clicked "-Row" button, which should delete only the selected rows, all the rows were deleted.
This was unexpected behaviour and we lost the data because of this.

Could you please advise if there is a way to restore this data?

Thank you!
  
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=1.0.18 of Parse Dashboard.

- [ ] You're running version >=2.2.18 of Parse Server.

- [+] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by yuriy-peslyak** [comment]
Any updates on this? Please advise, as we need to restore our data as soon as possible.

Thanks!

**Comment by steven-supersolid** [comment]
You're not going to be able to restore your data with parse dashboard, will have to use a database backup if you have one.

Could you confirm which version of the dashboard you were running when you experienced the issue and what UI flow you followed? e.g. how many rows did you select, were you filtering, was there a confirm dialog?

I can see no -Row button in the current UI. Just Edit -> Delete this row/Delete these rows, so you could be on an old version.

**Comment by yuriy-peslyak** [comment]
Hi Steven,

Thank you for your feedback! Please see the attached screenshot.
![4fbb80c450a10baffaa9e68aa4752fd64](https://cloud.githubusercontent.com/assets/22636764/19514704/374875bc-95fd-11e6-9ebe-209d6824a4ff.png)

**Comment by steven-supersolid** [comment]
Thanks for clarifying. That screenshot is from parse.com and is the 'old' dashboard.

This project is for the self-hosted dashboard so it's not possible to fix any issues with parse.com. You could try opening a ticket on parse.com but that site will be shut down in 3 months.

Please can you close this issue if the problem is with parse.com?

**Comment by yuriy-peslyak** [comment]
Yes, thanks for your help Steven!
