### ISSUE TITLE
Unnecessary one row added when "Add Row" button is clicked

### ISSUE THREAD

**Issue by kariskim** [ParsePlatform/parse-dashboard#554]
Hi , Teams !

When I click a "Add Row" button of Data Browser, one unnecessary row is added to table.
Is it a intentionally or a bug as it is ?  

![addrow_error](https://cloud.githubusercontent.com/assets/1067003/19443590/253a8d14-94c8-11e6-93c5-e61ee97f3186.png)

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [x] You're running version >=1.0.18 of Parse Dashboard.
- [x] You're running version >=2.2.18 of Parse Server.
- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Steps to reproduce

click "Add Row" Button
#### Logs/Trace

Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by johnnydimas** [comment]
It's not adding an extra row, it's a 30px bottom margin as a style applied to the newly added row. I assume it's a visual aid only, and it goes away once the row is added.

**Comment by kariskim** [comment]
Yeah, I know what you aim for. Thanks for explanation.!
