### ISSUE TITLE
Keep NPM version updated with small fixes?

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-dashboard#556]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ x] You're running version >=1.0.18 of Parse Dashboard.

- [ x] You're running version >=2.2.18 of Parse Server.

- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Heroku

Can we keep builds of the dashboard updated esp for people like us not using git to clone it and push it to local machines.  Heroku and other locations and the docs point out to use npm install but the current version is missing things like jobs, and other things.

**Comment by steven-supersolid** [comment]
1.0.19 has now been released with the latest changes.
