### ISSUE TITLE
Parse App explanation?

### ISSUE THREAD

**Issue by ZayLong** [ParsePlatform/parse-dashboard#559]
This is more of a question than an actual issue, I did some google searching but couldn't readily find an answer.

What exactly IS a Parse App? 

I came looking at parse server looking for an alternative to firebase, something to handle account creation and API endpoints for a mobile app. 

But whenever I hear App referenced in the context of parse it seems to be referring to something totally separate from an apk or ipa for android or iOS. 

So what is a parse app? 
Why would I make one for mobile instead of just making an actual native app

**Comment by deada92** [comment]
parse-server is the open source version of BaaS Parse.com. Its a backend api solution that powers any kind of apps. 

"Parse App" is only a term that was used when creating a new Project or "Parse App" in Parse.com. Now with parse-server you can use only one Parse App on a single parse-server instance. 

More information: 
https://parseplatform.github.io/docs/parse-server/guide/
https://github.com/ParsePlatform/parse-server/wiki
