### ISSUE TITLE
Can't open dashboard

### ISSUE THREAD

**Issue by nunu-e64** [ParsePlatform/parse-dashboard#563]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.18 of Parse Dashboard.

- [ ] You're running version >=2.2.18 of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Steps to reproduce
1. Access to dashboard.
2. Try to open Core page or Push page.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

Core: 
Request URL:https://parse.com/apps/outapplication/collections
Request Method:GET
Status Code:400 Bad Request

Push:
returns 500

#### Detail
http://ur0.link/zd2E

**Comment by flovilmart** [comment]
Can you try with http://api.parse.com.... instead of parse.com in your configuration?

**Comment by nunu-e64** [comment]
http://api.parse.com/ returned 404.
What do you mean?
We can access neither https://parse.com/apps/xxx/collections nor https://parse.com/apps/xxx/push_notifications.

Please read details. http://ur0.link/zd2E

**Comment by flovilmart** [comment]
So you're neither using parse-dashboard nor parse-server open source projects?

**Comment by nunu-e64** [comment]
Yes, we are still using Parse. (and planing to migrate and release apps on November or December.)
I'm sorry if I shouldn’t have asked about an old Parse dashboard here.

**Comment by flovilmart** [comment]
We don't support this here. You should reach out to http://parse.com/help.

Also, make sure to make your timeline as short as possible, the shutdown of parse.com is scheduled for January, don't expect to access/revive any data from that.

**Comment by nunu-e64** [comment]
I have already accessed https://parse.com/help, but could not find a contacting page.

**Comment by flovilmart** [comment]
There is a contact us link in the middle of the page, and before the video...

**Comment by nunu-e64** [comment]
(Yes, I have accessed here from the link.)
But now I'm trying Facebook bug reporting.
Thank you for your soon reply.
