### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by fson** [ParsePlatform/parse-dashboard#57]
It's fantastic that the source code for the dashboard has been made available to developers. But the current [license](https://github.com/ParsePlatform/parse-dashboard/blob/505d4a550f72e0c16e22ec9f136b36a7b5af3478/LICENSE) is not an [open source license](https://opensource.org/osd), because it doesn't allow distributing modifications of the software.

From the [introduction blog post](http://blog.parse.com/announcements/introducing-the-parse-server-dashboard/):
> We hope to see the Parse community take ownership of the Parse Dashboard and drive the creation of new features and distribution methods.

To enable these contributions from the community, please consider adding a permissive open source license, such as the BSD license that Parse Server is licensed with.

**Comment by ericlw** [comment]
It is very peculiar the current license doesn't specify anything about derivative works. With 64 forks as of time of writing, something to the effect of "with or without modification" would alleviate concerns.

**Comment by cristiursachi** [comment]
+1 for an open source license, such as the BSD license that Parse Server is licensed with.

**Comment by drew-gross** [comment]
We've updated the licence to make it clear that you can modify the dashboard and distribute it in custom integrations such as NodeChef's.

**Comment by fson** [comment]
@drew-gross Thanks for your response. However, this is still a custom license and not an OSI-approved open source license. It also only allows modifications for "own internal use" – I'm doubtful even open sourcing modified versions of the software is allowed.

Why not make the dashboard free and open source software like the other components of the Parse platform such as the Parse SDKs and [Parse Server](https://github.com/ParsePlatform/parse-server)? Of course it's up to Parse as the license holder to choose whether or not to open source this project, and you don't owe us an explanation, but still, I'm curious as to why this project isn't open like the those other projects?

If open source licensing the whole dashboard is impossible for some reason, would you consider at least licensing the reusable React components in this project (the [src/components](https://github.com/ParsePlatform/parse-dashboard/tree/7e26f5bb9b402750c35ab6d062aa6114e384c86c/src/components) folder) under a different, permissive open source license (e.g. BSD)? These great components are possibly the most valuable part of the codebase for the community and I'm sure they would be useful for many projects, including other open source tools, if available under an open source license.

**Comment by ericlw** [comment]
@fson let's go with the obvious answer to the "why": Parse Dashboard is the baby of a graphics designer on the UI/UX team, that wants more control over it than the open source community desires. They don't want anyone 'claiming' it without substantial visual modifications. Visual artists get like that.

I like your suggestions for compromise
