### ISSUE TITLE
Jobs are no longer displaying in Parse Dashboard after latest update

### ISSUE THREAD

**Issue by richarddwalsh** [ParsePlatform/parse-dashboard#583]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X] You're running version >=1.0.19 of Parse Dashboard.

- [X] You're running version >=2.2.24 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Mac OS X 10.12.1

#### Steps to reproduce
Start up dashboard from config:
parse-dashboard --config ~/parse-dashboard-config.json
The dashboard is now available at http://0.0.0.0:4040/

Browse to dashboard url  http://0.0.0.0:4040/
Click to Jobs, 
screen is blank

Dev tools output is:
POST http://localhost:1337/parse/cloud_code/jobs?per_page=50 403 (Forbidden)
POST http://localhost:1337/parse//apps/MITGA/cloud_code/jobs/data 403 (Forbidden)
POST http://localhost:1337/parse/releases/latest 403 (Forbidden)
POST http://localhost:1337/parse/cloud_code/jobs?per_page=50 403 (Forbidden)
POST http://localhost:1337/parse/cloud_code/jobs?per_page=50 403 (Forbidden)

#### Logs/Trace
Note: If you get a browser JS error please r
![screen shot 2016-11-10 at 2 33 18 pm](https://cloud.githubusercontent.com/assets/611232/20195194/b7530b12-a752-11e6-8d95-d42b749df81d.png)
<img width="1435" alt="screen shot 2016-11-10 at 2 33 18 pm 2" src="https://cloud.githubusercontent.com/assets/611232/20195193/b750661e-a752-11e6-94ff-0fcbcfae7b69.png">

un `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by richarddwalsh** [comment]
I've also noticed that I can't view config either.

**Comment by mario** [comment]
Try setting javascriptKey in the dashboard config.

**Comment by richarddwalsh** [comment]
I have set it:
`
{
      "serverURL": "http://localhost:1337/parse",
      "databaseURI": "mongodb://localhost:27017/mcara-dev",
      "appName": "MUTFA",
      "appId": "myAppId",
      "masterKey": "myMasterKey",
      "javascriptKey": "myJavascriptKey",
      "restAPIKey": "myRestApiKey",
      "clientKey": "myClientKey"
    }`

**Comment by anashalb** [comment]
I am facing the same issue.. Were you able to resolve it?

**Comment by richarddwalsh** [comment]
Nope I have not been able to resolve it yet. I think it may have something to do with the fact that it is triggering a POST method instead of GET??

**Comment by dstarke** [comment]
The request to get the job list is not being issued with the master key. See [JobStore.js line 33](https://github.com/ParsePlatform/parse-dashboard/blob/master/src/lib/stores/JobsStore.js#L33).

I think adding the `{useMasterKey:true}` option there should fix it.

I'm not sure why it works in some environments and not in others.

**Comment by dstarke** [comment]
Another way to resolve this is to remove the `javascriptKey` (and maybe also the `clientKey`) from your configuration. The job request then gets issued correctly. This is why it was working for me in some environments and not in others.

**Comment by NatanRolnik** [comment]
This was fixed in the latest release.
