### ISSUE TITLE
Is adding a default value to a scheme column theoretically possible?

### ISSUE THREAD

**Issue by SaifAlDilaimi** [ParsePlatform/parse-dashboard#586]
So I have a Use-Case where I have a DB-Scheme where some attributes need a default value.. To be specific I have a Rating object with bestRating, worstRating and ratedValue. bestRating & worstRating should have default values like 5.0 & 0.0.

Does anything speak against it? I know its possible with mongoose but is there a way to accomplish this with the dashboard or parse server? I'm not sure actually if its a dashboard or server related issue.. I would try to make first-pr if I know where to start...

**Comment by natanrolnik** [comment]
Yes @SaifAlDilaimi, you can check if the object is new in a `beforeSave` hook, by calling `request.object.isNew()`, and if so, you set the values you want if they don't exist.
