### ISSUE TITLE
Unable to export Analytics data

### ISSUE THREAD

**Issue by mustafa01ali** [ParsePlatform/parse-dashboard#589]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.19 of Parse Dashboard.

- [x] You're running version >=2.2.24 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Using dashboard on parse.com

#### Steps to reproduce
Login to dashboard
Analytics -> Explorer -> Chart/Table/JSON
Select any valid data range
Click Download

The CSV files are always empty. Since Parse will be shutting down soon, we need a way to export all the Analytics data. How can we do it?

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.
N/A

**Comment by flovilmart** [comment]
We don't provide support for parse.com. Please refer to http://parse.com/help
