### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by ldmtam** [ParsePlatform/parse-dashboard#59]
I download the zip file from github, then extract it and run "npm install" but i get this error. Can anyone help me out? Thanks in advance.

![untitled](https://cloud.githubusercontent.com/assets/8778071/13548495/5e427956-e324-11e5-970f-6e26f81fa35c.png)

**Comment by flovilmart** [comment]
You should clone the repository instead of downloading the zip!

**Comment by ldmtam** [comment]
But when i try to clone the project, i have another error. Please help me fix it. Thanks
![untitled](https://cloud.githubusercontent.com/assets/8778071/13548550/7e6c5ed0-e325-11e5-8c72-d696a70b5753.png)

**Comment by durunvo** [comment]
you need to setup your RSA key for github

try follow
https://help.github.com/articles/generating-an-ssh-key/

**Comment by ldmtam** [comment]
Thanks @flovilmart and @durunvo, I have cloned and run the repository successfully.
