### ISSUE TITLE
Global Config not returning parameters

### ISSUE THREAD

**Issue by mjonatd** [ParsePlatform/parse-dashboard#596]
When using the dashboard, under "Core | Config" , I am able to save global config variables.  However, when I go back to the dashboard, the config variables are not displaying due to a 403 unauthorized.  

I can, however, go use postman:  http://localhost:1337/parse/config and pass the masterkey/application id in the header and it displays all the configs I have added.

I have "fixed" it by changing the **ConfigStore.js**

  switch (action.type) {
    case ActionTypes.FETCH:
      return Parse._request(
        'GET',
        'config',
        { params: { [action.param]: Parse._encode(action.value) } },
        { useMasterKey: true }
      ).then(( attributes ) => {
          console.log(attributes);
        return Map({ lastFetch: new Date(), params: Map(attributes.params) });
      });

Is this the correct way of fixing it?  If not, what suggestions would you have?

Thanks!

**Comment by dvanwinkle** [comment]
Please check #575. It may include the fix that you are looking for. Very similar, but, I'm not sure if #575 needs the `params` that you pass in or not.

**Comment by NatanRolnik** [comment]
@mjonatd @dvanwinkle this issue was fixed in the latest release.
