### ISSUE TITLE
How to create Config in Core menu

### ISSUE THREAD

**Issue by durunvo** [ParsePlatform/parse-dashboard#60]
I'm just wonder if this project can also browse config in core menu as well as analytic or push menu?

**Comment by drew-gross** [comment]
Some additional work on Parse Server is needed before we can do Parse Config, but it shouldn't be too much effort. Push would need a medium amount of work on Parse Server for basic push. Analytics would need a lot of work.

**Comment by durunvo** [comment]
You say, for now, open source parse server and dashboard is not fully feature compare to parse.com?
correct me if i'm wrong

**Comment by drew-gross** [comment]
Yes, that is correct.
