### ISSUE TITLE
New login screen fails with useEncryptedPasswords

### ISSUE THREAD

**Issue by Muesly** [ParsePlatform/parse-dashboard#611]
I've upgraded to 1.0.21 and the new login screen, which appears fine, but come up with this page when entering in my details:

Error: Illegal arguments: undefined, string
   at Error (native)
   at Object.bcrypt.compareSync (/Users/tony/Code/Lost/parse-dashboard/node_modules/bcryptjs/dist/bcrypt.js:230:19)
   at /Users/tony/Code/Lost/parse-dashboard/node_modules/parse-dashboard/Parse-Dashboard/Authentication.js:91:65
   at Array.find (native)
   at Authentication.authenticate (/Users/tony/Code/Lost/parse-dashboard/node_modules/parse-dashboard/Parse-Dashboard/Authentication.js:88:21)
   at /Users/tony/Code/Lost/parse-dashboard/node_modules/parse-dashboard/Parse-Dashboard/Authentication.js:40:21
   at pass (/Users/tony/Code/Lost/parse-dashboard/node_modules/passport/lib/authenticator.js:347:9)
   at Authenticator.deserializeUser (/Users/tony/Code/Lost/parse-dashboard/node_modules/passport/lib/authenticator.js:352:5)
   at SessionStrategy.authenticate (/Users/tony/Code/Lost/parse-dashboard/node_modules/passport/lib/strategies/session.js:53:28)
   at attempt (/Users/tony/Code/Lost/parse-dashboard/node_modules/passport/lib/middleware/authenticate.js:348:16)

I have the setting "useEncryptedPasswords" : true in my config, and login worked in 1.0.19 with the same config.

Any ideas?

**Comment by sidan5** [comment]
Same here!

**Comment by jpm** [comment]
Same here. Setting the parse-dashboard package version to 1.0.19 fixes the problem.

**Comment by drizzt** [comment]
Nice unit tests ;)

**Comment by richard4339** [comment]
So Ubuntu only supports node 4.2.6, and parse-dashboard requires 4.3. I initially assumed it was related to this, but upgraded to the latest version and it still fails.

Rolling back to 1.0.19 since 1.0.20's form based login is clearly a breaking change.

**Comment by bdevore17** [comment]
Having same issue. Getting "Internal Server Error"

**Comment by dvanwinkle** [comment]
I'll look into this tomorrow morning. I wrote the original encrypted passwords part, but, haven't upgraded to the latest version with the login screen yet.

Thanks for reporting this @Muesly!

**Comment by dvanwinkle** [comment]
Ah, looks like @lsohn already fixed this in #609. It has been accepted and merged into master already.

This can be closed @flovilmart.

**Comment by richard4339** [comment]
Will there be a new release soon since this seems like a pretty major bug?

**Comment by jankcat** [comment]
Any ETA on this being put into a release?

**Comment by bdevore17** [comment]
Looks like @flovilmart just cut the release fixing this issue.

**Comment by flovilmart** [comment]
yes, available on NPM: https://www.npmjs.com/package/parse-dashboard
and docker: https://hub.docker.com/r/parseplatform/parse-dashboard/tags/

I appologize to the other maintainers for cutting the line of the PR flow 🙇

**Comment by hatpick** [comment]
It's still failing on 1.0.22
After I enter my credential, it says invalid username or password.
Removing useEncryptedPasswords solves the issue.

**Comment by mldb** [comment]
same here
