### ISSUE TITLE
Add Cloud Code Webhooks section

### ISSUE THREAD

**Issue by apersaud** [ParsePlatform/parse-dashboard#622]
Hi everyone,

As of Parse Server 2.2.19, Cloud Code Webhooks are supported in similar fashion as they were supported in the hosted Parse Dashboard. I have attached a picture below showing where this section is in the hosted Parse dashboard. Having a web interface to configure and debug webhooks is very useful to several developers that are not writing their cloud code functions and triggers in javascript. What would be the process of porting that feature over from the Parse.com dashboard to the open source version (without having to write it from scratch)?

Thanks

#### Environment Setup
* Running Parse-Dashboard 1.0.22
* Running Parse Server 2.2.19

#### Steps to reproduce
1 .Run the latest Parse Dashboard and register a webhook using the Parse Server REST API.
2. Go to the "Core" for the app, and notice the 'Webhooks' section is missing.

![screen shot 2017-01-02 at 8 30 31 am](https://cloud.githubusercontent.com/assets/127068/21592945/ec0f1998-d0c6-11e6-94fb-2bebd017dd0f.png)

**Comment by davimacedo** [comment]
I've written a PR to enable it 2 months ago:
https://github.com/ParsePlatform/parse-dashboard/pull/584

Still waiting approval or comments...

**Comment by otymartin** [comment]
@flovilmart Would be cool to have this in the dashboard

**Comment by NatanRolnik** [comment]
@apersaud @otymartin this is included in the last release.

**Comment by cantwait** [comment]
Hello @natanrolnik I just downloaded the latest version of dashboard and installed on Heroku... I don't see the webhooks option in the menu, would you please let me know if I'm missing some configuration? 

![selection_174](https://cloud.githubusercontent.com/assets/823966/24364562/c228d016-12d8-11e7-8aa2-c745a6854880.png)

**Comment by cantwait** [comment]
Hi @natanrolnik nevermind I noticed that by updating parse server the missing options become available... sorry.

**Comment by natanrolnik** [comment]
Good to know you figured it out!
