### ISSUE TITLE
App Settings is not showing in parse-dashboard

### ISSUE THREAD

**Issue by partikles** [ParsePlatform/parse-dashboard#629]
I can able to launch parse-dashboard with applications in my mac. 

1.Core (Available)
2.Push (Available)

**3.App Settings (Not Available)**

I have enabled email verification in parse server as below but still App Settings is not showing.

verifyUsersEmails: true,
    emailAdapter: {
        module: 'parse-server-simple-mailgun-adapter',
        options: {
            // The address that your emails come from
            fromAddress: 'name@myapp.com',
            // Your domain from mailgun.com
            domain: 'mg.myapp.com',
            // Your API key from mailgun.com
            apiKey: 'maigun_key'
        }
    }

**Comment by NatanRolnik** [comment]
That's correct, @partikles - as the settings are setup upon Parse Server initialization, the server is not able to change them on the fly. That's why it's not supported in the dashboard.
Maybe @davimacedo has any ideas?
