### ISSUE TITLE
Config 403 Unauthorized. Unable to read, can create

### ISSUE THREAD

**Issue by Lunke** [ParsePlatform/parse-dashboard#631]
Hey,
I have deployed Parse Dashboard to Heroku, and I can view and edit all the data in the browser section, but whenever I try to see the Config on the dashboard, I get error 403, Unauthorized. I can however create new parameters that will, if I check on Parse.com dashboard, be saved. 

I am using PARSE DASHBOARD 1.0.22.

**Comment by NatanRolnik** [comment]
This is a duplicate of #596

**Comment by NatanRolnik** [comment]
@Lunke this issue was fixed in the latest release.
