### ISSUE TITLE
Config properties are not visible?

### ISSUE THREAD

**Issue by Foddy** [ParsePlatform/parse-dashboard#634]
Hi,

I just figured out that when I set some config properties with the latest dashboard version, logout and login again, then the config properties do not show up – but they are still available via my app.

I still want to have access on them via the dashboard. How can I fix this issue? 

Thanks.

**Comment by NatanRolnik** [comment]
This is a duplicate of #596

**Comment by NatanRolnik** [comment]
@Foody this issue was fixed in the latest release.
