### ISSUE TITLE
Why My iconsFolder not working?

### ISSUE THREAD

**Issue by kevinlee85** [ParsePlatform/parse-dashboard#636]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=1.0.21 of Parse Dashboard.

- [ ] You're running version >=2.2.24 of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
I have added icon folder to my Dashboard, but it only show x on the app.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by kevinlee85** [comment]
Below is part of my configuration file: 
"apps": [
    {
      "iconName": "icon.png"
    }
  ],
  "iconsFolder": "/Users/kevin/Documents/Elance_Projects/Project_PROPASSIONAL/01parse",

**Comment by kevinlee85** [comment]
![screen shot 2017-01-24 at 3 04 57 pm](https://cloud.githubusercontent.com/assets/6616311/22237404/84bfe02e-e246-11e6-9a65-247c43ae1c6c.png)

**Comment by kevinlee85** [comment]
Then no image show up.

**Comment by NatanRolnik** [comment]
@kevinlee85

1 - How are you running it? From the command line passing the config file, or via `npm start`?
2 - What are the logs you're seeing in the command line?
3 - What are the logs you're seeing in the browser?
4 - If you do _Inspect Element_ in the broken image, what's the source URL of the image?

It's hard to give any help without enough information.

**Comment by kevinlee85** [comment]
@NatanRolnik I am launching my Dashboard by config file: parse-dashboard --config xxxx.json. I didn't see any logs from command line. Should I switch log by some commands? There is no log from browser. I upload one snapshot of my Inspect Element.

**Comment by kevinlee85** [comment]
![screen shot 2017-01-25 at 11 29 40 am](https://cloud.githubusercontent.com/assets/6616311/22279702/32a3666e-e307-11e6-988e-0227b401f9a6.png)

**Comment by kevinlee85** [comment]
![screen shot 2017-01-25 at 2 04 14 pm](https://cloud.githubusercontent.com/assets/6616311/22279706/43977000-e307-11e6-9b86-280a47a30da8.png)

**Comment by kevinlee85** [comment]
@NatanRolnik Do you have any advice?

**Comment by NatanRolnik** [comment]
@kevinlee85 sorry it took me so long to help you.
The solution is to place your icons folder in the same directory where the config file is located. It must be there, [and you can see why here](https://github.com/ParsePlatform/parse-dashboard/blob/master/Parse-Dashboard/index.js#L110). 

It's explained [in the Readme](https://github.com/ParsePlatform/parse-dashboard#app-icon-configuration):

> The path of the `iconsFolder` is relative to the configuration file

**Comment by kevinlee85** [comment]
Thank you. 
![screen shot 2017-02-07 at 3 19 35 pm](https://cloud.githubusercontent.com/assets/6616311/22681560/de24d356-ed48-11e6-9031-6a61fb5d138e.png)
![screen shot 2017-02-07 at 3 20 22 pm](https://cloud.githubusercontent.com/assets/6616311/22681583/f943113e-ed48-11e6-9cf3-ca0b9f1df797.png)

**Comment by NatanRolnik** [comment]
So is it working @kevinlee85?

**Comment by kevinlee85** [comment]
@NatanRolnik Yes, Thank you very much.
