### ISSUE TITLE
Can't export class

### ISSUE THREAD

**Issue by serviss1** [ParsePlatform/parse-dashboard#645]
I selected one of my classes to export.  It has been over 4 hours and I have not received an email that it is ready.  When I try to export again it says that it is currently being exported and to wait for the email.  This class usually takes a couple minutes before I get the email.  Not sure where to go from here.

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=1.0.21 of Parse Dashboard.

- [ ] You're running version >=2.2.24 of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by steven-supersolid** [comment]
This project is for the open source version of the dashboard, not the dashboard on parse.com.

You should still be able to get support from Parse by visiting http://parse.com/help and using the 'Contact Us' link which send you in to the Facebook support ticket flow.
