### ISSUE TITLE
DownLoad Freazed

### ISSUE THREAD

**Issue by AMV1818** [ParsePlatform/parse-dashboard#646]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=1.0.21 of Parse Dashboard.

- [ ] You're running version >=2.2.24 of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Steps to reproduce
I can't make any download I tried and stop since yesterday. Please help
User andre.vas@delfostelematics.com.br 
Application: DriverAlertParse

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by codegefluester** [comment]
What download are you referring too? Can you please fill out the issue template completely?

**Comment by NatanRolnik** [comment]
@codegefluester I have a feeling that this is another case of users trying to export their data to JSON...

**Comment by codegefluester** [comment]
@NatanRolnik Agreed, that ship sailed now though
