### ISSUE TITLE
Download/Export data options not responsive

### ISSUE THREAD

**Issue by jasmrowe** [ParsePlatform/parse-dashboard#648]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=1.0.21 of Parse Dashboard.

- [ ] You're running version >=2.2.24 of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Steps to reproduce
Trying to export data for several days now with no success. The dashboard appears to be stuck in "preparing for download" mode and never sends out the email with links to the .zip. Please advise!

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by codegefluester** [comment]
In case you're referring to the "Export Data" feature on parse.com, this feature isn't supported anymore and you should instead follow the official migration guid to export your data, see parse.com/migration.

**Comment by codegefluester** [comment]
Closing for now
