### ISSUE TITLE
Cannot edit values data browser.

### ISSUE THREAD

**Issue by skynext** [ParsePlatform/parse-dashboard#651]
Hi, I'try to manually edit values in the data browser browser from the Parse Dashboard but the new values aren't save.
(It worked with the dashboard available on Parse.com)
Can someone help me ?
thanks

#### Environment Setup
Parse Serve 2.3.2
Parse Dashboard 1.0.23

**Comment by NatanRolnik** [comment]
Do you have some logs from the server to begin with?

**Comment by skynext** [comment]
Yes but I'think that the error that the logs describes are related to an other problem  (https://github.com/ParsePlatform/parse-server/issues/3462)

> 2017-02-01T11:19:49.926Z - Uncaught internal server error. { [MongoError: Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\r\nStack trace: Error: Invalid argument. Query root must be specified.\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\n   at Global code (__.sys.commonUpdate.js:1:2)"]}
ActivityId: add3fff4-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p]
  name: 'MongoError',
  message: 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: add3fff4-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p',
  _t: 'OKMongoResponse',
  ok: 0,
  code: 2,
  errmsg: 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: add3fff4-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p',
  '$err': 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: add3fff4-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p' } MongoError: Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\r\nStack trace: Error: Invalid argument. Query root must be specified.\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\n   at Global code (__.sys.commonUpdate.js:1:2)"]}
ActivityId: add3fff4-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p
    at Function.MongoError.create (D:\home\site\wwwroot\node_modules\parse-server\node_modules\mongodb\node_modules\mongodb-core\lib\error.js:31:11)
    at D:\home\site\wwwroot\node_modules\parse-server\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:462:72
    at authenticateStragglers (D:\home\site\wwwroot\node_modules\parse-server\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:410:16)
    at null.messageHandler (D:\home\site\wwwroot\node_modules\parse-server\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:444:5)
    at TLSSocket.<anonymous> (D:\home\site\wwwroot\node_modules\parse-server\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:306:22)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:536:20)
2017-02-01T11:19:49.926Z - Error generating response. { [MongoError: Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\r\nStack trace: Error: Invalid argument. Query root must be specified.\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\n   at Global code (__.sys.commonUpdate.js:1:2)"]}
ActivityId: add3fff4-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p]
  name: 'MongoError',
  message: 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: add3fff4-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p',
  _t: 'OKMongoResponse',
  ok: 0,
  code: 2,
  errmsg: 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: add3fff4-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p',
  '$err': 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: add3fff4-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p' }
2017-02-01T10:09:00.786Z - Uncaught internal server error. { [MongoError: Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\r\nStack trace: Error: Invalid argument. Query root must be specified.\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\n   at Global code (__.sys.commonUpdate.js:1:2)"]}
ActivityId: bd8e14ac-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p]
  name: 'MongoError',
  message: 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: bd8e14ac-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p',
  _t: 'OKMongoResponse',
  ok: 0,
  code: 2,
  errmsg: 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: bd8e14ac-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p',
  '$err': 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: bd8e14ac-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p' } MongoError: Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\r\nStack trace: Error: Invalid argument. Query root must be specified.\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\n   at Global code (__.sys.commonUpdate.js:1:2)"]}
ActivityId: bd8e14ac-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p
    at Function.MongoError.create (D:\home\site\wwwroot\node_modules\parse-server\node_modules\mongodb\node_modules\mongodb-core\lib\error.js:31:11)
    at D:\home\site\wwwroot\node_modules\parse-server\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:462:72
    at authenticateStragglers (D:\home\site\wwwroot\node_modules\parse-server\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:410:16)
    at null.messageHandler (D:\home\site\wwwroot\node_modules\parse-server\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:444:5)
    at TLSSocket.<anonymous> (D:\home\site\wwwroot\node_modules\parse-server\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:306:22)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:536:20)

**Comment by NatanRolnik** [comment]
Interesting enough, this is the same error that is seen here: ParsePlatform/parse-server#3462
Can you give more details about where are you running the server, the dashboard, the database, etc...?

**Comment by skynext** [comment]
I'run the server, the dashboard and the database (I'use DocumentDB ) on Microsoft Azure. I've deploy parse server using the tools brought by Microsoft (https://github.com/felixrieseberg/parse-server-azure). I encountered the problem on parse server version 2.3.1 and 2.3.2. This worked a while on 2.2 but suddenly the problem appeared.

**Comment by NatanRolnik** [comment]
That's interesting, the issue that I mentioned is also happening on Azure.

**Comment by flovilmart** [comment]
The stack trace bleads DocumentDB `(.sys.commonUpdate.js:2288:17) at`**docDbMain**`(.sys.commonUpdate.js:4:5)\n at Global code`

**Comment by NatanRolnik** [comment]
Closing this as fixed by the Azure team. See more on [this issue](https://github.com/ParsePlatform/parse-server/issues/3462)
