### ISSUE TITLE
Push Notifications on Parse Server

### ISSUE THREAD

**Issue by kaifucious** [ParsePlatform/parse-dashboard#663]
I'm sure this might have been answered somewhere before but for the life of me I can't find it, My Parse Server notifications are fired successfully with no failure when calling pushNotification.sendInBackground(), but the notification never reaches another targeted user, and in Parse dashboard it reads N/A. Has this ever been resolved?

**Comment by natanrolnik** [comment]
`pushNotification.sendInBackground()` - are you trying to send from the client?

**Comment by natanrolnik** [comment]
Well, I see you also cross-opened at ParsePlatform/parse-server#3521...
