### ISSUE TITLE
Error: spawn ./ngrok.exe ENOENT.I need help

### ISSUE THREAD

**Issue by IceAgeQQ** [ParsePlatform/parse-dashboard#673]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ √] You're running version >=1.0.23 of Parse Dashboard.

- [√ ] You're running version >=2.3.2 of Parse Server.

- [√ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./ngrok.exe ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

how to solve this problem?

**Comment by flovilmart** [comment]
That seems unrelated to parse-server. Your failing command is ngrok.exe

**Comment by IceAgeQQ** [comment]
@flovilmart I have tried to rm/reinstall/update the ngrok,but it is still not working.I don't know why...

**Comment by flovilmart** [comment]
But parse-dashboard doesn't require ngrok. I'm not sure why you reported that issue on that repository

**Comment by dvanwinkle** [comment]
@IceAgeQQ It looks like you're not adding the port number to ngrok. Try running it with the port number after the command: `ngrok 1234` if your port number is `1234`.
