### ISSUE TITLE
fails on node-sass during npm install on ubuntu linux 14.04 LTS

### ISSUE THREAD

**Issue by mikepaggi** [ParsePlatform/parse-dashboard#68]
fails on node-sass during npm install on ubuntu linux 14.04 LTS

**Comment by drew-gross** [comment]
Have you tried pulling the latest version? We updated the `node-sass` package, which fixed this issue for some people. If not, the `node-sass` package on `npm` has some instructions for fixing issues on Ubuntu: https://www.npmjs.com/package/node-sass

**Comment by DazChong** [comment]
try to use `screen` + `npm start`

**Comment by drew-gross** [comment]
no response for 10 days, closing
