### ISSUE TITLE
can't find master key in back4app.com

### ISSUE THREAD

**Issue by Rohit-Jadhav13** [ParsePlatform/parse-dashboard#680]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by natanrolnik** [comment]
Please head over to back4app support. This repo's issues has nothing to do with back4app - only bugs in Parse Server itself.
