### ISSUE TITLE
Server not reachable: server version too low

### ISSUE THREAD

**Issue by Krajiyah** [ParsePlatform/parse-dashboard#69]
I freshly pulled from this repository for Parse Dashboard and my parse-server module works on heroku...i've been using it with my apps, but I wanted to install the parse dashboard too as a seperate heroku app. Before even trying to push to heroku I get issues locally:

My config file for the parse dashboard has the server url in this format: 
http://herokuappname.herokuapp.com/parse

When I check console errors in chrome on the Parse Dashboard it says: "Server not reachable: server version too low" also says in console that it couldnt find the serverInfo page on my parse-server.

![asd](https://cloud.githubusercontent.com/assets/10042218/13551237/d4897cbe-e2e7-11e5-85d4-ec6df0c79dac.png)

Can someone please tell me what im doing wrong? Not sure if server version is too low, since I took the parse-server from github.

**Comment by Krajiyah** [comment]
sorry issue was having version 2.1.3 instead of 2.1.4

**Comment by istx25** [comment]
How do I download/upgrade to 2.1.4 instead of what I'm on right now and/how do I check what I'm on right now?
