### ISSUE TITLE
push notifications and analytics dashboard

### ISSUE THREAD

**Issue by hoangtrongphuc** [ParsePlatform/parse-dashboard#71]
How to use push notify in parse-dashboard ?

**Comment by drew-gross** [comment]
Push isn't supported in Parse-Dashboard yet, because it uses a few features that aren't available in Parse.com. We'd happily accept a PR that adds it, and I would be glad to provide pointers to where to look in the code if you are interested in implementing it.

**Comment by hoangtrongphuc** [comment]
yes thanks for reply, In dashboard folder, i can see analytics folder, but when deploy i can't see this feature. How can i use ?

**Comment by chavanshashank** [comment]
+1

**Comment by greggmojica** [comment]
+1

**Comment by thamer898** [comment]
+1

**Comment by senpng** [comment]
+1

**Comment by ronaldo-getreveel** [comment]
+1

**Comment by alyssoncm** [comment]
+1

**Comment by meoz** [comment]
+1

**Comment by Apptation** [comment]
+1

**Comment by darkkiss** [comment]
+1

**Comment by d8815460** [comment]
+1

**Comment by alekoleg** [comment]
+1

**Comment by jcguarinpenaranda** [comment]
+1

**Comment by MeMTn** [comment]
+1

**Comment by zettlunic** [comment]
:+1:

**Comment by astanton** [comment]
+1 for the analytics in dashboard!

**Comment by justforfun** [comment]
+1 for push notification UI and analytics too

**Comment by leonereveel** [comment]
:+1:

**Comment by felipemobile** [comment]
Hi @drew-gross , where can I find a roadmap or deadline for Push notifications on Parse Dashboard?
I'm interested in this subject since I have to provide it to my customers.

**Comment by drew-gross** [comment]
We don't have a roadmap right now. If you want to help implement this feature, I can give you some pointers.

**Comment by darkkiss** [comment]
Hello @drew-gross, I am tracking server developments and I saw push is about to "emerge".
Can I have those pointers about implementing in dashboard?

As I've studied the dashboard I saw almost all features are currently somewhat integrated in it, but lacks of endpoint (server) configuration.

**Comment by felipemobile** [comment]
Yes i'm interested, I'll really appreciate if you can give those pointers for me to handle that. I've 25+ apps to be ported to our hosted Parse Server/Dashboard.

**Comment by felipemobile** [comment]
@darkkiss Push is already available on Parse Server. I've been using it via CURL.

**Comment by peterdotjs** [comment]
@felipemobile @darkkiss I'll add a separate discussion issue to document our existing schema in the dash and the path forward to integrating with parse-server as new endpoints are created.

**Comment by felipemobile** [comment]
@peterdotjs thanks!

**Comment by khafagy** [comment]
+1

**Comment by drew-gross** [comment]
Sending push notifications will be available after #192 lands
