### ISSUE TITLE
Warning: setState(...): Cannot update during an existing state transition ....

### ISSUE THREAD

**Issue by Krajiyah** [ParsePlatform/parse-dashboard#73]
I ran my parse dashboard with following commands:
`export PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1`
`npm run dashboard`

I have a semi working parse dashboard, where I can click the first app and it leads me to the next page.

However, when I click the second app....the console on chrome gives me this error and wont let me progress to next page:
Warning: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.

![asdasdasd](https://cloud.githubusercontent.com/assets/10042218/13553164/7173a274-e334-11e5-80c5-dad23dc645ac.png)

Please help!

**Comment by peterdotjs** [comment]
@Krajiyah could you provide the stack trace (expanding the arrow on the left) may or may not be helpful to point to where it is failing.

**Comment by peterdotjs** [comment]
@Krajiyah I'm able to repro the issue locally. I'll give an update once I've found what went wrong.

**Comment by Krajiyah** [comment]
Here is full strack trace:

Warning: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.warning @ dashboard.bundle.js:18835getInternalInstanceReadyForUpdate @ dashboard.bundle.js:22556ReactUpdateQueue.enqueueSetState @ dashboard.bundle.js:22697ReactComponent.setState @ dashboard.bundle.js:32559(anonymous function) @ dashboard.bundle.js:42475(anonymous function) @ dashboard.bundle.js:44363(anonymous function) @ dashboard.bundle.js:44199(anonymous function) @ dashboard.bundle.js:44235done @ dashboard.bundle.js:45194(anonymous function) @ dashboard.bundle.js:45200getComponentsForRoute @ dashboard.bundle.js:45290(anonymous function) @ dashboard.bundle.js:45309(anonymous function) @ dashboard.bundle.js:45199mapAsync @ dashboard.bundle.js:45198getComponents @ dashboard.bundle.js:45308(anonymous function) @ dashboard.bundle.js:44231runEnterHooks @ dashboard.bundle.js:45114finishMatch @ dashboard.bundle.js:44224(anonymous function) @ dashboard.bundle.js:44197done @ dashboard.bundle.js:45158(anonymous function) @ dashboard.bundle.js:45448(anonymous function) @ dashboard.bundle.js:45417done @ dashboard.bundle.js:45158(anonymous function) @ dashboard.bundle.js:45448(anonymous function) @ dashboard.bundle.js:45399getIndexRoute @ dashboard.bundle.js:45350matchRouteDeep @ dashboard.bundle.js:45393(anonymous function) @ dashboard.bundle.js:45446next @ dashboard.bundle.js:45165loopAsync @ dashboard.bundle.js:45171matchRoutes @ dashboard.bundle.js:45445(anonymous function) @ dashboard.bundle.js:45411getChildRoutes @ dashboard.bundle.js:45332matchRouteDeep @ dashboard.bundle.js:45406(anonymous function) @ dashboard.bundle.js:45446next @ dashboard.bundle.js:45165(anonymous function) @ dashboard.bundle.js:45450(anonymous function) @ dashboard.bundle.js:45423getChildRoutes @ dashboard.bundle.js:45338matchRouteDeep @ dashboard.bundle.js:45406(anonymous function) @ dashboard.bundle.js:45446next @ dashboard.bundle.js:45165loopAsync @ dashboard.bundle.js:45171matchRoutes @ dashboard.bundle.js:45445match @ dashboard.bundle.js:44193(anonymous function) @ dashboard.bundle.js:44359(anonymous function) @ dashboard.bundle.js:44435(anonymous function) @ dashboard.bundle.js:43193updateLocation @ dashboard.bundle.js:43192(anonymous function) @ dashboard.bundle.js:43279(anonymous function) @ dashboard.bundle.js:43260done @ dashboard.bundle.js:43507next @ dashboard.bundle.js:43516loopAsync @ dashboard.bundle.js:43520confirmTransitionTo @ dashboard.bundle.js:43246transitionTo @ dashboard.bundle.js:43274replaceState @ dashboard.bundle.js:43294render @ dashboard.bundle.js:50295ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ dashboard.bundle.js:24318ReactCompositeComponentMixin._renderValidatedComponent @ dashboard.bundle.js:24338wrapper @ dashboard.bundle.js:18069ReactCompositeComponentMixin.mountComponent @ dashboard.bundle.js:23951wrapper @ dashboard.bundle.js:18069ReactReconciler.mountComponent @ dashboard.bundle.js:22261ReactCompositeComponentMixin._updateRenderedComponent @ dashboard.bundle.js:24301ReactCompositeComponentMixin._performComponentUpdate @ dashboard.bundle.js:24275ReactCompositeComponentMixin.updateComponent @ dashboard.bundle.js:24204wrapper @ dashboard.bundle.js:18069ReactCompositeComponentMixin.receiveComponent @ dashboard.bundle.js:24136ReactReconciler.receiveComponent @ dashboard.bundle.js:22311ReactCompositeComponentMixin._updateRenderedComponent @ dashboard.bundle.js:24293ReactCompositeComponentMixin._performComponentUpdate @ dashboard.bundle.js:24275ReactCompositeComponentMixin.updateComponent @ dashboard.bundle.js:24204wrapper @ dashboard.bundle.js:18069ReactCompositeComponentMixin.receiveComponent @ dashboard.bundle.js:24136ReactReconciler.receiveComponent @ dashboard.bundle.js:22311ReactCompositeComponentMixin._updateRenderedComponent @ dashboard.bundle.js:24293ReactCompositeComponentMixin._performComponentUpdate @ dashboard.bundle.js:24275ReactCompositeComponentMixin.updateComponent @ dashboard.bundle.js:24204wrapper @ dashboard.bundle.js:18069ReactCompositeComponentMixin.performUpdateIfNecessary @ dashboard.bundle.js:24152ReactReconciler.performUpdateIfNecessary @ dashboard.bundle.js:22326runBatchedUpdates @ dashboard.bundle.js:22908Mixin.perform @ dashboard.bundle.js:23368Mixin.perform @ dashboard.bundle.js:23368assign.perform @ dashboard.bundle.js:22865flushBatchedUpdates @ dashboard.bundle.js:22926wrapper @ dashboard.bundle.js:18069Mixin.closeAll @ dashboard.bundle.js:23434Mixin.perform @ dashboard.bundle.js:23381ReactDefaultBatchingStrategy.batchedUpdates @ dashboard.bundle.js:27401batchedUpdates @ dashboard.bundle.js:22873ReactEventListener.dispatchEvent @ dashboard.bundle.js:31529

**Comment by peterdotjs** [comment]
@Krajiyah could you pull the latest and execute `npm run dev` and provide some more detailed stack information again.

This will help point to the file and line of the error. It would also be helpful if you provide a screen shot of the debugger/console/network.

**Comment by peterdotjs** [comment]
@Krajiyah is this resolved? I'm assuming yes from the other issue you created.
