### ISSUE TITLE
  Parse Dashboard can only be remotely accessed via HTTPS

### ISSUE THREAD

**Issue by trikiano** [ParsePlatform/parse-dashboard#74]
Parse Dashboard can only be remotely accessed via HTTPS

i don't have a https in my server 
can i desactivate https just for test dashboard

**Comment by peterdotjs** [comment]
Details of workaround are here: https://github.com/ParsePlatform/parse-dashboard#deploying-in-production

**Comment by manoj-singh-developer** [comment]
The change is

app.use('/parse-dashboard', new ParseDashboard(config.dashboard, { allowInsecureHTTP: true }));

instead of

app.use('/parse-dashboard', ParseDashboard(config.dashboard, true));

you will find this code in index.js
