### ISSUE TITLE
Blank screen opening localhost:4040

### ISSUE THREAD

**Issue by BloomSN** [ParsePlatform/parse-dashboard#75]
Hi,

might be completely stupid question but still, i am trying to set up this on windows server 2012 r2 with npm 3.8.1 and Node.js 4.3.2 all goes well but when i am trying to access dashboard (i have set link to app hosted on parse.com) i get white screen on localhost:4040. Any idea?

Thanks a lot.

**Comment by peterdotjs** [comment]
@BloomSN can you provide a screen shot of any console errors you see in the browser? As well as any logs/errors you see in the terminal that is running the server?

**Comment by BloomSN** [comment]
<img width="552" alt="server_remote" src="https://cloud.githubusercontent.com/assets/5353463/13555214/d952faee-e3ba-11e5-8bd7-68f68cb77b74.png">
<img width="575" alt="server_remote" src="https://cloud.githubusercontent.com/assets/5353463/13555218/e9fd8170-e3ba-11e5-99d9-7fd333f93a3e.png">


Here are both screens. Hope it helps, if you need more i will get more :)

Thanks

**Comment by thamer898** [comment]
Hello

now i get this error "Your parse‑dashboard‑config.json file contains invalid JSON."

Regards

**Comment by drew-gross** [comment]
I've seen this issue before, it's due to the express app serving `index.html` even when the request is for `dashboard.bundle.js`. I haven't had the chance to track down the error yet.

**Comment by flovilmart** [comment]
Should be fixed with #76

**Comment by thamer898** [comment]
@flovilmart how to update parse server example to be 2.1.4 without any errors ?

**Comment by BloomSN** [comment]
Great the fix works :) Thanks

**Comment by natanrolnik** [comment]
I'm having the same `Unexpected token <` when deploying to Heroku.
On `localhost`, it works fine and I can see my apps. On Heroku, I'm setting `PARSE_DASHBOARD_ALLOW_INSECURE_HTTP` to `1`. I'm using version 1.0.9.

Any ideas why I'm having this error?

**Comment by drew-gross** [comment]
That usually means the dashboard never got built. If you follow the instructions in the `README` and install from `npm` you should get the already-built dashboard.

**Comment by natanrolnik** [comment]
So instead of deploying the fork of this repo, I setup a new project using the `parse-dashboard` npm package, and it's working great, deployed to Heroku. I also added a CNAME dns record on my domain, so I can have parse.mydomain.com 😃
