### ISSUE TITLE
npm install failed with Node v5.7

### ISSUE THREAD

**Issue by clonezer** [ParsePlatform/parse-dashboard#77]
I've install Parse Server on Digital Ocean and it's run smoothly but when install `parse dashboard` I got this error

```
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
```

Server details
```
Ubuntu 14.04 64bit
NodeJS v. 5.7.1
npm v. 3.6.0
```

**Comment by peterdotjs** [comment]
Related to an older version of `sass-loader`. I'll add a PR to update the version.

**Comment by peterdotjs** [comment]
@clonezer could you pull the latest and test it out?

**Comment by clonezer** [comment]
Thank you @peterdotjs  but I still got error
![screen shot 2559-03-07 at 3 17 20 am](https://cloud.githubusercontent.com/assets/582587/13556717/58cbab88-e413-11e5-9f9e-644ed529baf6.png)

**Comment by peterdotjs** [comment]
@clonezer looking at it closer - it's not a direct dependency that is failing. It's node-sass -> gaze ->  globule -> glob -> graceful-fs. We don't have any control over the dependencies our dependencies use. 

Is it possible for you to use `node ~4.3`?

**Comment by peterdotjs** [comment]
@clonezer looking closer there are several node_modules further down their dependency tree which use an older version of `graceful-fs`. A workaround is to use `node version ~4.3` until we figure out how if possible to resolve this.

**Comment by drew-gross** [comment]
We've overhauled the installation process. Check the readme for details. That should fix this issue.
