### ISSUE TITLE
Parse Dashboard

### ISSUE THREAD

**Issue by thamer898** [ParsePlatform/parse-dashboard#78]
Hello

When i locate to localhost:4040 only white screen appear can you help me please ?

Regards

**Comment by peterdotjs** [comment]
Likely a duplicate of #75

**Comment by thamer898** [comment]
Hello

How to solve this issue @peterdotjs ? can you help me

Regards

**Comment by peterdotjs** [comment]
@thamer898 can you verify from your browser console that you're getting the same error? If so please close this issue and ref #75 for tracking.

**Comment by thamer898** [comment]
Hello

yes i get the same error ?

Regards
