### ISSUE TITLE
invalid json file in parse dashboard ?

### ISSUE THREAD

**Issue by thamer898** [ParsePlatform/parse-dashboard#79]
Hello

now i get this error "Your parse‑dashboard‑config.json file contains invalid JSON."

Regards

**Comment by peterdotjs** [comment]
@thamer898 please check `parse‑dashboard‑config.json` and ensure that is is valid JSON. This is a valid error.

**Comment by thamer898** [comment]
Hello

still the same error .

Regards

**Comment by drew-gross** [comment]
Try pasting your JSON file into a JSON validator.

**Comment by thamer898** [comment]
thank you it works @drew-gross but i have a problem that i cone the parse server from parse server example repository so i want to upgrade my parse version to be 2.1.4 in order to run parse Dashboard can you help me with that please ?

**Comment by drew-gross** [comment]
You just need to update the `parse-server` line in your project's `package.json` and then run `npm install` again.

**Comment by thamer898** [comment]
can you give me a sample example @drew-gross please note that i update the line like this "
    "parse-server": "~2.1.4"  but when i hit npm install the screen stuck ?

**Comment by drew-gross** [comment]
That is the correct method. If `npm install` is stuck, that sounds like a problem with `npm`.

**Comment by thamer898** [comment]
i will try your method again , please give me a minute .

**Comment by thamer898** [comment]
okay i update the version to be ~2.1.4 but this error appear "you must provide server url" ? kindly advice .

**Comment by drew-gross** [comment]
You need to make sure you include the server URL in the configuration of your parse server. You probably want to use `http://localhost:<%your_port%>/<%your_mount>%`

**Comment by thamer898** [comment]
i used this serverURL: 'http://localhost:1337/parse' but many errors occur if you need i will screenshot it  .

**Comment by drew-gross** [comment]
Yes I will need to know what errors you are seeing and see your full configuration before I can help.

**Comment by thamer898** [comment]
![error](https://cloud.githubusercontent.com/assets/17239124/13556682/bfd24e48-e3e8-11e5-96a7-289f01e4466b.PNG)

kindly see it

**Comment by drew-gross** [comment]
That is a syntax error. Maybe you forgot to put a comma at the end of this line, or at the end of the previous line?

**Comment by thamer898** [comment]
thank you very much @drew-gross  you are great this what i missed a comma thank a lot for your help .
