### ISSUE TITLE
Dashboard error

### ISSUE THREAD

**Issue by thamer898** [ParsePlatform/parse-dashboard#83]
![error](https://cloud.githubusercontent.com/assets/17239124/13556050/2ecfa684-e3d9-11e5-96cc-9b12ea5504cb.PNG)

this happen when i locate localhost:4040 ?

**Comment by flovilmart** [comment]
That's because your JSON file is not a valid json. Refer to the README.md and make sure your file is properly formatted.

**Comment by thamer898** [comment]
Hello

Thank you very much it works .

regards
