### ISSUE TITLE
error at main page

### ISSUE THREAD

**Issue by thamer898** [ParsePlatform/parse-dashboard#84]
![error](https://cloud.githubusercontent.com/assets/17239124/13556159/73e90cf4-e3db-11e5-9ee5-d8b8c05cc5f6.PNG)

this error appear "server version is too low " please help me .

**Comment by peterdotjs** [comment]
@thamer898 you need to be using `parse-server` version `>= 2.1.4`. This info is on the README.

**Comment by thamer898** [comment]
Hello

How to update my parse server ?

Regards
