### ISSUE TITLE
Unable to upload files

### ISSUE THREAD

**Issue by dcdspace** [ParsePlatform/parse-dashboard#90]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [√ ] You're running version >=2.1.4 of Parse Server.

- [ √] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Parse Server 2.1.4 on Heroku
Database on Mongolab
Not yet using S3 adapter, so still on the default Gridstore for saving new files

#### Steps to reproduce
Try and upload file (image) in dashboard

#### Logs/Trace
Error saying "Unable to connect to Parse API" when trying to upload a file.

**Comment by drew-gross** [comment]
This actually looks like a Parse Server issue, it seems like Parse Server isn't issuing the correct headers for file uploads.

**Comment by drew-gross** [comment]
This if fixed by ParsePlatform/parse-server#876 and the fix will be available in the next server version.

**Comment by w3care25** [comment]
add javascript key in dashboard config if you are trying to upload images from dashboard.
