### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by amirfarazmand** [ParsePlatform/parse-dashboard#91]
I get this error:
Uncaught SyntaxError: Unexpected token < dashboard.bundle.js:1 

and when I check under Parse-Dashboard this file is missing:

/bundles/dashboard.bundle.js

**Comment by drew-gross** [comment]
This should be fixed by #65 try pulling the latest version and see if that helps.

**Comment by amirfarazmand** [comment]
Excellent Drew. Thanks

**Comment by larcoamir** [comment]
> This should be fixed by #65 try pulling the latest version and see if that helps.

I cloned and getting the same error

**Comment by larcoamir** [comment]
> This should be fixed by #65 try pulling the latest version and see if that helps.

@drew-gross I cloned and getting the same error
