### ISSUE TITLE
Question: Why do you only release 50% of parse, when you know that 90% is forced to leave anyways - because parse-server (for now) is unusable for most users.

### ISSUE THREAD

**Issue by hjgabrielsen** [ParsePlatform/parse-dashboard#94]
I really don't get you guys, You announce that you are helping people move on, but really, you are just making the breakup harder by abandoning customers with 1/2 a product.

**Comment by rblalock** [comment]
I disagree.  What Parse is doing is awesome and very helpful.  They didn't have to do any of this but they are and the result is a decent community contributing to the parse server, etc.

**Comment by flovilmart** [comment]
@hjgabrielsen you're welcome to help us do the last 50%. As we discussed over (here)[https://github.com/ParsePlatform/parse-dashboard/pull/63] 

From @drew-gross from ParseHQ
> Yeah, the go version is massively multi-tenant and includes tons of multi-tenant specific code. It also relies on like 6 different databases, takes 2-3 days to get it running, and would be unlikely to fit in the smallest tier on any IaaS provider. I wouldn't have been a good experience.

**Comment by gfosco** [comment]
I'd encourage some patience.  It's been 39 days and we've come a long way.  Nothing is being abandoned.  695 commits by 49 contributors since launch, 298 pull requests...  It's a fast-moving and growing community.

See https://medium.com/@newfosco/parse-2-0-600839abebdf and http://blog.parse.com/announcements/what-is-parse-server/

**Comment by hjgabrielsen** [comment]
Look, Why didn't parse release everything?! : (Jobs, Push, Dashbord, CloudCode support) to begin with (They're not going to use it anyways) - instead they are  letting DEVs build the rest themselves? (Something that already exists) (The reason why Facebook didn't abandon all their 600.000 DEVs completely - is because they didn't want to end up in a giant shitstorm. so thy're giving us a lollypop to be quiet.

**Comment by rblalock** [comment]
Things like jobs and cloud code have to be taken in to account in the way parse-server works.  It's not just a matter of magically releasing something that already existed...it has to be released in a way that works with parse-server.

**Comment by flovilmart** [comment]
I can tell you that the whole parse team is full time on improving the server and dashboard. 
Push and CloudCode are implemented, there are alternatives opening to run cloud code on a separate server if you're worried about scaling. 
Dashboard is available too! https://github.com/parseplatform/parse-dashboard

As for Jobs, heroku has a worker API that is designed just for that, AWS provides workers in elastic beanstalk, and GAE got a cron API that is quite powerful. In the end, you're better off with Jobs not being part of parse-server!

**Comment by iatek** [comment]
> "because parse-server (for now) is unusable for most users"

I felt that way too several weeks ago, but it has really come a long way since. It's very usable and I have had a production app running on my self-hosted parse-server for a week or so. Mostly everything is working for me now.. complex queries, Twitter login, and even the /files api where my files are stored via the Mongo adapter.

**Comment by flovilmart** [comment]
yeah, stability and feature parity is our main concern now. And we consider deeply every pull request. New features are added almost every week, and more bug fixes come in every day. We're very very close to feature parity. I would not call it 'production ready' only time will tell.

**Comment by hjgabrielsen** [comment]
Glad that you guys (and girls) are happy now, but noone has really answered, why parse haven't released everything at once. My best guess it that a lot of what parse was built on - is proprietary code - and not eligble for open-source..

**Comment by flovilmart** [comment]
@hjgabrielsen https://github.com/ParsePlatform/parse-dashboard/pull/63#issuecomment-192781437
