### ISSUE TITLE
How to make https for parse dashboard?

### ISSUE THREAD

**Issue by kenglou** [ParsePlatform/parse-dashboard#96]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ yes] You're running version >=2.1.4 of Parse Server.

- [ yes] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Ubuntu Server

#### Problem
I wish to know what is the steps or any clue on implementing the https on ubuntu server. Currently I'm using Apache2 and i already enabled the HTTPS from using the guid in Ubuntu, but unfortunately I doesn't know how to turn on the https for the nodejs. I'm refering the [link](https://help.ubuntu.com/lts/serverguide/httpd.html) to configure the https.

**Comment by flovilmart** [comment]
If you're sure of what you're doing, you can use --allowInsecuretHTTP=1 or set the env variable PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1

**Comment by ronaldo-getreveel** [comment]
Or you can use LetsEncrypt and generate your certificates for apache server (its opensource and free). 

https://letsencrypt.org/

**Comment by drew-gross** [comment]
Thanks @ronaldo-getreveel! I'd also recommend LetsEncrypt for https. You can also run the dashboard locally, which doesn't require https.
