### ISSUE TITLE
Dashboard shows https error even after we created https url

### ISSUE THREAD

**Issue by krishnakumarcitrus** [ParsePlatform/parse-dashboard#97]
#### Environment Setup
We set up https using NGINX and tried remote access, but still the error "Parse Dashboard can only be remotely accessed via HTTPS" is shown.

Do you know where i might have gone wrong?

**Comment by flovilmart** [comment]
See [here](https://github.com/ParsePlatform/parse-dashboard#deploying-in-production) there is a way to bypass the https problem if you have your https handled with a proxy

**Comment by drew-gross** [comment]
For some more detail, the server requires https to the node instance directly. Early SSL termination is secure, but the node instance doesn't know that, so if you are using early SSL termination, you need to tell the node instance that it's OK to use HTTP.
